Repository SAP/ui5-webcomponents, pull requests merged in 2020-12, with the labels that each got.

#2385 fix(ui5-textarea): announce required textarea
  packages/main/src/TextArea.hbs
  packages/main/test/pages/TextArea.html
Labels: ACC, SF, for review

#2546 fix(ui5-tree): make the height of tree adjustable
  packages/main/src/Tree.hbs
  packages/main/src/themes/Tree.css
Labels: for review

#2566 fix(ui5-button): hide icon tooltip
  packages/main/src/Button.hbs
  packages/main/test/pages/Button.html
Labels: SF, for review

#2577 fix(ui5-card): correct aria-labelledBy to card and header
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/test/pages/Card.html
  packages/main/test/specs/Card.spec.js
Labels: for review

#2571 refactor(ui5-flexible-column-layout): Add more accessibility texts
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/FCLApp.html
  packages/fiori/test/specs/FCL.spec.js
Labels: SF, for review

#2580 refactor(ui5-notification-action): rename component
  docs/Public Module Imports.md
  packages/fiori/bundle.esm.js
  packages/fiori/src/NotificationAction.js
  packages/fiori/src/NotificationListGroupItem.js
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/NotificationListItemBase.js
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/pages/NotificationList_test_page.html
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
Labels: for review

#2541 feat(framework): Change child-parent invalidation API
  docs/dev/Metadata.md
  packages/base/src/RenderScheduler.js
  packages/base/src/UI5Element.js
  packages/base/src/UI5ElementMetadata.js
  packages/base/src/delegate/ItemNavigation.js
  packages/base/src/util/arraysAreEqual.js
  packages/base/src/util/getActiveElement.js
  packages/base/test/elements/Parent.js
  packages/base/test/specs/UI5ElementInvalidation.js
  packages/base/test/specs/UI5ElementListenForChildPropChanges.spec.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/SideNavigationItem.js
  packages/fiori/src/Wizard.js
  packages/main/src/ComboBox.js
  packages/main/src/ComboBoxItem.hbs
  packages/main/src/ComboBoxItem.js
  packages/main/src/DayPicker.js
  packages/main/src/List.js
  packages/main/src/MonthPicker.js
  packages/main/src/MultiComboBox.js
  packages/main/src/Option.js
  packages/main/src/Select.js
  packages/main/src/TabContainer.js
  packages/main/src/Table.hbs
  packages/main/src/Table.js
  packages/main/src/Tree.hbs
  packages/main/src/Tree.js
  packages/main/src/TreeItem.js
  packages/main/src/YearPicker.js
  packages/main/src/popup-utils/PopupUtils.js
  packages/main/src/themes/ComboBoxItem.css
  packages/main/test/pages/Button.html
  packages/main/test/pages/Simple.html
Labels: for review

#2585 refactor: use ItemNavigation optimally
  packages/fiori/src/ProductSwitch.js
  packages/fiori/src/Timeline.hbs
  packages/fiori/src/Timeline.js
  packages/fiori/src/Wizard.js
  packages/main/src/AvatarGroup.js
  packages/main/src/List.js
  packages/main/src/SegmentedButton.js
  packages/main/src/TabContainer.js
  packages/main/src/Tokenizer.js
Labels: for review

#2582 fix(ui5-avatar): fix XS size
  packages/main/src/themes/Avatar.css
  packages/main/test/pages/AvatarGroup.html
Labels: for review

#2364 docs: add missing docs for stable DOM refs
  packages/fiori/src/ShellBar.js
  packages/main/src/TabContainer.js
Labels: for review

#2586 refactor: Date/time components refactoring part 1
  packages/base/src/delegate/ItemNavigation.js
  packages/main/src/Calendar.js
  packages/main/src/DatePicker.js
  packages/main/src/DayPicker.js
  packages/main/src/MonthPicker.js
  packages/main/src/PickerBase.js
  packages/main/src/TimePicker.js
  packages/main/src/YearPicker.js
  packages/main/src/util/DateTime.js
Labels: for review

#2366 feat(ui5-option): provide stabledomref
  packages/main/src/Option.js
  packages/main/src/Select.js
  packages/main/src/SelectPopover.hbs
Labels: for review

#2596 fix(ui5-wizard): correct phone breakpoint size
  packages/fiori/src/Wizard.js
Labels: for review

#2608 fix(ui5-bar): display ui5-icon properly inside bar
  packages/fiori/src/themes/Bar.css
  packages/fiori/test/pages/Bar.html
Labels: for review

#2603 chore: release v1.0.0-rc.11
  CHANGELOG.md
  packages/base/CHANGELOG.md
  packages/base/package.json
  packages/fiori/CHANGELOG.md
  packages/fiori/package.json
  packages/icons-tnt/CHANGELOG.md
  packages/icons-tnt/package.json
  packages/icons/CHANGELOG.md
  packages/icons/package.json
  packages/localization/CHANGELOG.md
  packages/localization/package.json
  packages/main/CHANGELOG.md
  packages/main/package.json
  packages/playground/CHANGELOG.md
  packages/playground/build-scripts/samples-prepare.js
  packages/playground/docs/landing-page.html
  packages/playground/package.json
  packages/theme-base/CHANGELOG.md
  packages/theme-base/package.json
  packages/tools/CHANGELOG.md
  packages/tools/package.json
Labels: for review
