Repository SAP/ui5-webcomponents, pull requests merged in 2020-07, with the labels that each got.

#1898 feat(ui5-popup): add support for aria-label
  packages/main/src/Dialog.js
  packages/main/src/Input.js
  packages/main/src/Popover.js
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
  packages/main/test/pages/Popover.html
  packages/main/test/specs/Dialog.spec.js
  packages/main/test/specs/Popover.spec.js
Labels: SuccessFactors, for review

#1900 docs: Document the usage of i18n for apps
  docs/i18n.md
  packages/base/bundle.esm.js
  packages/base/src/i18nBundle.js
  packages/base/test/pages/assets/messagebundle_de.properties
  packages/base/test/pages/assets/messagebundle_en.properties
  packages/base/test/pages/assets/messagebundle_es.properties
  packages/base/test/pages/assets/messagebundle_fr.properties
  packages/base/test/pages/i18n.html
Labels: for review

#1899 feat(ui5-list): support aria-label and aria-labelledby
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/test/pages/List_test_page.html
  packages/main/test/specs/List.spec.js
Labels: SuccessFactors, for review

#1905 refactor(framework): getText uses the key as fallback, simplify docs
  docs/i18n.md
  packages/base/src/i18nBundle.js
  packages/base/test/pages/i18n.html
Labels: for review

#1907 chore(ui5-input): add isSuggestionsScrollable method
  packages/main/src/Input.js
  packages/main/src/features/InputSuggestions.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SuccessFactors, for review

#1908 feat(tools): Add more commands to package.json
  docs/dev/Creating UI5 Web Components Packages.md
  packages/fiori/package.json
  packages/main/package.json
  packages/tools/bin/dev.js
  packages/tools/lib/init-package/index.js
Labels: SuccessFactors, for review

#1911 feat(ui5-popover): prevent closing when no opener
  packages/main/src/Input.js
  packages/main/src/Popover.js
  packages/main/src/Popup.js
  packages/main/src/ResponsivePopover.js
  packages/main/src/features/InputSuggestions.js
  packages/main/test/pages/Input.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/Popover.html
  packages/main/test/specs/Input.spec.js
  packages/main/test/specs/Popover.spec.js
Labels: SuccessFactors, for review

#1915 feat(ui5-card): add 'action' slot
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/src/themes/Card.css
  packages/main/test/pages/Card.html
  packages/main/test/specs/Card.spec.js
Labels: SuccessFactors, for review

#1868 feat(framework): implement stabledomref functionality
  packages/base/src/UI5Element.js
  packages/fiori/src/ShellBar.hbs
  packages/fiori/src/ShellBar.js
  packages/fiori/src/ShellBarItem.js
  packages/main/src/Tab.js
  packages/main/src/TabInStrip.hbs
  packages/main/test/pages/TabContainer.html
Labels: SuccessFactors

#1916 fix(ui5-combobox): support arial-labelledby and fix aria-expanded
  packages/main/src/ComboBox.hbs
  packages/main/src/ComboBox.js
  packages/main/test/pages/ComboBox.html
Labels: SuccessFactors, for review

#1890 feature(tools): Support unsafeHTML in HBS compiler
  packages/base/src/renderer/LitRenderer.js
  packages/tools/lib/hbs2lit/src/litVisitor2.js
  packages/tools/lib/hbs2ui5/RenderTemplates/LitRenderer.js
Labels: SuccessFactors, for review

#1921 feat(ui5-input): Support 'inactive' suggestions
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/src/SuggestionItem.js
  packages/main/src/features/InputSuggestions.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SuccessFactors, for review

#1922 chore(ui5-input): Enable separators customization
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
Labels: SuccessFactors, for review

#1897 fix(ui5-upload-collection): The component does not get stuck
  packages/fiori/src/upload-utils/UploadCollectionBodyDnD.js
Labels: MDK, for review

#1909 fix(ui5-textarea): Add missing dependency, extract .hbs partial
  packages/main/src/TextArea.hbs
  packages/main/src/TextArea.js
Labels: Autopilot, for review

#1910 feat(ui5-panel): support aria-label and aria-labelledby
  packages/main/src/Panel.hbs
  packages/main/src/Panel.js
  packages/main/test/pages/Panel.html
  packages/main/test/specs/Panel.spec.js
Labels: SuccessFactors

#1929 fix(framework): make renderImmediately sync, fix lifecycle issues
  packages/base/src/RenderQueue.js
  packages/base/src/RenderScheduler.js
  packages/base/src/UI5Element.js
  packages/base/test/specs/UI5ElementLifecycle.js
  packages/main/test/pages/DialogLifecycle.html
  packages/main/test/specs/Dialog.spec.js
Labels: SuccessFactors, for review

#1952 fix(framework): managedSlots: true always has effect
  packages/base/src/UI5Element.js
Labels: for review

#1956 refactor(ui5-input): Add hook for value update on suggestion preview
  packages/main/src/Input.js
Labels: Autopilot

#1937 refactor(ui5-popover): Keep popup open if focus is inside
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/src/Popover.js
  packages/main/src/Popup.js
  packages/main/src/TextArea.js
  packages/main/src/TextAreaPopover.hbs
  packages/main/src/popup-utils/OpenedPopupsRegistry.js
  packages/main/src/popup-utils/PopupUtils.js
  packages/main/test/pages/Input.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/specs/Input.spec.js
Labels: SuccessFactors, for review

#1964 feat(framework): implement invalidateParent
  docs/dev/Metadata.md
  packages/base/src/UI5Element.js
Labels: for review

#1943 feat(ui5-input): Add highlighting
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/src/SuggestionItem.js
  packages/main/src/SuggestionListItem.hbs
  packages/main/src/SuggestionListItem.js
  packages/main/src/features/InputSuggestions.js
  packages/main/src/themes/ListItemBase.css
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SuccessFactors, for review

#1966 chore(framework): Allow the hidden property for custom elements
  packages/base/src/util/isValidPropertyName.js
Labels: MDK

#1975 feat(ui5-input): announce suggestions count
  packages/main/src/Input.hbs
  packages/main/src/Input.js
  packages/main/src/i18n/messagebundle.properties
Labels: SuccessFactors

#1974 fix(ui5-tabcontainer): prevent the tabcontainer from setting the selected property on ui5-tab internally
  packages/main/src/TabContainer.js
Labels: SuccessFactors

#1978 fix(ui5-tabcontainer): fix accessibility of overflow button
  packages/main/src/TabContainer.hbs
Labels: SuccessFactors

#1889 feat(ui5-side-navigation): initial implementation
  packages/base/src/UI5Element.js
  packages/fiori/bundle.esm.js
  packages/fiori/src/SideNavigation.hbs
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/SideNavigationItem.js
  packages/fiori/src/SideNavigationItemPopoverContent.hbs
  packages/fiori/src/SideNavigationSubItem.js
  packages/fiori/src/themes/SideNavigation.css
  packages/fiori/test/pages/SideNavigation.html
  packages/fiori/test/samples/SideNavigation.sample.html
  packages/fiori/test/specs/SideNavigation.spec.js
  packages/main/src/Tree.hbs
  packages/main/src/Tree.js
  packages/main/src/TreeListItem.hbs
  packages/main/src/TreeListItem.js
  packages/main/src/themes/Title.css
  packages/main/src/themes/TreeListItem.css
  packages/main/src/themes/base/sizes-parameters.css
  packages/playground/build-scripts/samples-prepare.js
  packages/theme-base/css-vars-usage.json
Labels: for review

#1979 fix(ui5-input): sync width of suggestions popover and input
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SuccessFactors

#1994 fix(tools): Building third-party packages no longer fails
  packages/theme-base/package-scripts.js
  packages/tools/components-package/nps.js
  packages/tools/lib/generate-json-imports/themes.js
  packages/tools/lib/init-package/index.js
  packages/tools/lib/init-package/resources/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/tools/lib/init-package/resources/src/themes/sap_fiori_3_hcw/parameters-bundle.css
Labels: RC8 Testing, for review

#1997 feat(ui5-li): Support 'Information' infoState
  packages/main/src/StandardListItem.js
  packages/main/src/themes/ListItem.css
  packages/main/test/pages/List.html
  packages/main/test/samples/List.sample.html
Labels: Autopilot

#2002 chore(ui5-button): fix docs
  packages/base/src/util/isValidPropertyName.js
  packages/main/src/Button.js
Labels: RC8 Testing

#2011 fix: lists no longer show a dot on IE
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListItem.hbs
  packages/main/src/GroupHeaderListItem.hbs
  packages/main/src/List.hbs
  packages/main/src/ListItem.hbs
  packages/main/src/TabContainer.hbs
  packages/main/src/TabInStrip.hbs
  packages/main/src/TabSeparator.hbs
  packages/main/src/Timeline.hbs
  packages/main/src/WheelSlider.hbs
Labels: RC8 Testing, for review

#2014 fix(ui5-carousel): make content under the navigation arrows accessible
  packages/main/src/themes/Carousel.css
Labels: RC8 Testing, for review

#1987 refactor(ui5-flexlible-column-layout): Custom layouts configuration
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/test/pages/FCLCustom.html
Labels: SuccessFactors
