Repository SAP/ui5-webcomponents, pull requests merged in 2020-08, with the labels that each got.

#2046 fix(ui5-tabcontainer): Fix ARIA posinset and setsize values
  packages/main/src/TabContainer.js
  packages/main/test/specs/TabContainer.spec.js
Labels: SuccessFactors

#2047 fix(ui5-tabcontainer): implement acc for overflowed items
  packages/main/src/TabInOverflow.hbs
Labels: SuccessFactors, for review

#2063 feat(tools): ES5 build supports dynamic imports (inlined)
  packages/tools/components-package/rollup.js
Labels: SuccessFactors, for review

#2068 @vladitasev fix(tools): UI5 Web Components are now correctly transpiled
  packages/tools/components-package/rollup.js
Labels: SuccessFactors, for review

#2067 feat(tools): process HBS files in nested directories
  packages/tools/lib/hbs2ui5/index.js
  packages/tools/package.json
  yarn.lock
Labels: SuccessFactors

#2083 feat(framework): Make addCustomCSS dynamic
  packages/base/src/RenderScheduler.js
  packages/base/src/UI5Element.js
  packages/base/src/theming/CustomStyle.js
  packages/base/src/theming/createComponentStyleTag.js
  packages/base/src/theming/getConstructableStyle.js
  packages/base/src/theming/getEffectiveStyle.js
  packages/main/bundle.es5.js
  packages/main/bundle.esm.js
  packages/main/test/pages/CustomCSS.html
Labels: for review

#2120 fix(ui5-input): announce custom valueStateMessage
  packages/main/src/Input.hbs
  packages/main/src/Input.js
Labels: SuccessFactors

#2113 fix(ui5-textarea): add aria-required
  packages/main/src/TextArea.hbs
Labels: SuccessFactors

#2114 fix(ui5-input): implement aria-required
  packages/main/src/Input.hbs
  packages/main/src/Input.js
Labels: SuccessFactors

#2116 feat(ui5-select): introduce required property
  packages/main/src/Select.hbs
  packages/main/src/Select.js
Labels: SuccessFactors

#2117 feat(ui5-datepicker): introduce required property
  packages/main/src/DatePicker.js
Labels: SuccessFactors

#2119 fix(ui5-popup): prevent interaction with the content under the popup
  packages/main/src/Popup.js
  packages/main/src/PopupBlockLayer.hbs
Labels: SuccessFactors

#2118 fix(ui5-toast) avoid overlaying Dialog and Popover
  packages/main/src/Toast.js
  packages/main/src/themes/Toast.css
  packages/main/test/pages/Toast.html
  packages/main/test/specs/Toast.spec.js
Labels: SuccessFactors

#2122 fix(ui5-textarea): announce custom valueStateMessage
  packages/main/src/TextArea.hbs
  packages/main/src/TextArea.js
  packages/main/src/themes/TextArea.css
Labels: SuccessFactors

#2104 fix(ui5-multi-combobox): fix width in IE
  packages/main/src/themes/MultiComboBox.css
Labels: for review

#2123 fix(ui5-popup): restore focus when block layer is clicked
  packages/main/src/Popup.js
  packages/main/src/PopupBlockLayer.hbs
Labels: SuccessFactors

#2103 chore(ui5-dialog): update docs about nesting
  packages/main/src/Dialog.js
Labels: for review

#2124 feat(ui5-textarea): add ariaLabel and ariaLabelledby properties
  packages/main/src/TextArea.hbs
  packages/main/src/TextArea.js
  packages/main/test/pages/TextArea.html
  packages/main/test/specs/TextArea.spec.js
Labels: SuccessFactors

#2125 feat(ui5-select): add ariaLabel and ariaLabelledby properties
  packages/main/src/Select.hbs
  packages/main/src/Select.js
  packages/main/test/pages/Select.html
  packages/main/test/specs/Select.spec.js
Labels: SuccessFactors

#2126 feat(ui5-date-picker): add ariaLabel and ariaLabelledby properties
  packages/main/src/DatePicker.js
  packages/main/src/Input.js
  packages/main/test/pages/DatePicker.html
  packages/main/test/pages/DatePicker_test_page.html
  packages/main/test/specs/DatePicker.spec.js
Labels: SuccessFactors

#2127 feat(ui5-card): add ariaLabel and ariaLabelledby properties
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/test/pages/Card.html
  packages/main/test/specs/Card.spec.js
Labels: CBC

#2129 fix(ui5-popover): fix arrow horizontal position
  packages/main/src/Popover.js
  packages/main/test/pages/Popover.html
Labels: SuccessFactors

#2135 refactor(ui5-title): enable font-size customization
  packages/main/src/themes/Title.css
Labels: SuccessFactors

#2161 chore(ui5-button): propagate more css properties to host element
  packages/main/src/themes/Button.css
Labels: CBC, for review
