Repository SAP/ui5-webcomponents, pull requests merged in 2020-10, with the labels that each got.

#2275 fix(ui5-popup, ui5-dialog): remove instance from openedPopupsRegistry
  packages/main/src/popup-utils/OpenedPopupsRegistry.js
Labels: for review

#2276 fix(ui5-calendar-header): prevent scrolling when month/year picker is selected
  packages/main/src/CalendarHeader.hbs
  packages/main/src/CalendarHeader.js
Labels: for review

#2284 fix(framework): Do not create IE styles with disabled
  packages/base/src/theming/createComponentStyleTag.js
Labels: SuccessFactors, for review

#2290 fix(framework): Allow role as a property name
  packages/base/src/UI5Element.js
  packages/base/src/util/isValidPropertyName.js
Labels: for review

#2303 feat(framework): Add API to subscribe/unsubscribe for theme loaded
  packages/base/src/Theming.js
  packages/base/src/theming/ThemeLoaded.js
  packages/base/src/theming/applyTheme.js
  packages/main/bundle.esm.js
Labels: SuccessFactors, for review

#2309 chore(tools): Upgrade rollup and plugins
  packages/tools/components-package/rollup.js
  packages/tools/package.json
  yarn.lock
Labels: for review

#2305 feat(framework): Support custom dynamic asset paths
  packages/base/src/AssetRegistry.js
  packages/base/src/asset-registries/Icons.js
  packages/base/src/asset-registries/LocaleData.js
  packages/base/src/asset-registries/Themes.js
  packages/base/src/asset-registries/i18n.js
  packages/base/src/util/EffectiveAssetPath.js
  packages/base/src/util/getEffectiveAssetPath.js
Labels: for review

#2316 chore(tools): Upgrade Chromedriver to 86
  yarn.lock
Labels: for review

#2299 feat(ui5-shellbar): implement root part
  packages/fiori/src/ShellBar.hbs
  packages/fiori/test/pages/SideNavigation.html
Labels: Autopilot, for review

#2320 chore: fix memory leak in NativeResize
  packages/base/src/delegate/NativeResize.js
Labels: MDK

#2328 fix: fix JS error on setLanguage call
  packages/base/src/asset-registries/LocaleData.js
  packages/main/test/pages/RTL.html
Labels: MDK

#2272 feat(ui5-checkbox): implement ariaLabelledby property
  packages/main/src/CheckBox.hbs
  packages/main/src/CheckBox.js
Labels: SuccessFactors

#2340 fix(ui5-textarea): fix placeholder font-style
  packages/main/src/themes/TextArea.css
Labels: SuccessFactors

#2350 chore(ui5-date*): enable color and bg-color restyling
  packages/main/src/themes/DatePicker.css
  packages/main/src/themes/DateRangePicker.css
  packages/main/src/themes/DateTimePicker.css
  packages/main/src/themes/DurationPicker.css
  packages/main/src/themes/TimePicker.css
Labels: MDK

#2357 feat(ui5-link): add aria-label and aria-labelledby support
  packages/main/src/Link.hbs
  packages/main/src/Link.js
  packages/main/test/pages/Link.html
  packages/main/test/specs/Link.spec.js
Labels: SF

#2352 fix(ui5-messagestrip): fix close button accessibility
  packages/main/src/MessageStrip.hbs
Labels: for review

#2378 fix(ui5-day-picker): fix color contrast of selected day in HCB
  packages/main/src/themes/DayPicker.css
  packages/main/src/themes/base/DayPicker-parameters.css
  packages/main/src/themes/sap_belize_hcb/DatePicker-parameters.css
  packages/main/src/themes/sap_belize_hcw/DayPicker-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/DayPicker-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/DayPicker-parameters.css
Labels: SF, for review

#2362 fix(ui5-li): fix title update when initially empty
  packages/main/src/StandardListItem.hbs
  packages/main/test/pages/List_test_page.html
  packages/main/test/specs/List.spec.js
Labels: for review

#2402 feat(framework): add override font-family for glyphs with diacritics
  packages/base/src/FontFace.js
  packages/fiori/src/themes/NotificationListGroupItem.css
  packages/fiori/src/themes/NotificationListItem.css
  packages/fiori/src/themes/ProductSwitch.css
  packages/fiori/src/themes/ShellBar.css
  packages/fiori/src/themes/UploadCollection.css
  packages/fiori/src/themes/UploadCollectionItem.css
  packages/main/src/themes/Badge.css
  packages/main/src/themes/Button.css
  packages/main/src/themes/CalendarHeader.css
  packages/main/src/themes/Card.css
  packages/main/src/themes/DayPicker.css
  packages/main/src/themes/Input.css
  packages/main/src/themes/Label.css
  packages/main/src/themes/Link.css
  packages/main/src/themes/List.css
  packages/main/src/themes/ListItemBase.css
  packages/main/src/themes/MessageStrip.css
  packages/main/src/themes/MonthPicker.css
  packages/main/src/themes/Panel.css
  packages/main/src/themes/PopupsCommon.css
  packages/main/src/themes/ProgressIndicator.css
  packages/main/src/themes/ResponsivePopoverCommon.css
  packages/main/src/themes/Switch.css
  packages/main/src/themes/TabContainer.css
  packages/main/src/themes/Table.css
  packages/main/src/themes/TableCell.css
  packages/main/src/themes/TableRow.css
  packages/main/src/themes/TextArea.css
  packages/main/src/themes/TimelineItem.css
  packages/main/src/themes/Title.css
  packages/main/src/themes/Toast.css
  packages/main/src/themes/Token.css
  packages/main/src/themes/Tokenizer.css
  packages/main/src/themes/ValueStateMessage.css
  packages/main/src/themes/WheelSlider.css
  packages/main/src/themes/YearPicker.css
  packages/main/test/pages/72override.html
Labels: SF, for review
