Repository SAP/ui5-webcomponents, pull requests merged in 2020-09, with the labels that each got.

#2157 fix(ui5-daterange-picker): enable selection of single day
  packages/main/src/DateRangePicker.js
  packages/main/test/pages/DateRangePicker.html
  packages/main/test/specs/DateRangePicker.spec.js
Labels: for review

#2164 fix(ui5-table-row): announce entire row and columns
  packages/main/src/Table.js
  packages/main/src/TableRow.hbs
  packages/main/src/TableRow.js
  packages/main/test/specs/Table.spec.js
Labels: CBC

#2158 chore: Update README.md and add Scoping.md
  README.md
  docs/Assets.md
  docs/FAQ.md
  docs/Public Module Imports.md
  docs/Scoping.md
  docs/dev/Development Workflow.md
Labels: for review

#2130 fix(ui5-input): number input doesn't lose value
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: for review

#2180 fix(ui5-daterange-picker): fix js error when removed from the DOM
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/DateRangePicker.js
Labels: for review

#2181 fix(ui5-button): prevent buttons with icon truncate in ie
  packages/main/src/themes/Button.css
Labels: SuccessFactors, for review

#2178 fix(ui5-popover): fix js errors if parent is removed from DOM
  packages/main/src/popup-utils/PopupUtils.js
Labels: for review

#2195 docs: make playground set rtl properly
  packages/playground/assets/js/playground.js
Labels: SuccessFactors, for review

#2196 fix(ui5-li-custom): fix pointer-events inheritance
  packages/main/src/themes/BusyIndicator.css
  packages/main/src/themes/CustomListItem.css
Labels: SuccessFactors, for review

#2203 fix(ui5-daterange-picker): date selection is now correct in all timez…
  packages/main/src/DatePicker.js
  packages/main/src/DateRangePicker.js
Labels: SuccessFactors

#2193 feat(ui5-token): provide closeIcon slot
  packages/main/src/Token.hbs
  packages/main/src/Token.js
  packages/main/src/themes/Token.css
  packages/main/test/pages/MultiInput.html
Labels: SuccessFactors, for review

#2192 feat(ui5-tab-container): implement overflow-button slot
  packages/main/src/Popover.js
  packages/main/src/TabContainer.hbs
  packages/main/src/TabContainer.js
  packages/main/src/themes/TabContainer.css
  packages/main/test/pages/TabContainer.html
Labels: SuccessFactors, for review

#2214 feat(framework): make assets path configurable
  .travis.yml
  README.md
  docs/Configuration.md
  packages/base/src/InitialConfiguration.js
  packages/base/src/asset-registries/Icons.js
  packages/base/src/asset-registries/LocaleData.js
  packages/base/src/asset-registries/Themes.js
  packages/base/src/asset-registries/i18n.js
  packages/base/src/config/AssetsPath.js
  packages/base/src/util/getEffectiveAssetPath.js
  packages/main/bundle.esm.js
  packages/main/test/pages/DatePicker.html
  packages/main/test/pages/Kitchen.html
  packages/tools/components-package/nps.js
  packages/tools/components-package/rollup.js
  packages/tools/package.json
  yarn.lock
Labels: MDK, SuccessFactors, for review

#2227 fix(ui5-flexible-column-layout) fix arrows screen reader suport
  packages/fiori/src/FlexibleColumnLayout.hbs
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/specs/FCL.spec.js
Labels: SuccessFactors

#2204 feat(ui5-select): improve accessibility
  packages/main/src/ListItem.js
  packages/main/src/Select.hbs
  packages/main/src/Select.js
  packages/main/src/SelectPopover.hbs
  packages/main/src/i18n/messagebundle.properties
Labels: SuccessFactors, for review

#2229 fix(ui5-select): make disabled select not focusable
  packages/main/src/Select.js
Labels: SuccessFactors, for review

#2200 feat(ui5-panel): implement headerAriaLabelledBy property
  packages/base/src/util/AriaLabelHelper.js
  packages/base/src/util/getEffectiveAriaLabelText.js
  packages/main/src/Button.js
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/src/ComboBox.js
  packages/main/src/DatePicker.js
  packages/main/src/Input.js
  packages/main/src/List.js
  packages/main/src/Panel.hbs
  packages/main/src/Panel.js
  packages/main/src/Select.js
  packages/main/src/TextArea.js
  packages/main/src/themes/Panel.css
  packages/main/test/pages/Panel.html
  packages/main/test/specs/Card.spec.js
Labels: SuccessFactors, for review

#2230 feat(framework): Limited support for campact size on IE
  packages/base/src/UI5Element.js
  packages/base/src/theming/CSSVarsPonyfill.js
Labels: IE11, SuccessFactors, for review

#2098 fix(ui5-daterange-picker): show value in input only when first & last…
  packages/main/src/DatePicker.js
  packages/main/src/DateRangePicker.js
Labels: for review

#2242 chore(ui5-fcl): add template hooks for toggle arrows
  packages/fiori/src/FlexibleColumnLayout.hbs
Labels: SuccessFactors

#2241 chore(framework): refactor device.js
  packages/base/src/Device.js
Labels: SuccessFactors, for review

#2248 fix(ui5-select): fix text color of disabled select in hcb/hcw
  packages/main/src/themes/Input.css
Labels: SuccessFactors, for review

#2236 feat(ui5-li, ui5-li-tree, ui5-li-custom, ui5-upload-collection-item): implement role property
  packages/main/src/ListItem.js
Labels: SuccessFactors, for review

#2235 feat(ui5-list): introduce role property
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/src/Tree.hbs
Labels: SuccessFactors, for review

#2278 chore: fix imports
  packages/main/src/DayPicker.js
  packages/main/src/TimePicker.js
  packages/main/src/WheelSlider.js
Labels: for review
