Repository SAP/ui5-webcomponents, pull requests merged in 2020-11, with the labels that each got.

#2420 chore(framework): Improve behavior with multiple CSSVarsPonyfills
  packages/base/src/theming/CSSVarsPonyfill.js
Labels: SF, for review

#2400 feat(ui5-wizard): initial implementation
  docs/Public Module Imports.md
  packages/fiori/bundle.esm.js
  packages/fiori/src/Wizard.hbs
  packages/fiori/src/Wizard.js
  packages/fiori/src/WizardStep.js
  packages/fiori/src/WizardTab.hbs
  packages/fiori/src/WizardTab.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/src/themes/Wizard.css
  packages/fiori/src/themes/WizardTab.css
  packages/fiori/src/themes/base/WizardTab-parameters.css
  packages/fiori/src/themes/sap_belize/parameters-bundle.css
  packages/fiori/src/themes/sap_belize_hcb/WizardTab-parameters.css
  packages/fiori/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/fiori/src/themes/sap_belize_hcw/WizardTab-parameters.css
  packages/fiori/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_hcb/WizardTab-parameters.css
  packages/fiori/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_hcw/WizardTab-parameters.css
  packages/fiori/src/themes/sap_fiori_3_hcw/parameters-bundle.css
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/samples/Wizard.sample.html
  packages/fiori/test/specs/Wizard.spec.js
  packages/playground/Gemfile.lock
  packages/playground/build-scripts/samples-prepare.js
Labels: SF, for review

#2311 fix(docs): fix tabcontainer sample for IE
  packages/main/test/samples/TabContainer.sample.html
Labels: SF, for review

#2458 fix(ui5-textarea): set italic to placeholder only
  packages/main/src/themes/TextArea.css
Labels: SF

#2463 fix(ui5-select): remove aria-roledescription
  packages/main/src/Select.hbs
  packages/main/src/Select.js
  packages/main/src/i18n/messagebundle.properties
Labels: ACC, SF

#2493 fix(ui5-badge): enable letter spacing overwrite
  packages/main/src/themes/Badge.css
Labels: SF, for review

#2476 fix(ui5-daterange-picker): fix RenderScheduler import
  packages/main/src/DateRangePicker.js
Labels: RC10 Testing

#2413 feat(ui5-popover): implement hide-block-layer property
  packages/main/src/Dialog.js
  packages/main/src/Popover.js
  packages/main/src/Popup.js
  packages/main/test/pages/Popover.html
  packages/main/test/specs/Popover.spec.js
Labels: SF, for review

#2501 fix(docs): update section info
  packages/playground/_layouts/docs.html
  packages/playground/docs/getting-started-nested.md
  packages/playground/docs/getting-started.md
Labels: for review

#2298 feat(ui5-side-navigation-item, ui5-side-navigation-sub-item): introduce click event
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/SideNavigationItem.js
  packages/fiori/src/SideNavigationSubItem.js
  packages/fiori/test/pages/SideNavigation.html
  packages/fiori/test/specs/SideNavigation.spec.js
Labels: Autopilot, for review

#2511 chore(playground): fix broken link
  packages/playground/docs/getting-started-nested.md
  packages/playground/docs/getting-started.md
Labels: for review

#2512 fix(ui5-input): don't render aria-describedby if not neccessary
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: ACC, SF, for review

#2492 feat(ui5-button): implement title property
  packages/main/src/Button.hbs
  packages/main/src/Button.js
  packages/main/test/pages/Button.html
Labels: ACC, SF, for review

#2520 feat(ui5-side-navigation): add "header" slot
  packages/fiori/src/SideNavigation.hbs
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/themes/SideNavigation.css
  packages/fiori/test/pages/SideNavigation.html
  packages/fiori/test/specs/SideNavigation.spec.js
Labels: MDK, for review

#2483 feat(ui5-flexible-column-layout): add start/mid/endColumnAccessibleName properties
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/test/pages/FCLApp.html
Labels: ACC, SF, for review
