Repository SAP/ui5-webcomponents, pull requests merged in 2020-06, with the labels that each got.

#1692 refactor(components): rename event names to kebab case
  docs/Configuration.md
  packages/base/src/UI5Element.js
  packages/base/test/pages/ConfigurationScript.html
  packages/base/test/specs/ConfigurationChange.spec.js
  packages/base/test/specs/ConfigurationScript.spec.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/ShellBarItem.js
  packages/fiori/src/ShellBarPopover.hbs
  packages/fiori/src/UploadCollection.hbs
  packages/fiori/src/UploadCollection.js
  packages/fiori/src/UploadCollectionItem.js
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
  packages/fiori/test/samples/ProductSwitch.sample.html
  packages/fiori/test/samples/ShellBar.sample.html
  packages/main/src/Calendar.hbs
  packages/main/src/Calendar.js
  packages/main/src/CalendarHeader.js
  packages/main/src/Card.js
  packages/main/src/Carousel.js
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/DateTimePickerPopover.hbs
  packages/main/src/DayPicker.js
  packages/main/src/Dialog.js
  packages/main/src/DurationPickerPopover.hbs
  packages/main/src/Icon.js
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/src/List.js
  packages/main/src/ListItem.js
  packages/main/src/ListItemBase.js
  packages/main/src/MonthPicker.js
  packages/main/src/MultiComboBox.hbs
  packages/main/src/MultiComboBox.js
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/Popover.js
  packages/main/src/Popup.js
  packages/main/src/ResponsivePopover.hbs
  packages/main/src/SegmentedButton.js
  packages/main/src/SelectPopover.hbs
  packages/main/src/TabContainer.js
  packages/main/src/TabContainerPopover.hbs
  packages/main/src/Table.js
  packages/main/src/TableRow.js
  packages/main/src/TimePickerPopover.hbs
  packages/main/src/TimelineItem.js
  packages/main/src/Tokenizer.js
  packages/main/src/Tree.hbs
  packages/main/src/Tree.js
  packages/main/src/TreeListItem.js
  packages/main/src/WheelSlider.js
  packages/main/src/YearPicker.js
  packages/main/src/features/InputSuggestions.js
  packages/main/src/types/ListItemType.js
  packages/main/test/samples/List.sample.html
  packages/main/test/samples/Tree.sample.html
Labels: for review

#1708 chore: fix button slot display
  packages/main/src/Button.js
  packages/main/test/pages/Button.html
  packages/main/test/specs/Button.spec.js
Labels: for review

#1715 fix(ui5-file-uploader): setting the value to an empty string also res…
  packages/fiori/test/pages/uploadCollectionScript.js
  packages/main/src/FileUploader.js
Labels: MDK, for review

#1716 fix(framework): Allow users to override default language translations
  packages/base/src/asset-registries/i18n.js
  packages/tools/lib/generate-json-imports/i18n.js
Labels: SuccessFactors, for review

#1724 fix(ui5-select): fix use of ESC leads to wrong selection
  packages/main/src/Select.js
  packages/main/test/pages/Select.html
  packages/main/test/specs/Select.spec.js
Labels: for review

#1691 feat(framework): support several runtimes simultaneously
  packages/base/src/CustomElementsRegistry.js
  packages/base/src/UI5Element.js
  packages/base/src/delegate/ItemNavigation.js
  packages/base/src/delegate/ResizeHandler.js
  packages/base/src/util/FocusableElements.js
Labels: for review

#1726 ui5-table: design implemented for popped-in columns
  packages/main/src/TableRow.hbs
  packages/main/src/TableRow.js
  packages/main/src/themes/TableRow.css
  packages/main/test/pages/TableAllPopin.html
Labels: MDK, for review

#1733 feature(framework): Deprecate the RTL configuration setting
  docs/Configuration.md
  docs/Public Module Imports.md
  packages/base/src/SystemCSSVars.js
  packages/base/src/UI5Element.js
  packages/base/src/boot.js
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/NotificationListItemBase.js
  packages/fiori/src/ShellBar.hbs
  packages/fiori/src/ShellBar.js
  packages/main/src/Badge.hbs
  packages/main/src/Badge.js
  packages/main/src/Button.hbs
  packages/main/src/Button.js
  packages/main/src/CalendarHeader.hbs
  packages/main/src/CalendarHeader.js
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/src/CheckBox.hbs
  packages/main/src/CheckBox.js
  packages/main/src/ComboBox.hbs
  packages/main/src/DatePicker.hbs
  packages/main/src/DatePicker.js
  packages/main/src/Icon.hbs
  packages/main/src/Icon.js
  packages/main/src/Label.hbs
  packages/main/src/Label.js
  packages/main/src/ListItem.hbs
  packages/main/src/ListItemBase.js
  packages/main/src/MultiComboBox.hbs
  packages/main/src/MultiComboBox.js
  packages/main/src/RadioButton.hbs
  packages/main/src/RadioButton.js
  packages/main/src/Select.hbs
  packages/main/src/Select.js
  packages/main/src/Switch.hbs
  packages/main/src/Switch.js
  packages/main/src/TabContainer.hbs
  packages/main/src/TabContainer.js
  packages/main/src/TimelineItem.hbs
  packages/main/src/TimelineItem.js
  packages/main/src/Toast.hbs
  packages/main/src/Toast.js
  packages/main/src/Token.hbs
  packages/main/src/Token.js
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/test/pages/RTL.html
  packages/main/test/specs/RTL.spec.js
Labels: for review

#1734 fix(ui5-segmentedbutton): add RTL support
  packages/main/src/SegmentedButton.hbs
  packages/main/src/themes/SegmentedButton.css
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/test/pages/SegmentedButton.html
Labels: MDK

#1728 feat(framework): Support properties message bundles for i18n
  docs/Public Module Imports.md
  packages/base/src/asset-registries/i18n.js
  packages/base/src/features/PropertiesFormatSupport.js
  packages/base/src/util/parseProperties.js
  packages/main/bundle.esm.js
  packages/main/test/pages/lang/fr.json
  packages/main/test/pages/lang/messagebundle_bg.properties
Labels: SuccessFactors, for review

#1727 feature(theme-base): Generate a report for used CSS vars upon build
  packages/theme-base/css-vars-usage.json
  packages/theme-base/lib/generate-css-vars-usage-report/index.js
  packages/theme-base/package-scripts.js
  packages/theme-base/package.json
Labels: SuccessFactors, for review

#1729 feat(ui5-rating-indicator): initial implementation
  packages/base/src/UI5Element.js
  packages/base/src/types/Float.js
  packages/main/bundle.esm.js
  packages/main/src/RatingIndicator.hbs
  packages/main/src/RatingIndicator.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/RatingIndicator.css
  packages/main/test/pages/RatingIndicator.html
  packages/main/test/samples/RatingIndicator.sample.html
  packages/main/test/specs/RatingIndicator.spec.js
  packages/playground/Gemfile.lock
  packages/playground/build-scripts/samples-prepare.js
  packages/theme-base/css-vars-usage.json
Labels: SuccessFactors, for review

#1752 fix(ui5-timepicker): adjust hours in 12hours format only
  packages/main/src/TimePicker.js
  packages/main/test/pages/TimePicker.html
Labels: for review

#1751 chore(RatingIndicator): fix few comments from review
  packages/main/src/RatingIndicator.js
  packages/main/test/samples/RatingIndicator.sample.html
Labels: for review

#1764 fix(ui5-timepicker): fix firing "change" event for the same value
  packages/main/src/TimePicker.js
  packages/main/test/pages/TimePicker.html
  packages/main/test/specs/TimePicker.spec.js
Labels: MDK

#1676 fix(ui5-popover): fix closing order of popovers
  packages/main/src/Popover.js
  packages/main/src/popup-utils/OpenedPopupsRegistry.js
  packages/main/src/popup-utils/PopoverRegistry.js
  packages/main/test/pages/Popover.html
Labels: for review

#1770 fix(ui5-upload-collection): Provide min-height also when DND mode is on
  packages/fiori/src/UploadCollection.js
Labels: MDK, for review

#1746 feat(framework): Add dynamic language change and on-demand rerendering
  docs/Configuration.md
  packages/base/src/CustomElementsRegistry.js
  packages/base/src/EventProvider.js
  packages/base/src/RenderScheduler.js
  packages/base/src/UI5Element.js
  packages/base/src/UI5ElementMetadata.js
  packages/base/src/asset-registries/i18n.js
  packages/base/src/config/Language.js
  packages/base/src/locale/RTLAwareRegistry.js
  packages/base/src/locale/applyDirection.js
  packages/base/src/locale/languageChange.js
  packages/base/src/util/setToArray.js
  packages/fiori/src/NotificationListGroupItem.js
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/ShellBar.js
  packages/main/bundle.es5.js
  packages/main/bundle.esm.js
  packages/main/src/Badge.js
  packages/main/src/Button.js
  packages/main/src/CalendarHeader.js
  packages/main/src/Card.js
  packages/main/src/CheckBox.js
  packages/main/src/ComboBox.js
  packages/main/src/DatePicker.js
  packages/main/src/Icon.js
  packages/main/src/Label.js
  packages/main/src/ListItem.js
  packages/main/src/MessageStrip.js
  packages/main/src/MultiComboBox.js
  packages/main/src/RadioButton.js
  packages/main/src/SegmentedButton.js
  packages/main/src/Select.js
  packages/main/src/Switch.js
  packages/main/src/TabContainer.js
  packages/main/src/TimelineItem.js
  packages/main/src/Toast.js
  packages/main/src/Token.js
  packages/main/test/pages/RTL.html
Labels: for review

#1773 fix: the styles getter always expects an array of strings
  packages/fiori/src/UploadCollectionItem.js
  packages/main/src/CustomListItem.js
  packages/main/src/TreeListItem.js
Labels: High Prio, SuccessFactors

#1702 feat(ui5-upload-collection-item): implement keyboard handling
  packages/fiori/src/UploadCollectionItem.hbs
  packages/fiori/src/UploadCollectionItem.js
  packages/fiori/test/pages/UploadCollection.html
  packages/fiori/test/specs/UploadCollection.spec.js
  packages/main/src/List.js
Labels: for review

#1777 fix(icons): overflow icon is now centered
  packages/icons/src/icon-collections/SAP-icons.json
  packages/main/test/pages/Icon.html
Labels: SuccessFactors, for review

#1779 fix(ui5-busy-indicator): fix double focus issue
  packages/main/src/BusyIndicator.js
Labels: SuccessFactors, for review

#1783 fix(tools): Polyfill copied correctly in all scenarios
  packages/tools/components-package/nps.js
Labels: SuccessFactors, for review

#1781 fix(ui5-button): apply aria-expanded to inner button tag
  packages/base/src/util/isValidPropertyName.js
  packages/main/src/Button.hbs
  packages/main/src/Button.js
  packages/main/test/pages/Button.html
  packages/main/test/specs/Button.spec.js
Labels: SuccessFactors, for review

#1782 feat(ui5-input): implement aria-label
  packages/main/src/Input.hbs
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SuccessFactors, for review

#1786 fix(ui5-avatar): Correct colors are applied for acc themes
  packages/main/src/themes/Avatar.css
  packages/main/src/themes/base/Avatar-parameters.css
  packages/main/src/themes/sap_belize/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcb/Avatar-parameters.css
  packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcw/Avatar-parameters.css
  packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
Labels: for review

#1793 fix(ui5-panel): The expand/collapse button is not in the DOM when fixed
  packages/main/src/Panel.hbs
  packages/main/src/themes/Panel.css
Labels: SuccessFactors

#1771 fix(ui5-select): improve keyboard handling
  packages/main/src/Select.js
  packages/main/test/pages/Select.html
  packages/main/test/specs/Select.spec.js
Labels: for review

#1798 refactor: document Popup.js and improve consistency
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
  packages/main/src/themes/MultiComboBox.css
  packages/main/src/themes/Popover.css
  packages/main/src/themes/Popup.css
  packages/main/src/themes/ResponsivePopover.css
  packages/main/src/themes/base/Popover-parameters.css
  packages/main/src/themes/base/Popup-parameters.css
  packages/main/src/themes/sap_belize/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
Labels: SuccessFactors, for review

#1800 fix(ui5-link): fix "click twice" issue in Safari (#1799)
  packages/main/src/themes/Link.css
  packages/main/src/themes/base/Link-parameters.css
  packages/main/src/themes/sap_belize_hcb/Link-parameters.css
  packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcw/Link-parameters.css
  packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
Labels: SuccessFactors

#1816 docs: how to create a Fiori 3 message page
  packages/main/test/pages/MessagePage.html
Labels: SuccessFactors

#1811 fix(ui5-input): fix JS errors when open/close popups
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
Labels: SuccessFactors

#1817 fix(ui5-tabcontainer): aria-controls now points to an existing ID
  packages/main/src/TabContainer.hbs
Labels: SuccessFactors

#1826 chore: fix NotificationList tests
  packages/fiori/test/specs/NotificationList.spec.js
Labels: for review

#1828 fix(ui5-avatar): image URL may now contain special characters
  packages/main/src/Avatar.hbs
  packages/main/src/Avatar.js
  packages/main/test/pages/Avatar.html
  packages/main/test/pages/img/John$$$ ' (_)Miller#1.png
Labels: for review

#1829 fix(ui5-tabcontainer): fix box-shadow
  packages/main/src/themes/TabContainer.css
Labels: SuccessFactors, for review

#1830 fix(ui5-dialog): fix behaviour on mobile when added to DOM on interaction
  packages/main/src/Dialog.js
Labels: for review

#1842 feat(ui5-shellbar): add "logo" slot
  packages/fiori/src/ShellBar.hbs
  packages/fiori/src/ShellBar.js
  packages/fiori/src/themes/ShellBar.css
  packages/fiori/test/pages/ShellBar.html
  packages/fiori/test/samples/ShellBar.sample.html
  packages/playground/_sass/base.scss
Labels: SuccessFactors, for review

#1844 feat(ui5-popup): custom popups work with focusable elements in the sh…
  packages/base/src/util/FocusableElements.js
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
  packages/main/test/pages/Dialog.html
Labels: SuccessFactors

#1832 refactor(framework): make _id only generated on demand
  packages/base/src/UI5Element.js
  packages/main/src/Tree.hbs
  packages/main/src/Tree.js
  packages/main/test/pages/LitKeyFunction.html
  packages/main/test/specs/LitKeyFunction.spec.js
Labels: for review

#1848 fix(ui5-input): fix scrolling item into view
  packages/main/src/features/InputSuggestions.js
Labels: SuccessFactors

#1833 feat(framework): make icons RTL aware
  packages/base/src/SVGIconRegistry.js
  packages/base/src/asset-registries/Icons.js
  packages/icons/src/icon-collections/SAP-icons.json
  packages/main/src/CheckBox.hbs
  packages/main/src/Icon.hbs
  packages/main/src/Icon.js
  packages/main/test/pages/Icon.html
  packages/tools/lib/create-icons/index.js
Labels: MDK, for review

#1850 refactor(ui5-avatar): fix for the fix for special characters in image…
  packages/main/src/Avatar.js
  packages/main/test/pages/Avatar.html
  packages/main/test/pages/img/John$$$ ' (_)Miller#1 100% &=.png
Labels: for review

#1853 refactor(ui5-popup): Move more common functionality to Popup.js
  packages/main/bundle.esm.js
  packages/main/src/Dialog.hbs
  packages/main/src/Dialog.js
  packages/main/src/Popover.hbs
  packages/main/src/Popover.js
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
  packages/main/src/themes/Popup.css
  packages/main/src/themes/PopupsCommon.css
  packages/main/src/themes/base/PopupsCommon-parameters.css
  packages/main/src/themes/sap_belize/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
Labels: SuccessFactors, for review

#1855 fix(tools): strip unnecessary whitespaces
  packages/tools/lib/hbs2lit/src/compiler.js
Labels: SuccessFactors, for review

#1857 fix(ui5-input): stop firing focusout on suggestion click
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
Labels: SuccessFactors

#1856 feat(ui5-input): add suggestion-scroll event
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SuccessFactors

#1860 feat(tools): Templates can be imported from node_modules/
  packages/fiori/.npmignore
  packages/main/.npmignore
  packages/tools/lib/hbs2lit/index.js
  packages/tools/lib/hbs2lit/src/compiler.js
  packages/tools/lib/hbs2lit/src/includesReplacer.js
  packages/tools/lib/hbs2ui5/index.js
Labels: SuccessFactors, for review

#1863 feat(ui5-shellbar): enable tooltips of custom icons
  packages/fiori/src/ShellBar.hbs
  packages/fiori/src/ShellBar.js
  packages/fiori/src/themes/ShellBar.css
  packages/fiori/test/pages/ShellBar.html
Labels: for review

#1864 chore(ui5-dialog): allow content max-width 100%
  packages/main/src/themes/Dialog.css
  packages/main/test/pages/Dialog.html
Labels: SuccessFactors, for review

#1873 feat(ui5-input): Support ariaLabelledBy
  packages/base/src/util/getEffectiveAriaLabelText.js
  packages/main/src/Button.js
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
Labels: for review

#1874 fix(ui5-sebmentedbutton): fix intermittent js error
  packages/main/src/SegmentedButton.js
Labels: MDK, for review

#1877 chore(ui5-tree): extract tree list item partial
  packages/main/src/Tree.hbs
Labels: SuccessFactors, for review

#1875 chore: create a test page for ResizeHandler
  packages/main/bundle.es5.js
  packages/main/bundle.esm.js
  packages/main/test/pages/ResizeHandler.html
Labels: MDK, for review

#1867 feat(ui5-flexible-column-layout): new component
  packages/fiori/bundle.esm.js
  packages/fiori/src/FlexibleColumnLayout.hbs
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/src/fcl-utils/FCLLayout.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/src/themes/FlexibleColumnLayout.css
  packages/fiori/src/themes/base/FlexibleColumnLayout-parameters.css
  packages/fiori/src/themes/sap_belize/parameters-bundle.css
  packages/fiori/src/themes/sap_belize_hcb/FlexibleColumnLayout-parameters.css
  packages/fiori/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/fiori/src/themes/sap_belize_hcw/FlexibleColumnLayout-parameters.css
  packages/fiori/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_dark/FlexibleColumnLayout-parameters.css
  packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/fiori/src/types/FCLLayout.js
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/FCLApp.html
  packages/fiori/test/samples/FlexibleColumnLayout.sample.html
  packages/fiori/test/specs/FCL.spec.js
  packages/playground/build-scripts/samples-prepare.js
  packages/theme-base/css-vars-usage.json
Labels: SuccessFactors

#1869 feat(framework): Create a global shared resources repo, share SVG Icons
  packages/base/src/SVGIconRegistry.js
  packages/base/src/StaticArea.js
  packages/base/src/getSharedResource.js
  packages/base/src/util/getSingletonElementInstance.js
Labels: SuccessFactors, for review

#1885 chore(ui5-dialog): Show how to build a semantic dialog
  packages/main/test/pages/DialogSemantic.html
Labels: SuccessFactors, for review
