Repository SAP/ui5-webcomponents, pull requests merged in 2021-08, with the labels that each got.

#3520 feat(ui5-timeline): enable horizontal layout
  packages/fiori/src/Timeline.hbs
  packages/fiori/src/Timeline.js
  packages/fiori/src/TimelineItem.hbs
  packages/fiori/src/TimelineItem.js
  packages/fiori/src/themes/Timeline.css
  packages/fiori/src/themes/TimelineItem.css
  packages/fiori/src/types/TimelineLayout.js
  packages/fiori/test/pages/Timeline.html
  packages/fiori/test/samples/Timeline.sample.html
Labels: SF

#3568 fix(ui5-table-cell): allow selection of text nodes
  packages/main/src/themes/TableCell.css
Labels: RBSC

#3523 feat(ui5-barcode-scanner-dialog): Initial implementation
  packages/fiori/bundle.common.js
  packages/fiori/package.json
  packages/fiori/src/BarcodeScannerDialog.hbs
  packages/fiori/src/BarcodeScannerDialog.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/src/themes/BarcodeScannerDialog.css
  packages/fiori/test/pages/BarcodeScannerDialog.html
  packages/fiori/test/samples/BarcodeScannerDialog.sample.html
  packages/fiori/test/specs/BarcodeScannerDialog.spec.js
  packages/tools/components-package/rollup.js
Labels: New Component

#3532 fix(ui5-dialog): fix text selection on chrome
  packages/base/src/Device.js
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
Labels: RBSC, SF

#3586 fix(ui5-li-notification, ui5-li-notification-group): rename heading property to titleText
  packages/base/hash.txt
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListGroupItem.js
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/NotificationListItemBase.js
  packages/fiori/src/themes/NotificationListGroupItem.css
  packages/fiori/src/themes/NotificationListItem.css
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/pages/NotificationList_test_page.html
  packages/fiori/test/pages/ProductSwitchItem.html
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
  packages/fiori/test/specs/NotificationList.spec.js
Labels: BREAKING CHANGE, for review

#3489 feat(ui5-breadcrumbs): Initial implementation
  packages/main/bundle.common.js
  packages/main/src/Breadcrumbs.hbs
  packages/main/src/Breadcrumbs.js
  packages/main/src/BreadcrumbsItem.js
  packages/main/src/BreadcrumbsPopover.hbs
  packages/main/src/Interfaces.js
  packages/main/src/Link.hbs
  packages/main/src/Link.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/Breadcrumbs.css
  packages/main/src/themes/BreadcrumbsPopover.css
  packages/main/src/themes/Link.css
  packages/main/src/types/BreadcrumbsDesign.js
  packages/main/src/types/BreadcrumbsSeparatorStyle.js
  packages/main/test/pages/Breadcrumbs.html
  packages/main/test/samples/Breadcrumbs.sample.html
  packages/main/test/specs/Breadcrumbs.spec.js
Labels: New Component

#3502 feat(ui5-view-settings-dialog): implement ViewSettingsDialog component
  docs/Public Module Imports.md
  packages/fiori/bundle.common.js
  packages/fiori/src/ViewSettingsDialog.hbs
  packages/fiori/src/ViewSettingsDialog.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/src/themes/ViewSettingsDialog.css
  packages/fiori/test/pages/ViewSettingsDialog.html
  packages/fiori/test/samples/ViewSettingsDialog.sample.html
  packages/fiori/test/specs/ViewSettingsDialog.spec.js
  packages/playground/build-scripts/samples-prepare.js
Labels: New Component, SF

#3610 fix(ui5-li-groupheader): fix row height
  packages/main/src/themes/GroupHeaderListItem.css
Labels: SF

#3595 feat(ui5-responsive-popover): add prevent initial focus parameter to showAt method
  packages/main/src/ResponsivePopover.js
  packages/main/test/pages/ResponsivePopover.html
  packages/main/test/specs/ResponsivePopover.spec.js
Labels: SF

#3609 feat(ui5-date-picker): preventable change and input events
  packages/main/src/DatePicker.js
  packages/main/test/pages/DatePicker.html
  packages/main/test/pages/DatePicker_test_page.html
  packages/main/test/specs/DatePicker.spec.js
Labels: SF

#3633 feat(ui5-illustrated-message): introduce subtitle slot
  packages/fiori/src/IllustratedMessage.hbs
  packages/fiori/src/IllustratedMessage.js
  packages/fiori/test/pages/IllustratedMessage.html
  packages/fiori/test/samples/IllustratedMessage.sample.html
Labels: SAP Graph

#3604 refactor(framework): UI5Element - improvements and fixes
  packages/base/hash.txt
  packages/base/src/UI5Element.js
  packages/base/src/types/DataType.js
  packages/base/src/types/Float.js
  packages/base/src/types/Integer.js
  packages/main/test/pages/Simple.html
Labels: for review

#3676 fix: update readme build steps
  README.md
Labels: for review

#3694 feat(ui5-panel): noAnimation property introduced
  packages/main/src/Panel.js
  packages/main/test/pages/Panel.html
  packages/main/test/specs/Panel.spec.js
Labels: SF

#3629 fix(ui5-date-picker): setting value before firing event
  packages/main/src/DatePicker.js
  packages/main/test/pages/DatePicker.html
  packages/main/test/pages/DatePicker_test_page.html
Labels: SF

#3677 fix(ui5-daypicker): fix js error
  packages/main/src/DayPicker.js
Labels: SF, Blocked

#3657 fix(framework): apply RTL for components with popovers
  packages/base/bundle.esm.js
  packages/base/hash.txt
  packages/base/src/StaticAreaItem.js
  packages/base/test/elements/WithStaticArea.js
  packages/base/test/pages/AllTestElements.html
  packages/base/test/specs/StaticArea.spec.js
Labels: for review

#3725 fix(framework): Multiple properties have no attribute
  packages/base/hash.txt
  packages/base/src/UI5ElementMetadata.js
  packages/main/src/DayPicker.js
  packages/main/src/MultiInput.js
Labels: for review

#3634 feat(ui5-calendar): support secondary calendar type
  packages/main/src/Calendar.hbs
  packages/main/src/CalendarHeader.hbs
  packages/main/src/CalendarHeader.js
  packages/main/src/DateComponentBase.js
  packages/main/src/DayPicker.hbs
  packages/main/src/DayPicker.js
  packages/main/src/themes/CalendarHeader.css
  packages/main/src/themes/DayPicker.css
  packages/main/src/themes/base/DayPicker-parameters.css
  packages/main/src/themes/sap_fiori_3/DayPicker-parameters.css
  packages/main/src/themes/sap_fiori_3_dark/DayPicker-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/DayPicker-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/DayPicker-parameters.css
  packages/main/test/pages/Calendar.html
  packages/main/test/specs/Calendar.spec.js
Labels: SF
