Repository SAP/ui5-webcomponents, pull requests merged in 2021-07, with the labels that each got.

#3469 feat(ui5-combobox): add suggestions grouping
  packages/main/src/ComboBox.js
  packages/main/src/ComboBoxGroupItem.js
  packages/main/src/ComboBoxPopover.hbs
  packages/main/test/pages/ComboBox.html
  packages/main/test/samples/ComboBox.sample.html
  packages/main/test/specs/ComboBox.spec.js
Labels: SF

#3431 fix(ui5-popup) page scrolling up if more than one dialog is open
  packages/main/src/Popup.js
  packages/main/test/specs/Dialog.spec.js
Labels: SF

#3477 refactor(ui5-list): introduce accessibleRole prop
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/specs/NotificationList.spec.js
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/src/Tree.hbs
Labels: ACC

#3237 feat(ui5-avatar): implement default slot
  packages/main/src/Avatar.hbs
  packages/main/src/Avatar.js
  packages/main/src/themes/Avatar.css
  packages/main/src/types/AvatarFitType.js
  packages/main/test/pages/Avatar.html
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/samples/Avatar.sample.html
  packages/main/test/samples/AvatarGroup.sample.html
  packages/main/test/specs/Avatar.spec.js
  packages/playground/_sass/base.scss
Labels: BREAKING_CHANGE

#3506 fix(ui5-popup): adjust default header height
  packages/main/src/themes/PopupsCommon.css
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/test/pages/Dialog.html
  packages/theme-base/hash.txt
Labels: SF

#3508 fix(ui5-responsive-popover): fixed position of downward pointing arrow
  packages/main/src/themes/Popover.css
  packages/main/test/pages/ResponsivePopover.html
Labels: SF

#3513 fix(ui5-shellbar): Fix unnecessary cutting space on left side
  packages/fiori/src/themes/ShellBar.css
Labels: SF

#3449 feat: rename aria-label to accessible-name
  packages/base/hash.txt
  packages/base/src/util/AriaLabelHelper.js
  packages/fiori/src/Timeline.hbs
  packages/fiori/src/Wizard.js
  packages/fiori/src/WizardStep.js
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/samples/Bar2.sample.html
  packages/fiori/test/samples/FlexibleColumnLayout.sample.html
  packages/main/src/Button.js
  packages/main/src/Card.js
  packages/main/src/CheckBox.js
  packages/main/src/ComboBox.js
  packages/main/src/DatePicker.js
  packages/main/src/Dialog.js
  packages/main/src/Input.js
  packages/main/src/Link.js
  packages/main/src/List.js
  packages/main/src/Panel.hbs
  packages/main/src/Panel.js
  packages/main/src/Popover.js
  packages/main/src/Popup.js
  packages/main/src/RatingIndicator.hbs
  packages/main/src/RatingIndicator.js
  packages/main/src/Select.js
  packages/main/src/StepInput.js
  packages/main/src/TextArea.js
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/pages/Button.html
  packages/main/test/pages/Card.html
  packages/main/test/pages/CheckBox.html
  packages/main/test/pages/ComboBox.html
  packages/main/test/pages/DatePicker.html
  packages/main/test/pages/DatePicker_test_page.html
  packages/main/test/pages/Input.html
  packages/main/test/pages/Link.html
  packages/main/test/pages/Popover.html
  packages/main/test/pages/RatingIndicator.html
  packages/main/test/pages/Select.html
  packages/main/test/pages/TabContainer.html
  packages/main/test/pages/TextArea.html
  packages/main/test/specs/Dialog.spec.js
  packages/main/test/specs/Input.spec.js
  packages/main/test/specs/Popover.spec.js
  packages/main/test/specs/StepInput.spec.js
Labels: ACC, BREAKING_CHANGE

#3530 refactor(ui5-duration-picker): make component private
  docs/Public Module Imports.md
  packages/main/src/DurationPicker.js
  packages/main/test/samples/DurationPicker.sample.html
Labels: BREAKING CHANGE

#3528 refactor(ui5-dialog): rename "open()" to "show()"
  docs/How To Use.md
  packages/fiori/test/pages/IllustratedMessage.html
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/samples/IllustratedMessage.sample.html
  packages/fiori/test/specs/UploadCollection.spec.js
  packages/main/src/ColorPalette.js
  packages/main/src/Dialog.js
  packages/main/src/Popover.js
  packages/main/src/Popup.js
  packages/main/src/ResponsivePopover.js
  packages/main/test/pages/BusyIndicator.html
  packages/main/test/pages/Dialog.html
  packages/main/test/pages/DialogLifecycle.html
  packages/main/test/pages/DialogSemantic.html
  packages/main/test/pages/Input.html
  packages/main/test/pages/MultiInput.html
  packages/main/test/pages/MultiInput_Suggestions.html
  packages/main/test/pages/ResponsivePopover.html
  packages/main/test/pages/Toast.html
  packages/main/test/pages/kitchen-scripts.js
  packages/main/test/pages/modules/Popups.js
  packages/main/test/samples/Dialog.sample.html
  packages/main/test/specs/ComboBox.spec.js
  packages/main/test/specs/List.spec.js
  packages/playground/assets/js/playground.js
Labels: BREAKING CHANGE

#3525 feat(framework): Expose HTML sanitization utilities
  packages/base/.eslintignore
  packages/base/.npmignore
  packages/base/hash.txt
  packages/base/package-scripts.js
  packages/base/package.json
  packages/base/src/util/HTMLSanitizer.js
  packages/base/used-modules.txt
  packages/localization/package-scripts.js
  packages/main/bundle.common.js
  packages/theme-base/css-vars-usage.json
  packages/tools/lib/copy-list/index.js
  packages/tools/lib/esm-abs-to-rel/index.js
  packages/tools/lib/replace-global-core/index.js
  yarn.lock
Labels: SAP Marketing Area

#3490 refactor(ui5-card): header slot is added
  docs/Public Module Imports.md
  packages/fiori/test/pages/Timeline.html
  packages/main/bundle.common.js
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/src/CardHeader.hbs
  packages/main/src/CardHeader.js
  packages/main/src/themes/Card.css
  packages/main/src/themes/CardHeader.css
  packages/main/test/pages/Card.html
  packages/main/test/pages/Carousel.html
  packages/main/test/pages/Components.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/samples/Card.sample.html
  packages/main/test/specs/Card.spec.js
Labels: BREAKING CHANGE

#3529 feat(ui5-badge): update design
  packages/main/src/Badge.hbs
  packages/main/src/Badge.js
  packages/main/src/themes/Badge.css
  packages/main/src/themes/base/Badge-parameters.css
  packages/main/src/themes/sap_belize_hcb/Badge-parameters.css
  packages/main/src/themes/sap_belize_hcw/Badge-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/Badge-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/Badge-parameters.css
  packages/main/test/pages/Badge.html
  packages/theme-base/css-vars-usage.json
Labels: SF

#3540 refactor(ui5-popover, ui5-responsive-popover): rename "openBy" to "showAt"
  packages/base/src/util/PopupUtils.js
  packages/fiori/src/NotificationListItemBase.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/Wizard.js
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/pages/ShellBar.html
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
  packages/fiori/test/samples/ProductSwitch.sample.html
  packages/fiori/test/samples/ShellBar.sample.html
  packages/main/src/ComboBox.js
  packages/main/src/DatePicker.js
  packages/main/src/FileUploader.js
  packages/main/src/Input.js
  packages/main/src/MultiComboBox.js
  packages/main/src/Popover.js
  packages/main/src/ResponsivePopover.js
  packages/main/src/Select.js
  packages/main/src/TabContainer.js
  packages/main/src/TextArea.js
  packages/main/src/TimePickerBase.js
  packages/main/src/Tokenizer.js
  packages/main/src/features/InputSuggestions.js
  packages/main/src/popup-utils/PopoverRegistry.js
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/pages/ColorPalette.html
  packages/main/test/pages/Dialog.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/pages/Popover.html
  packages/main/test/pages/ResponsivePopover.html
  packages/main/test/pages/kitchen-scripts.js
  packages/main/test/pages/modules/Popups.js
  packages/main/test/samples/AvatarGroup.sample.html
  packages/main/test/samples/Popover.sample.html
  packages/main/test/samples/ResponsivePopover.sample.html
Labels: BREAKING CHANGE

#3514 fix(ui5-input): fire change on the initial tab press after suggestion is selected
  packages/main/src/Input.js
  packages/main/src/features/InputSuggestions.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SF

#3565 fix(ui5-li-notification): rename wrap property to wrappingType
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/themes/NotificationListItem.css
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/pages/NotificationList_test_page.html
Labels: BREAKING CHANGE

#3562 refactor(ui5-card-header): rename "headerInteractive" to "interactive"
  packages/main/src/CardHeader.js
  packages/main/test/pages/Card.html
  packages/main/test/pages/Carousel.html
  packages/main/test/samples/Card.sample.html
  packages/main/test/samples/Carousel.sample.html
Labels: BREAKING CHANGE

#3442 feat: implement assessibleNameRef for many components
  packages/base/hash.txt
  packages/base/src/util/AriaLabelHelper.js
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/WizardStep.js
  packages/main/src/Button.hbs
  packages/main/src/Button.js
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/src/CardHeader.js
  packages/main/src/CheckBox.hbs
  packages/main/src/CheckBox.js
  packages/main/src/ComboBox.js
  packages/main/src/DatePicker.js
  packages/main/src/Input.js
  packages/main/src/Link.js
  packages/main/src/List.js
  packages/main/src/Select.js
  packages/main/src/StepInput.js
  packages/main/src/TextArea.js
  packages/main/test/pages/Button.html
  packages/main/test/pages/Card.html
  packages/main/test/pages/ComboBox.html
  packages/main/test/pages/DatePicker.html
  packages/main/test/pages/DatePicker_test_page.html
  packages/main/test/pages/Input.html
  packages/main/test/pages/Link.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/pages/Select.html
  packages/main/test/pages/TextArea.html
  packages/main/test/samples/Button.sample.html
  packages/main/test/samples/Label.sample.html
  packages/main/test/specs/Card.spec.js
  packages/main/test/specs/CheckBox.spec.js
  packages/main/test/specs/Link.spec.js
  packages/main/test/specs/MultiComboBox.spec.js
Labels: ACC, BREAKING CHANGE
