Repository SAP/ui5-webcomponents, pull requests merged in 2021-09, with the labels that each got.

#3803 chore: add interfaces JSDoc
  packages/main/src/ComboBoxGroupItem.js
  packages/main/src/Interfaces.js
  packages/main/src/SegmentedButton.js
  packages/main/src/SegmentedButtonItem.js
  packages/main/src/TableGroupRow.js
Labels: for review

#3819 refactor(framework): EventProvider.js reworked
  packages/base/src/EventProvider.js
Labels: for review

#3742 fix (ui5-avatar, ui5-icon): attach onclick handler based on interactive property
  packages/main/src/Avatar.js
  packages/main/src/Icon.js
Labels: SF

#3873 fix(ui5-color-palette-popover): fix event params
  packages/base/hash.txt
  packages/main/src/ColorPalettePopover.js
Labels: for review, BREAKING CHANGE

#3883 feat(ui5-color-palette-popover): implement isOpen method
  packages/main/src/ColorPalettePopover.js
Labels: for review

#3892 chore: Use nodejs 14 and upgrade dependencies
  .travis.yml
  packages/base/hash.txt
  packages/base/package.json
  packages/fiori/package.json
  packages/icons-business-suite/package.json
  packages/icons-tnt/package.json
  packages/icons/package.json
  packages/ie11/package.json
  packages/localization/package.json
  packages/main/package.json
  packages/main/test/pages/Breadcrumbs.html
  packages/main/test/specs/Breadcrumbs.spec.js
  packages/theme-base/css-vars-usage.json
  packages/theme-base/hash.txt
  packages/theme-base/package.json
  packages/tools/package.json
  yarn.lock
Labels: for review

#3917 feat(ui5-upload-collection): Added "accessibleName" property
  packages/fiori/src/UploadCollection.hbs
  packages/fiori/src/UploadCollection.js
  packages/fiori/src/themes/UploadCollection.css
  packages/fiori/test/pages/UploadCollection.html
  packages/fiori/test/samples/UploadCollection.sample.html
  packages/fiori/test/specs/UploadCollection.spec.js
Labels: SF

#3911 fix(ui5-link): the anchor element inherits its text-decoration
  packages/main/src/themes/Link.css
Labels: SF

#3770 docs: fix datepicker docs
  packages/main/src/DatePicker.js
Labels: for review

#3833 fix(ui5-input): adjust value state paddings according to specifications
  packages/main/src/Input.js
  packages/main/src/themes/ValueStateMessage.css
Labels: SF

#3939 fix(ui5-toast): Content is announced when ui5-toast is shown
  packages/main/src/Toast.hbs
  packages/main/src/Toast.js
  packages/main/test/specs/Toast.spec.js
Labels: SF

#3705 fix(ui5-select): correct screen reader speech out when popover is opened
  packages/main/src/Select.hbs
  packages/main/src/Select.js
  packages/main/src/SelectPopover.hbs
  packages/main/test/specs/Select.spec.js
Labels: CBC

#3952 fix(ui5-list): change role mappings so no interactive elements are ne…
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.js
  packages/main/src/TreeListItem.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/pages/List_test_page.html
  packages/main/test/specs/List.spec.js
Labels: SF

#3989 refactor: Use waitUntil in tests
  packages/base/hash.txt
  packages/fiori/test/specs/Page.spec.js
  packages/fiori/test/specs/Wizard.spec.js
  packages/main/test/specs/BusyIndicator.spec.js
  packages/main/test/specs/ComboBox.spec.js
  packages/main/test/specs/DateTimePicker.spec.js
  packages/main/test/specs/Dialog.spec.js
  packages/main/test/specs/Input.spec.js
  packages/main/test/specs/List.spec.js
  packages/main/test/specs/MultiComboBox.spec.js
  packages/main/test/specs/Panel.spec.js
  packages/main/test/specs/TabContainer.spec.js
  packages/main/test/specs/Table.spec.js
  packages/main/test/specs/TimePicker.spec.js
  packages/main/test/specs/Toast.spec.js
  packages/tools/components-package/wdio.js
Labels: for review

#3996 chore: remove redundant assert
  packages/main/test/specs/ComboBox.spec.js
Labels: for review

#3941 fix: detach events correctly to prevent memory leaks
  packages/base/src/EventProvider.js
Labels: RBSC

#4016 chore: Create a test for EventProvider
  packages/base/bundle.esm.js
  packages/base/test/specs/EventProvider.spec.js
Labels: for review

#4020 feat(ui5-popover, ui5-responsive-popover): implement sap_horizon theme
  packages/main/src/themes/Popover.css
  packages/main/src/themes/PopupsCommon.css
  packages/main/src/themes/base/PopupsCommon-parameters.css
  packages/main/src/themes/sap_horizon/Popover-parameters.css
  packages/main/src/themes/sap_horizon/parameters-bundle.css
Labels: for review, sap_horizon
