Repository SAP/ui5-webcomponents, pull requests merged in 2021-01, with the labels that each got.

#2583 fix(ui5-popup): correct focus when there is no focusable content
  packages/main/src/Dialog.js
  packages/main/src/Popover.js
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
  packages/main/src/themes/PopupsCommon.css
  packages/main/test/pages/Popover.html
  packages/main/test/specs/Popover.spec.js
Labels: for review

#2639 fix(ui5-tabcontainer): overflow menu button is added a title
  packages/main/src/TabContainer.hbs
Labels: ACC

#2635 fix(ui5-carousel): titles are added to arrows
  packages/main/src/Carousel.hbs
  packages/main/src/Carousel.js
  packages/main/src/i18n/messagebundle.properties
Labels: ACC

#2578 feat(ui5-li-notification*): full-fill accessibility spec
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListGroupItem.js
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/NotificationListItemBase.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/src/themes/NotificationListGroupItem.css
  packages/fiori/src/themes/NotificationListItem.css
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/specs/NotificationList.spec.js
Labels: ACC, for review

#2636 feat(ui5-tree): implement acc spec
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.js
  packages/main/src/Tree.hbs
  packages/main/src/TreeListItem.hbs
  packages/main/src/TreeListItem.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/TreeListItem.css
Labels: ACC, SF

#2646 feat(framework): Create attachDirectionChange function
  packages/base/src/locale/applyDirection.js
  packages/base/src/locale/directionChange.js
  packages/main/bundle.esm.js
  packages/main/test/pages/RTL.html
Labels: for review

#2648 feat(ui5-calendar): Declarative dates support added
  packages/main/src/Calendar.hbs
  packages/main/src/Calendar.js
  packages/main/src/CalendarDate.js
  packages/main/src/CalendarPart.js
  packages/main/src/DatePicker.js
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/DateRangePicker.js
  packages/main/src/DateTimePicker.js
  packages/main/src/DateTimePickerPopover.hbs
  packages/main/src/DayPicker.js
  packages/main/src/MonthPicker.js
  packages/main/src/YearPicker.js
  packages/main/test/pages/Calendar.html
Labels: for review

#2584 fix(ui5-li-notification-group): align priority icon
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/themes/NotificationListGroupItem.css
  packages/fiori/src/themes/NotificationListItem.css
Labels: for review

#2660 fix(ui5-calendar): Today date is properly calculated
  packages/localization/src/dates/getTodayUTCTimestamp.js
  packages/main/src/CalendarPart.js
  packages/main/src/DatePicker.js
  packages/main/src/DateRangePicker.js
  packages/main/test/samples/Calendar.sample.html
Labels: for review

#2671 fix(ui5-tree): accessibility improvements
  packages/main/src/ListItem.hbs
  packages/main/src/Tree.hbs
  packages/main/src/Tree.js
  packages/main/src/TreeListItem.js
Labels: ACC, SF

#2674 fix(ui5-upload-collection): wrap noDataText/Desc text
  packages/fiori/src/UploadCollection.hbs
Labels: SF

#2678 chore: Upgrade Chromedriver to 87
  packages/base/package.json
  packages/fiori/package.json
  packages/icons-tnt/package.json
  packages/icons/package.json
  packages/localization/package.json
  packages/main/package.json
  packages/theme-base/package.json
  yarn.lock
Labels: for review

#2684 fix(ui5-list): show busy indicator over the list
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/src/themes/List.css
  packages/main/test/pages/List.html
  packages/main/test/pages/List_test_page.html
Labels: SF

#2620 feat(ui5-range-slider): focus and keyboard handling implementation
  packages/main/src/RangeSlider.hbs
  packages/main/src/RangeSlider.js
  packages/main/src/themes/SliderBase.css
  packages/main/src/themes/base/SliderBase-parameters.css
  packages/main/test/specs/RangeSlider.spec.js
Labels: ACC

#2711 feat(ui5-tree-item): implement info/infoState attributes
  packages/main/src/Tree.hbs
  packages/main/src/TreeItem.js
  packages/main/src/TreeListItem.hbs
  packages/main/src/TreeListItem.js
  packages/main/src/themes/TreeListItem.css
  packages/main/test/pages/Tree.html
Labels: SF

#2716 refactor(framework): Simplify ui5-static-area-item
  packages/base/src/StaticArea.js
  packages/base/src/StaticAreaItem.js
  packages/base/src/UI5Element.js
  packages/base/src/updateShadowRoot.js
  packages/main/src/TabContainer.js
  packages/main/test/pages/MemoryLeak.html
Labels: for review

#2722 refactor(framework): Reorder base code
  packages/base/src/StaticAreaItem.js
  packages/base/src/UI5Element.js
  packages/base/src/UI5ElementMetadata.js
  packages/base/src/locale/getEffectiveDir.js
  packages/base/src/util/SlotsHelper.js
  packages/base/src/util/getEffectiveContentDensity.js
  packages/base/src/util/isSlot.js
  packages/main/src/WheelSlider.js
Labels: for review

#2714 feat(ui5-slider, ui5-range-slider): Implement accessibility specifications
  packages/main/src/RangeSlider.hbs
  packages/main/src/RangeSlider.js
  packages/main/src/Slider.hbs
  packages/main/src/Slider.js
  packages/main/src/SliderBase.hbs
  packages/main/src/SliderBase.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/SliderBase.css
  packages/main/test/specs/RangeSlider.spec.js
  packages/main/test/specs/Slider.spec.js
Labels: ACC

#2628 fix(ui5-date-picker): input type is now conveyed
  packages/main/src/DatePicker.js
  packages/main/src/Input.hbs
  packages/main/src/Input.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/specs/DatePicker.spec.js
Labels: ACC

#2743 refactor(framework): Move CustomResize code to the ie11 package
  packages/base/src/delegate/CustomResize.js
  packages/base/src/delegate/NativeResize.js
  packages/base/src/delegate/ResizeHandler.js
  packages/ie11/src/CustomResize.js
  packages/ie11/src/integrate.js
  packages/main/test/pages/Table.html
Labels: for review
