Repository SAP/ui5-webcomponents, pull requests merged in 2021-03, with the labels that each got.

#2888 fix(ui5-wizard): prevent scrolling to step's very top
  packages/fiori/src/Wizard.js
  packages/fiori/test/specs/Wizard.spec.js
Labels: SF

#2908 chore(framework): Register all themes
  packages/tools/lib/generate-json-imports/themes.js
Labels: for review

#2932 chore: do not distribute the webcomponentsjs polyfill's src dir
  packages/tools/components-package/nps.js
Labels: SF, for review

#2941 chore: Re-enable eslint checks
  packages/main/src/Button.js
  packages/main/src/CheckBox.js
  packages/main/src/ColorPalette.js
  packages/main/src/ComboBox.js
  packages/main/src/CustomListItem.js
  packages/main/src/Icon.js
  packages/main/src/Panel.js
  packages/main/src/RadioButton.js
  packages/main/src/ResponsivePopover.js
  packages/main/src/features/ColorPaletteMoreColors.js
  packages/tools/components-package/nps.js
Labels: for review

#2947 chore: fix lint errors
  packages/main/src/DateRangePicker.js
  packages/main/src/Popover.js
Labels: for review

#2949 chore: upgrade postcss and plugins
  packages/theme-base/package.json
  packages/tools/lib/postcss-css-to-esm/index.js
  packages/tools/lib/postcss-css-to-json/index.js
  packages/tools/package.json
  yarn.lock
Labels: for review

#2956 chore: Define ui5-static-area
  packages/base/src/StaticAreaItem.js
Labels: for review

#2957 chore: Upgrade all dependencies
  package.json
  packages/base/.eslintignore
  packages/base/package.json
  packages/fiori/.eslintignore
  packages/ie11/.eslintignore
  packages/ie11/package.json
  packages/localization/.eslintignore
  packages/localization/package.json
  packages/main/.eslintignore
  packages/main/src/Dialog.js
  packages/main/src/FileUploader.js
  packages/playground/package.json
  packages/theme-base/package.json
  packages/tools/package.json
  yarn.lock
Labels: for review

#2955 fix(ui5-table-column): align content right in RTL
  packages/main/src/TableColumn.hbs
  packages/main/src/themes/TableColumn.css
Labels: SF

#2954 fix(ui5-table-row): fire row-click on SPACE/ENTER
  packages/main/src/TableRow.hbs
  packages/main/src/TableRow.js
  packages/main/test/specs/Table.spec.js
Labels: SF

#2950 feat(ui5-list): introduce "growing" property
  packages/base/src/util/isElementInView.js
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/src/Table.hbs
  packages/main/src/Table.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/List.css
  packages/main/src/themes/LoadMoreRow.css
  packages/main/src/themes/Table.css
  packages/main/src/themes/base/LoadMoreRow-parameters.css
  packages/main/src/themes/base/TableLoadMoreRow-parameters.css
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/src/themes/sap_belize/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcb/LoadMoreRow-parameters.css
  packages/main/src/themes/sap_belize_hcb/TableLoadMoreRow-parameters.css
  packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcw/LoadMoreRow-parameters.css
  packages/main/src/themes/sap_belize_hcw/TableLoadMoreRow-parameters.css
  packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcb/LoadMoreRow-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/TableLoadMoreRow-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcw/LoadMoreRow-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/TableLoadMoreRow-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
  packages/main/src/types/GrowingMode.js
  packages/main/src/types/ListGrowingMode.js
  packages/main/src/types/TableGrowingMode.js
  packages/main/test/pages/List.html
  packages/main/test/pages/ListGrowing_Button.html
  packages/main/test/pages/ListGrowing_Scroll.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/samples/List.sample.html
  packages/main/test/specs/Table.spec.js
Labels: SF

#2959 chore: apply new eslint rules
  packages/base/package.json
  packages/base/src/Boot.js
  packages/base/src/InitialConfiguration.js
  packages/base/src/MediaRange.js
  packages/base/src/Render.js
  packages/base/src/StaticArea.js
  packages/base/src/StaticAreaItem.js
  packages/base/src/UI5Element.js
  packages/base/src/util/getClassCopy.js
  packages/fiori/src/Page.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/Wizard.js
  packages/fiori/src/upload-utils/UploadCollectionBodyDnD.js
  packages/ie11/package-scripts.js
  packages/ie11/package.json
  packages/ie11/src/features/IE11.js
  packages/main/src/CheckBox.js
  packages/main/src/ColorPicker.js
  packages/main/src/DateTimePicker.js
  packages/main/src/DayPicker.js
  packages/main/src/Dialog.js
  packages/main/src/Link.js
  packages/main/src/List.js
  packages/main/src/MultiComboBox.js
  packages/main/src/Panel.js
  packages/main/src/Popup.js
  packages/main/src/RangeSlider.js
  packages/main/src/Slider.js
  packages/main/src/SliderBase.js
  packages/main/src/StepInput.js
  packages/main/src/Switch.js
  packages/main/src/TextArea.js
  packages/main/src/features/InputElementsFormSupport.js
  packages/main/src/popup-utils/PopoverRegistry.js
  packages/main/src/popup-utils/PopupUtils.js
  packages/main/src/types/GrowingMode.js
  packages/main/src/types/PopoverVerticalAlign.js
  packages/main/src/types/ToastPlacement.js
  packages/tools/package.json
  yarn.lock
Labels: for review

#2966 chore: use scoping-friendly selectors
  packages/main/src/ColorPalette.js
  packages/main/src/Select.js
  packages/main/src/themes/AvatarGroup.css
  packages/main/src/themes/ColorPaletteStaticArea.css
  packages/main/src/themes/ColorPicker.css
  packages/main/src/themes/Token.css
Labels: for review

#2965 chore: build static resources for IE
  packages/tools/components-package/rollup.js
Labels: for review

#2933 chore(tools): Optimize the build and start tasks
  package.json
  packages/base/hash.txt
  packages/base/package-scripts.js
  packages/base/package.json
  packages/fiori/package-scripts.js
  packages/fiori/package.json
  packages/icons-tnt/hash.txt
  packages/icons-tnt/package.json
  packages/icons/hash.txt
  packages/icons/package.json
  packages/ie11/.eslintignore
  packages/ie11/hash.txt
  packages/ie11/package-scripts.js
  packages/ie11/package.json
  packages/localization/hash.txt
  packages/localization/package-scripts.js
  packages/localization/package.json
  packages/main/package-scripts.js
  packages/main/package.json
  packages/theme-base/hash.txt
  packages/theme-base/package-scripts.js
  packages/theme-base/package.json
  packages/tools/components-package/nps.js
  packages/tools/components-package/rollup.js
  packages/tools/icons-collection/nps.js
  packages/tools/lib/copy-and-watch/index.js
  packages/tools/lib/hash/config.js
  packages/tools/lib/hash/folder-hash-customized/LICENSE.txt
  packages/tools/lib/hash/folder-hash-customized/index.js
  packages/tools/lib/hash/generate.js
  packages/tools/lib/hash/upToDate.js
  packages/tools/lib/i18n/toJSON.js
  packages/tools/lib/polyfill-placeholder/index.js
  packages/tools/package.json
  yarn.lock
Labels: for review

#2980 feat(framework): Maintain a common z-index for all UI5 Web Components instances and OpenUI5
  packages/base/hash.txt
  packages/base/src/features/OpenUI5Support.js
  packages/base/src/util/PopupUtils.js
  packages/main/src/Popover.js
  packages/main/src/Popup.js
  packages/main/src/ResponsivePopover.js
  packages/main/src/Toast.js
  packages/main/src/popup-utils/PopoverRegistry.js
Labels: SF, for review

#2985 docs: require Node.js 14
  README.md
  docs/dev/Development Workflow.md
Labels: for review

#2967 fix(ui5-avatar): fix click event fired twice
  packages/main/src/Avatar.js
  packages/main/src/AvatarGroup.hbs
  packages/main/src/AvatarGroup.js
  packages/main/test/pages/Avatar.html
  packages/main/test/specs/Avatar.spec.js
Labels: SF

#2991 fix(ui5-select): set aria-expanded initially
  packages/main/src/Select.js
  packages/main/test/specs/Select.spec.js
Labels: SF

#2992 chore: improve build responsiveness
  packages/tools/components-package/nps.js
  packages/tools/lib/postcss-new-files/index.js
  packages/tools/package.json
  yarn.lock
Labels: for review

#3004 chore: fix the hash for the base package
  packages/base/hash.txt
Labels: for review

#3016 chore: update folder-hash
  packages/base/hash.txt
  packages/icons-tnt/hash.txt
  packages/icons/hash.txt
  packages/ie11/hash.txt
  packages/localization/hash.txt
  packages/tools/lib/hash/folder-hash-customized/LICENSE.txt
  packages/tools/lib/hash/folder-hash-customized/index.js
  packages/tools/lib/hash/generate.js
  packages/tools/lib/hash/upToDate.js
  packages/tools/package.json
  yarn.lock
Labels: for review

#3008 chore: reserve free ports for main and fiori
  .gitignore
  packages/base/package-scripts.js
  packages/fiori/package-scripts.js
  packages/fiori/package.json
  packages/fiori/test/specs/_port.js
  packages/main/package-scripts.js
  packages/main/package.json
  packages/main/test/specs/_port.js
  packages/tools/components-package/nps.js
  packages/tools/components-package/rollup.js
  packages/tools/lib/serve/index.js
  packages/tools/lib/serve/serve.json
  packages/tools/package.json
  yarn.lock
Labels: for review

#3017 chore: improve the localization build
  packages/localization/lib/copy-list/index.js
Labels: for review

#3009 refactor(ui5-wizard): configure step change threshold
  packages/fiori/src/Wizard.js
  packages/fiori/test/pages/Wizard_test.html
Labels: SF

#3019 docs: document native metadata events
  packages/fiori/src/SideNavigationItem.js
  packages/fiori/src/SideNavigationSubItem.js
  packages/fiori/src/UploadCollection.js
  packages/main/src/Button.js
  packages/main/src/Link.js
  packages/tools/lib/jsdoc/plugin.js
  packages/tools/lib/jsdoc/template/publish.js
Labels: for review

#2977 docs: fix breakpoints info
  packages/fiori/src/FlexibleColumnLayout.js
Labels: SF

#3023 chore: fix IE11 bundle
  packages/fiori/bundle.common.js
  packages/fiori/bundle.es5.js
  packages/fiori/bundle.esm.js
  packages/main/bundle.common.js
  packages/main/bundle.es5.js
  packages/main/bundle.esm.js
Labels: for review

#2984 fix(ui5-togglebutton): fix hover background on desktop
  packages/main/src/themes/ToggleButton.css
Labels: for review

#3024 feat: add new icons
  packages/icons/hash.txt
  packages/icons/src/SAP-icons.json
Labels: for review

#2864 fix(ui5-input): fix Backspace on Input type=Number
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
  packages/main/test/specs/Input.spec.js
Labels: SF, for review

#3026 fix(ui5-file-uploader): opening dialog with space or enter key
  packages/main/src/FileUploader.hbs
  packages/main/src/FileUploader.js
Labels: SF

#3034 feat(ui5-wizard): add parameter to selectionChange event
  packages/fiori/src/Wizard.js
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/specs/Wizard.spec.js
Labels: SF

#3044 fix(ui5-dialog): Fix aria-labelledby attribute value
  packages/main/src/Dialog.hbs
  packages/main/src/Dialog.js
Labels: SF

#3058 chore: fix bundle problems for fiori
  packages/fiori/src/Page.js
  packages/fiori/src/Wizard.js
Labels: for review

#3056 chore: disable the whole unstable test
  packages/main/test/specs/MultiComboBox.spec.js
Labels: for review

#3055 chore(ie11): Provide a polyfill feature without fetch
  packages/ie11/src/features/IE11WithoutFetch.js
Labels: SF, for review

#3061 fix(ui5-upload-collection-item): make use of both main & fiori i18n bundles
  packages/fiori/src/UploadCollectionItem.js
Labels: SF, for review
