Repository SAP/ui5-webcomponents, pull requests merged in 2021-05, with the labels that each got.

#2865 feat(ui5-product-switch): Implement accessibility specification
  packages/fiori/src/ProductSwitch.hbs
  packages/fiori/src/ProductSwitch.js
  packages/fiori/src/ProductSwitchItem.hbs
  packages/fiori/src/ProductSwitchItem.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/test/specs/ProductSwitch.spec.js
Labels: ACC, for review

#3219 fix(ui5-rating-indicator): Aria-readonly attribute added
  packages/main/src/RatingIndicator.hbs
  packages/main/src/RatingIndicator.js
  packages/main/test/pages/RatingIndicator.html
  packages/main/test/specs/RatingIndicator.spec.js
Labels: ACC, SF

#3182 fix(ui5-label): fix required label in safari
  packages/main/src/Label.hbs
  packages/main/src/Label.js
  packages/main/src/themes/Label.css
Labels: SF, for review

#3210 docs(ui5-page): improve docs
  packages/fiori/src/Page.js
  packages/fiori/src/themes/Page.css
Labels: for review

#3244 fix(ui5-list): rename inset property to indent
  packages/main/src/List.js
  packages/main/src/themes/List.css
  packages/main/test/pages/List_keyboard_support.html
  packages/main/test/pages/Popups.html
Labels: BREAKING_CHANGE

#3227 fix(ui5-button): remove iconSize property
  packages/main/src/Button.hbs
  packages/main/src/Button.js
  packages/main/src/MessageStrip.hbs
  packages/main/src/themes/MessageStrip.css
Labels: BREAKING_CHANGE

#3188 chore: add links to the docs on the landing page of the playground
  packages/playground/_layouts/default.html
  packages/playground/_sass/layout.scss
  packages/playground/assets/css/landing-page.css
  packages/playground/docs/landing-page.html
Labels: for review

#3247 refactor(ui5-wizard): selection-change renamed to step-change
  packages/fiori/src/Wizard.js
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/samples/Wizard.sample.html
  packages/fiori/test/specs/Wizard.spec.js
Labels: BREAKING_CHANGE

#3154 feat(ui5-avatar-group): Implement accessibility specification
  packages/main/src/Avatar.hbs
  packages/main/src/Avatar.js
  packages/main/src/AvatarGroup.hbs
  packages/main/src/AvatarGroup.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/pages/Avatar.html
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/specs/Avatar.spec.js
  packages/main/test/specs/AvatarGroup.spec.js
Labels: ACC

#3228 fix(ui5-carousel): implement hideNavigationArrows property
  packages/main/src/Carousel.hbs
  packages/main/src/Carousel.js
Labels: BREAKING_CHANGE

#3245 refactor(ui5-shellbar): rename notificationCount property to notificationsCount
  packages/fiori/src/ShellBar.hbs
  packages/fiori/src/ShellBar.js
  packages/fiori/src/themes/ShellBar.css
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/ShellBar.html
  packages/fiori/test/samples/FlexibleColumnLayout.sample.html
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
  packages/fiori/test/samples/ShellBar.sample.html
Labels: BREAKING_CHANGE

#3222 refactor(ui5-avatar): rename backgroundColor property to colorScheme
  packages/main/src/Avatar.js
  packages/main/src/AvatarGroup.js
  packages/main/src/themes/Avatar.css
  packages/main/src/types/AvatarColorScheme.js
  packages/main/test/pages/Avatar.html
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/samples/Avatar.sample.html
  packages/main/test/samples/AvatarGroup.sample.html
  packages/main/test/specs/AvatarGroup.spec.js
Labels: BREAKING_CHANGE

#3261 fix(ui5-textarea): revert value on escape
  packages/main/src/TextArea.js
  packages/main/test/specs/TextArea.spec.js
Labels: ACC

#3273 refactor(ui5-table): more(sub)Text replaced by growingButton(sub)Text
  packages/base/hash.txt
  packages/main/src/List.hbs
  packages/main/src/List.js
  packages/main/src/Table.hbs
  packages/main/src/Table.js
  packages/main/src/themes/GrowingButton.css
  packages/main/src/themes/List.css
  packages/main/src/themes/Table.css
  packages/main/src/themes/base/GrowingButton-parameters.css
  packages/main/src/themes/sap_belize/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcb/GrowingButton-parameters.css
  packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcw/GrowingButton-parameters.css
  packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcb/GrowingButton-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcw/GrowingButton-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
  packages/main/test/pages/TableGrowingWithButton.html
  packages/main/test/samples/Table.sample.html
  packages/main/test/specs/List.spec.js
  packages/main/test/specs/Table.spec.js
Labels: BREAKING_CHANGE

#3302 fix(ui5-table): introduce hide-no-data property
  packages/main/src/Table.hbs
  packages/main/src/Table.js
  packages/main/test/pages/Table.html
  packages/main/test/samples/Table.sample.html
Labels: BREAKING_CHANGE

#3328 fix(ui5-flexible-column-layout): column borders in high contrast themes
  packages/fiori/src/themes/sap_fiori_3_hcb/FlexibleColumnLayout-parameters.css
  packages/fiori/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_hcw/FlexibleColumnLayout-parameters.css
  packages/fiori/src/themes/sap_fiori_3_hcw/parameters-bundle.css
Labels: SF

#3337 refactor(ui5-toggle-button): rename tag name
  docs/Public Module Imports.md
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/samples/Wizard.sample.html
  packages/main/README.md
  packages/main/src/DateTimePickerPopover.hbs
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/SegmentedButton.js
  packages/main/src/ToggleButton.js
  packages/main/src/themes/SegmentedButton.css
  packages/main/src/themes/ToggleButton.ie11.css
  packages/main/test/pages/Button.html
  packages/main/test/pages/Calendar.html
  packages/main/test/pages/Components.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/RTL.html
  packages/main/test/pages/SegmentedButton.html
  packages/main/test/pages/Select.html
  packages/main/test/pages/ToggleButton.html
  packages/main/test/pages/Tree.html
  packages/main/test/pages/kitchen-styles.css
  packages/main/test/samples/SegmentedButton.sample.html
  packages/main/test/samples/ToggleButton.sample.html
  packages/main/test/specs/SegmentedButton.spec.js
  packages/playground/lib/static-index.js
Labels: BREAKING_CHANGE

#3338 refactor(ui5-tabcontainer): deprecate tabsPlacement
  packages/main/src/TabContainer.js
  packages/main/src/types/TabContainerTabsPlacement.js
  packages/main/test/pages/TabContainer.html
Labels: BREAKING_CHANGE

#3270 refactor(ui5-product-switch-item): rename heading/subtitle to titleText/subtitleText
  packages/fiori/src/ProductSwitchItem.hbs
  packages/fiori/src/ProductSwitchItem.js
  packages/fiori/src/themes/ProductSwitchItem.css
  packages/fiori/test/pages/ProductSwitch.html
  packages/fiori/test/pages/ProductSwitchItem.html
  packages/fiori/test/samples/ProductSwitch.sample.html
  packages/fiori/test/specs/ProductSwitchItem.spec.js
Labels: BREAKING_CHANGE

#3259 fix(list items): rename info & infoState properties
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/ShellBar.html
  packages/fiori/test/samples/FlexibleColumnLayout.sample.html
  packages/main/src/AvatarGroup.hbs
  packages/main/src/ComboBox.js
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/InputPopover.hbs
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/StandardListItem.hbs
  packages/main/src/StandardListItem.js
  packages/main/src/SuggestionItem.js
  packages/main/src/SuggestionListItem.hbs
  packages/main/src/Tree.hbs
  packages/main/src/TreeItem.js
  packages/main/src/TreeListItem.hbs
  packages/main/src/TreeListItem.js
  packages/main/src/features/InputSuggestions.js
  packages/main/src/themes/ListItem.css
  packages/main/test/pages/Carousel.html
  packages/main/test/pages/Input.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/List.html
  packages/main/test/pages/ListGrowing_Button.html
  packages/main/test/pages/ListGrowing_Scroll.html
  packages/main/test/pages/Popover.html
  packages/main/test/pages/Tree.html
  packages/main/test/samples/Input.sample.html
  packages/main/test/samples/List.sample.html
  packages/main/test/specs/ComboBox.spec.js
  packages/main/test/specs/MultiComboBox.spec.js
Labels: BREAKING_CHANGE

#3276 fix(ui5-messagestrip): rename type property to design
  packages/base/hash.txt
  packages/main/src/MessageStrip.js
  packages/main/src/types/MessageStripDesign.js
  packages/main/test/pages/MessageStrip.html
  packages/main/test/samples/MessageStrip.sample.html
Labels: BREAKING_CHANGE, for review

#3350 refactor(ui5-input): remove highlight property
  packages/main/src/Input.js
  packages/main/test/pages/Input.html
Labels: BREAKING_CHANGE

#3346 fix(ui5-messagestrip): rename properties
  packages/main/src/MessageStrip.hbs
  packages/main/src/MessageStrip.js
  packages/main/src/themes/MessageStrip.css
  packages/main/test/pages/MessageStrip.html
  packages/main/test/samples/MessageStrip.sample.html
Labels: BREAKING_CHANGE

#3334 fix(ui5-wizard-step): rename properties
  packages/fiori/src/Wizard.hbs
  packages/fiori/src/Wizard.js
  packages/fiori/src/WizardStep.js
  packages/fiori/src/WizardTab.hbs
  packages/fiori/src/WizardTab.js
  packages/fiori/src/themes/WizardTab.css
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/pages/Wizard_test_mobile.html
  packages/fiori/test/samples/Wizard.sample.html
Labels: BREAKING_CHANGE

#3316 fix(ui5-card): rename heading/subheading to titleText/subtitleText
  packages/main/src/Card.hbs
  packages/main/src/Card.js
  packages/main/src/themes/Card.css
  packages/main/test/pages/Card.html
  packages/main/test/pages/Carousel.html
  packages/main/test/pages/CarouselLoadMore.html
  packages/main/test/samples/Card.sample.html
  packages/main/test/samples/Carousel.sample.html
  packages/main/test/specs/Card.spec.js
Labels: BREAKING_CHANGE, for review

#3351 fix(ui5-popover): rename noArrow property to hideArrow
  packages/fiori/src/NotifactionOverflowActionsPopover.hbs
  packages/fiori/src/ShellBarPopover.hbs
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/FileUploaderPopover.hbs
  packages/main/src/InputPopover.hbs
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/Popover.js
  packages/main/src/SelectPopover.hbs
  packages/main/src/TabContainerPopover.hbs
  packages/main/src/TextAreaPopover.hbs
  packages/main/src/TimePickerPopover.hbs
  packages/main/src/TokenizerPopover.hbs
  packages/main/src/themes/Popover.css
  packages/main/test/pages/Dialog.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/Popover.html
  packages/main/test/pages/Popups.html
  packages/main/test/samples/ColorPalette.sample.html
  packages/main/test/specs/Popover.spec.js
Labels: BREAKING_CHANGE

#3352 fix(ui5-flexible-column-layout): rename noArrows property to hideArrows
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/test/pages/FCL.html
Labels: BREAKING_CHANGE

#3336 fix(ui5-tab): rename semanticColor property to design
  docs/How To Use.md
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/FCLApp.html
  packages/fiori/test/samples/FlexibleColumnLayout.sample.html
  packages/main/src/Tab.js
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/TabContainer.html
Labels: BREAKING_CHANGE

#3257 feat(ui5-switch): implement design property
  packages/main/src/Switch.js
  packages/main/src/types/SwitchDesign.js
  packages/main/test/pages/Switch.html
  packages/main/test/samples/Switch.sample.html
Labels: BREAKING_CHANGE

#3345 refactor(ui5-segmented-button): rename tag name
  docs/Public Module Imports.md
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/samples/Wizard.sample.html
  packages/main/README.md
  packages/main/src/DateTimePickerPopover.hbs
  packages/main/src/SegmentedButton.hbs
  packages/main/src/SegmentedButton.js
  packages/main/src/themes/SegmentedButton.css
  packages/main/test/pages/RTL.html
  packages/main/test/pages/SegmentedButton.html
  packages/main/test/pages/Tree.html
  packages/main/test/samples/SegmentedButton.sample.html
Labels: BREAKING_CHANGE
