Repository SAP/ui5-webcomponents, pull requests merged in 2021-02, with the labels that each got.

#2728 refactor(framework): Deprecate RenderScheduler in favor of Render.js
  packages/base/bundle.esm.js
  packages/base/package.json
  packages/base/src/Render.js
  packages/base/src/RenderScheduler.js
  packages/base/src/StaticAreaItem.js
  packages/base/src/UI5Element.js
  packages/base/src/config/Language.js
  packages/base/src/delegate/ItemNavigation.js
  packages/base/src/locale/applyDirection.js
  packages/base/src/theming/CustomStyle.js
  packages/base/test/specs/UI5ElementInvalidation.js
  packages/base/test/specs/UI5ElementLifecycle.js
  packages/base/test/specs/UI5ElementListenForChildPropChanges.spec.js
  packages/fiori/package.json
  packages/fiori/src/UploadCollectionItem.js
  packages/icons-tnt/package.json
  packages/icons/package.json
  packages/ie11/src/integrate.js
  packages/localization/package.json
  packages/main/bundle.esm.js
  packages/main/package.json
  packages/main/src/Calendar.js
  packages/main/src/DateRangePicker.js
  packages/main/src/Input.js
  packages/main/src/SegmentedButton.js
  packages/main/test/pageobjects/DayPickerTestPage.js
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/MemoryLeak.html
  packages/theme-base/package.json
  packages/tools/components-package/wdio.js
  packages/tools/lib/init-package/resources/bundle.esm.js
  yarn.lock
Labels: for review

#2761 feat(ui5-multi-input): Implement accessibility specifications
  packages/main/src/MultiComboBox.hbs
  packages/main/src/MultiComboBox.js
  packages/main/src/MultiInput.hbs
  packages/main/src/MultiInput.js
  packages/main/src/Tokenizer.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/pages/MultiComboBox.html
  packages/main/test/pages/MultiInput.html
  packages/main/test/specs/MultiComboBox.spec.js
  packages/main/test/specs/MultiInput.spec.js
Labels: ACC, for review

#2767 chore: Deprecate Internet Explorer 11
  README.md
  docs/Public Module Imports.md
  packages/ie11/README.md
Labels: for review

#2762 refactor(ui5-input, ui5-textarea, ui5-date-*): allow letter spacing
  packages/main/src/themes/DatePicker.css
  packages/main/src/themes/Input.css
  packages/main/src/themes/TextArea.css
Labels: for review

#2780 feat(framework): ItemNavigation cyclic behavior implemented for multiple rows
  packages/base/src/delegate/ItemNavigation.js
  packages/fiori/src/ProductSwitch.js
  packages/main/bundle.esm.js
Labels: for review

#2790 refactor(ui5-multi-input): Fix DOM structure
  packages/base/src/UI5Element.js
  packages/main/src/MultiInput.hbs
Labels: for review

#2783 fix(ui5-radiobutton): fix tab order within group
  packages/main/src/RadioButton.js
  packages/main/src/RadioButtonGroup.js
  packages/main/test/pages/RadioButton.html
  packages/main/test/specs/RadioButton.spec.js
Labels: SF

#2736 fix(ui5-input): ValueStateMessage width fixed
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/src/MultiComboBox.js
  packages/main/src/MultiComboBoxPopover.hbs
Labels: for review

#2798 docs(ui5-avatar-group): comment on the avatars' shape
  packages/main/src/AvatarGroup.js
  packages/main/test/pages/Avatar.html
Labels: for review

#2795 fix(ui5-multi-combobox): fix JS error on phone
  packages/main/src/MultiComboBox.js
Labels: for review

#2801 fix(ui5-wizard): observe content height changes
  packages/fiori/src/Wizard.js
  packages/fiori/src/themes/Wizard.css
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/specs/Wizard.spec.js
Labels: SF, for review

#2800 fix(ui5-popup): prevent focus on elements below block layer
  packages/main/src/Popup.hbs
  packages/main/src/Popup.js
  packages/main/test/pages/Popover.html
  packages/main/test/specs/Popover.spec.js
Labels: SF

#2742 fix(ui5-combobox): User action cancelled when clicking "X" on mobile
  packages/main/src/ComboBox.js
Labels: for review

#2813 refactor(framework): ItemNavigation public API clarified
  packages/base/src/delegate/ItemNavigation.js
  packages/fiori/src/ProductSwitch.js
  packages/fiori/src/Timeline.js
  packages/fiori/src/Wizard.js
  packages/main/src/AvatarGroup.js
  packages/main/src/ColorPalette.js
  packages/main/src/List.js
  packages/main/src/MultiComboBox.js
  packages/main/src/MultiInput.js
  packages/main/src/SegmentedButton.js
  packages/main/src/Select.js
  packages/main/src/TabContainer.js
  packages/main/src/Table.js
  packages/main/src/Tokenizer.js
  packages/main/test/specs/Select.spec.js
Labels: for review

#2816 fix(ui5-icon): ui5-icon i18n works for all packages
  packages/base/src/asset-registries/Icons.js
  packages/fiori/src/Assets.js
  packages/icons-tnt/src/SAP-icons-TNT.json
  packages/icons/src/SAP-icons.json
  packages/main/src/Assets.js
  packages/main/src/Icon.hbs
  packages/main/src/Icon.js
  packages/tools/lib/create-icons/index.js
Labels: for review

#2828 fix(ui5-checkbox): set aria-hidden attribute
  packages/main/src/CheckBox.hbs
Labels: SF

#2823 fix(ui5-responsive-popover): accessibility improvements
  packages/main/src/ResponsivePopover.hbs
  packages/main/src/ResponsivePopover.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/ResponsivePopover.css
  packages/main/src/themes/ResponsivePopoverCommon.css
  packages/main/test/pages/ResponsivePopover.html
Labels: SF

#2834 chore: fix and improve JSDoc
  packages/fiori/src/Bar.js
  packages/fiori/src/NotificationListGroupItem.js
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/Page.js
  packages/fiori/src/ProductSwitch.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/SideNavigationItem.js
  packages/fiori/src/Timeline.js
  packages/fiori/src/UploadCollection.js
  packages/fiori/src/Wizard.js
  packages/fiori/src/types/BarDesign.js
  packages/main/src/Avatar.js
  packages/main/src/AvatarGroup.js
  packages/main/src/Badge.js
  packages/main/src/Button.js
  packages/main/src/Calendar.js
  packages/main/src/Card.js
  packages/main/src/Carousel.js
  packages/main/src/ColorPalette.js
  packages/main/src/ComboBox.js
  packages/main/src/Dialog.js
  packages/main/src/FileUploader.js
  packages/main/src/GroupHeaderListItem.js
  packages/main/src/Input.js
  packages/main/src/Label.js
  packages/main/src/Link.js
  packages/main/src/List.js
  packages/main/src/MessageStrip.js
  packages/main/src/MultiComboBox.js
  packages/main/src/Option.js
  packages/main/src/SegmentedButton.js
  packages/main/src/Select.js
  packages/main/src/StandardListItem.js
  packages/main/src/TabContainer.js
  packages/main/src/Table.js
  packages/main/src/TableRow.js
  packages/main/src/Title.js
  packages/main/src/Toast.js
  packages/main/src/Tree.js
  packages/main/src/TreeItem.js
  packages/main/src/TreeListItem.js
  packages/tools/lib/documentation/index.js
  packages/tools/lib/jsdoc/plugin.js
  packages/tools/lib/jsdoc/template/publish.js
Labels: for review

#2852 chore: fix JSDoc prototype entry for properties/slots/events
  packages/fiori/src/NotificationAction.js
  packages/fiori/src/SideNavigationItem.js
  packages/fiori/src/SideNavigationSubItem.js
  packages/main/src/ColorPaletteItem.js
  packages/main/src/Icon.js
  packages/main/src/ListItemBase.js
  packages/main/src/Panel.js
  packages/main/src/SuggestionItem.js
  packages/main/src/SuggestionListItem.js
  packages/theme-base/css-vars-usage.json
Labels: for review

#2854 chore: fix several property types
  packages/main/src/Option.js
  packages/main/src/TabContainer.js
  packages/main/src/TableColumn.js
  packages/main/src/TextArea.js
Labels: for review

#2861 chore: Introduce the notion of interfaces for the purpose of JSDoc
  packages/fiori/src/Interfaces.js
  packages/fiori/src/NotificationAction.js
  packages/fiori/src/NotificationListGroupItem.js
  packages/fiori/src/NotificationListItem.js
  packages/fiori/src/NotificationListItemBase.js
  packages/fiori/src/ProductSwitch.js
  packages/fiori/src/ProductSwitchItem.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/ShellBarItem.js
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/SideNavigationItem.js
  packages/fiori/src/SideNavigationSubItem.js
  packages/fiori/src/Timeline.js
  packages/fiori/src/TimelineItem.js
  packages/fiori/src/UploadCollection.js
  packages/fiori/src/UploadCollectionItem.js
  packages/fiori/src/Wizard.js
  packages/fiori/src/WizardStep.js
  packages/main/src/Avatar.js
  packages/main/src/AvatarGroup.js
  packages/main/src/Badge.js
  packages/main/src/Button.js
  packages/main/src/Calendar.js
  packages/main/src/CalendarDate.js
  packages/main/src/ColorPalette.js
  packages/main/src/ColorPaletteItem.js
  packages/main/src/ComboBox.js
  packages/main/src/ComboBoxItem.js
  packages/main/src/CustomListItem.js
  packages/main/src/GroupHeaderListItem.js
  packages/main/src/Icon.js
  packages/main/src/Input.js
  packages/main/src/Interfaces.js
  packages/main/src/List.js
  packages/main/src/MessageStrip.js
  packages/main/src/MultiComboBox.js
  packages/main/src/MultiComboBoxItem.js
  packages/main/src/MultiInput.js
  packages/main/src/Option.js
  packages/main/src/SegmentedButton.js
  packages/main/src/Select.js
  packages/main/src/StandardListItem.js
  packages/main/src/SuggestionItem.js
  packages/main/src/Tab.js
  packages/main/src/TabContainer.js
  packages/main/src/TabSeparator.js
  packages/main/src/Table.js
  packages/main/src/TableCell.js
  packages/main/src/TableColumn.js
  packages/main/src/TableRow.js
  packages/main/src/Token.js
  packages/main/src/Tree.js
  packages/main/src/TreeItem.js
  packages/tools/lib/documentation/index.js
Labels: for review

#2858 fix(ui5-icon): fix click event fired twice
  packages/main/src/Icon.js
  packages/main/test/pages/Icon.html
  packages/main/test/specs/Icon.spec.js
Labels: SF, for review

#2853 feat(ui5-color-palette): implement more-colors property
  packages/main/bundle.esm.js
  packages/main/src/ColorPalette.hbs
  packages/main/src/ColorPalette.js
  packages/main/src/ColorPaletteDialog.hbs
  packages/main/src/Popup.js
  packages/main/src/features/ColorPaletteMoreColors.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/ColorPalette.css
  packages/main/src/themes/ColorPaletteStaticArea.css
  packages/main/test/pages/ColorPalette.html
  packages/main/test/specs/ColorPalette.spec.js
Labels: for review

#2871 chore: minor JSDoc fixes
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/Wizard.js
  packages/main/src/Input.js
Labels: for review

#2860 feat(ui5-panel): implement accessibleName
  packages/main/src/Panel.hbs
  packages/main/src/Panel.js
  packages/main/src/themes/Panel.css
  packages/main/test/pages/Panel.html
  packages/main/test/specs/Panel.spec.js
  packages/theme-base/css-vars-usage.json
Labels: ACC, SF

#2872 fix(ui5-icon): work of applied styles
  packages/main/src/themes/Icon.css
Labels: SF

#2870 fix(ui5-li-custom): keyboard handling improvement
  packages/main/src/CustomListItem.js
  packages/main/test/pages/List_test_page.html
  packages/main/test/specs/List.spec.js
Labels: SF
