Repository SAP/ui5-webcomponents, pull requests merged in 2021-04, with the labels that each got.

#2938 fix(ui5-busyindicator): add a11y support
  packages/main/src/BusyIndicator.hbs
  packages/main/src/BusyIndicator.js
  packages/main/src/themes/BusyIndicator.css
  packages/main/test/pages/BusyIndicator.html
  packages/main/test/specs/BusyIndicator.spec.js
Labels: ACC

#3046 refactor(ui5-button, ui5-li): make touch events handlers passive
  packages/main/src/Button.js
  packages/main/src/ListItem.js
Labels: for review

#3074 chore: warn developers if a key they're using is not in the bundle
  packages/base/hash.txt
  packages/base/src/i18nBundle.js
  packages/theme-base/css-vars-usage.json
Labels: SF

#3085 fix: keep invisible texts out of the view port
  packages/fiori/src/themes/InvisibleTextStyles.css
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/specs/Wizard.spec.js
  packages/main/src/themes/InvisibleTextStyles.css
Labels: ACC, SF

#3088 chore: show a deprecation warning for old tags
  packages/base/hash.txt
  packages/base/src/UI5Element.js
  packages/base/src/util/getClassCopy.js
Labels: for review

#3101 refactor: remove sap.ui.requireSync from localization code
  packages/localization/hash.txt
  packages/localization/overlay/sap/ui/base/Interface.js
Labels: for review

#3113 feat(ui5-color-palette): implement show-recent-color functionality
  packages/main/src/ColorPalette.hbs
  packages/main/src/ColorPalette.js
  packages/main/src/themes/ColorPalette.css
  packages/main/test/pages/ColorPalette.html
  packages/main/test/samples/ColorPalette.sample.html
  packages/main/test/specs/ColorPalette.spec.js
Labels: for review

#3127 fix(ui5-input): Suggestions count is read out when expected
  packages/main/src/Input.js
  packages/main/src/MultiInput.js
  packages/main/test/specs/Input.spec.js
  packages/main/test/specs/MultiInput.spec.js
Labels: ACC

#3105 fix(ui5-list): prevent load-more on initial intersection
  packages/main/src/List.js
  packages/main/test/pages/List_test_page.html
  packages/main/test/specs/List.spec.js
Labels: for review

#3168 refactor(ui5-icon): Show not-imported icons warning
  docs/Assets.md
  docs/Public Module Imports.md
  packages/base/hash.txt
  packages/base/src/asset-registries/Icons.js
  packages/icons-tnt/hash.txt
  packages/icons-tnt/src/AllIcons-static.js
  packages/icons-tnt/src/AllIcons.js
  packages/icons-tnt/src/Assets-static.js
  packages/icons-tnt/src/Assets.js
  packages/icons/hash.txt
  packages/icons/src/AllIcons-static.js
  packages/icons/src/AllIcons.js
  packages/icons/src/Assets-static.js
  packages/icons/src/Assets.js
  packages/main/bundle.es5.js
  packages/main/bundle.esm.js
  packages/main/src/Icon.js
Labels: for review

#3138 feat(framework): support sap-* config URL params
  packages/base/hash.txt
  packages/base/src/InitialConfiguration.js
  packages/base/test/specs/ConfigurationURL.spec.js
Labels: for review

#3178 fix(ui5-busyindicator): fix typo in styles
  packages/main/src/themes/BusyIndicator.css
Labels: SF

#3174 fix(ui5-carousel): hides navigation arrows on mouse out
  packages/main/src/Carousel.hbs
  packages/main/src/Carousel.js
  packages/main/src/themes/Carousel.css
  packages/main/test/specs/Carousel.spec.js
Labels: SF

#3180 fix(ui5-wizard): correct aria-controls value
  packages/fiori/src/Wizard.hbs
  packages/fiori/test/specs/Wizard.spec.js
Labels: ACC, SF

#3185 chore: make serve an optional dependency
  packages/base/hash.txt
  packages/tools/package.json
  yarn.lock
Labels: for review

#3155 feat(ui5-dialog): labeling of header slots is now possible
  packages/main/src/Dialog.js
  packages/main/test/pages/Dialog.html
  packages/main/test/specs/Dialog.spec.js
Labels: SF

#3183 chore: use only one tab for the playground app
  packages/playground/docs/landing-page.html
Labels: for review

#3118 refactor(ui5-color-palette): refactor rendering of items
  packages/main/src/ColorPalette.hbs
  packages/main/src/ColorPalette.js
  packages/main/src/ColorPaletteItem.hbs
  packages/main/src/ColorPaletteItem.js
  packages/main/src/themes/ColorPalette.css
  packages/main/src/themes/ColorPaletteItem.css
  packages/main/src/themes/base/sizes-parameters.css
Labels: for review
