Repository SAP/ui5-webcomponents, pull requests merged in 2021-06, with the labels that each got.

#3379 fix(ui5-title): rename wrap property to wrappingType
  packages/base/hash.txt
  packages/fiori/src/UploadCollection.hbs
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/samples/FlexibleColumnLayout.sample.html
  packages/main/src/Title.js
  packages/main/src/themes/Title.css
  packages/main/src/types/WrappingType.js
  packages/main/test/pages/DateTimePicker.html
  packages/main/test/pages/Title.html
  packages/main/test/specs/Components.spec.js
  packages/main/test/specs/Title.spec.js
Labels: BREAKING_CHANGE

#3361 refactor(ui5-busy-indicator): API enhancements
  docs/Public Module Imports.md
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/test/pages/FCLApp.html
  packages/main/README.md
  packages/main/src/BusyIndicator.hbs
  packages/main/src/BusyIndicator.js
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/List.hbs
  packages/main/src/Table.hbs
  packages/main/src/themes/BusyIndicator.css
  packages/main/test/pages/BusyIndicator.html
  packages/main/test/pages/CarouselLoadMore.html
  packages/main/test/pages/Components.html
  packages/main/test/pages/Tree.html
  packages/main/test/samples/BusyIndicator.sample.html
  packages/main/test/samples/Tree.sample.html
  packages/main/test/specs/BusyIndicator.spec.js
Labels: BREAKING_CHANGE, for review

#3380 fix(ui5-link): rename wrap property to wrappingType
  packages/fiori/src/NotificationAction.js
  packages/main/src/Link.js
  packages/main/src/Option.js
  packages/main/src/StandardListItem.js
  packages/main/src/SuggestionItem.js
  packages/main/src/themes/Link.css
  packages/main/test/pages/Link.html
  packages/main/test/specs/Components.spec.js
Labels: BREAKING_CHANGE

#3341 fix(ui5-label): rename wrap property to wrappingType
  packages/fiori/src/UploadCollection.hbs
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/pages/Wizard_test_mobile.html
  packages/fiori/test/samples/Wizard.sample.html
  packages/main/src/CheckBox.hbs
  packages/main/src/CheckBox.js
  packages/main/src/Label.js
  packages/main/src/RadioButton.hbs
  packages/main/src/RadioButton.js
  packages/main/src/themes/Label.css
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/Label.html
  packages/main/test/pages/Panel.html
  packages/main/test/samples/Label.sample.html
  packages/main/test/samples/Panel.sample.html
  packages/main/test/specs/Components.spec.js
Labels: BREAKING_CHANGE, for review

#3397 refactor(ui5-daterange-picker): rename first/lastDateValue
  packages/main/src/DateRangePicker.js
  packages/main/test/specs/DateRangePicker.spec.js
Labels: BREAKING_CHANGE

#3362 refactor(ui5-radiobutton): API enhancements
  packages/main/src/ListItem.hbs
  packages/main/src/RadioButton.hbs
  packages/main/src/RadioButton.js
  packages/main/src/RadioButtonGroup.js
  packages/main/src/themes/RadioButton.css
  packages/main/src/themes/base/RadioButton-parameters.css
  packages/main/src/themes/sap_belize_hcb/RadioButton-parameters.css
  packages/main/src/themes/sap_belize_hcw/RadioButton-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/RadioButton-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/RadioButton-parameters.css
  packages/main/test/pages/FormSupport.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/RadioButton.html
  packages/main/test/pages/form.html
  packages/main/test/samples/Label.sample.html
  packages/main/test/samples/RadioButton.sample.html
  packages/main/test/specs/Components.spec.js
  packages/main/test/specs/RadioButton.spec.js
Labels: BREAKING_CHANGE, for review

#3403 refactor(ui5-checkbox): replace `wrap` with `wrappingType`
  packages/main/src/CheckBox.hbs
  packages/main/src/CheckBox.js
  packages/main/src/themes/CheckBox.css
  packages/main/test/pages/CheckBox.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/samples/CheckBox.sample.html
  packages/main/test/specs/CheckBox.spec.js
Labels: BREAKING_CHANGE

#3409 refactor(ui5-radiobutton): replace `wrap` with `wrappingType`
  packages/main/src/RadioButton.hbs
  packages/main/src/RadioButton.js
  packages/main/src/themes/RadioButton.css
  packages/main/test/pages/RadioButton.html
  packages/main/test/samples/RadioButton.sample.html
  packages/main/test/specs/RadioButton.spec.js
Labels: BREAKING_CHANGE

#3413 fix(ui5-upload-collection): change file deleted event name
  packages/fiori/src/UploadCollection.js
  packages/fiori/test/pages/uploadCollectionScript.js
  packages/fiori/test/specs/UploadCollection.spec.js
Labels: BREAKING_CHANGE

#3248 feat(ui5-input): introduce new SuggestionGroupItem
  packages/main/src/Input.js
  packages/main/src/InputPopover.hbs
  packages/main/src/SuggestionGroupItem.js
  packages/main/src/SuggestionItem.js
  packages/main/src/features/InputSuggestions.js
  packages/main/test/pages/Input.html
Labels: BREAKING_CHANGE

#3375 fix(ui5-rating-indicator): rename maxValue property to max
  packages/main/src/RatingIndicator.hbs
  packages/main/src/RatingIndicator.js
  packages/main/test/pages/RatingIndicator.html
  packages/main/test/samples/RatingIndicator.sample.html
  packages/main/test/specs/RatingIndicator.spec.js
Labels: BREAKING_CHANGE

#3323 feat(ui5-select): support angular reactive forms
  packages/main/src/Select.js
Labels: for review

#3420 refactor(ui5-color-palette): change API
  packages/main/src/ColorPalette.js
  packages/main/test/samples/ColorPalette.sample.html
  packages/main/test/specs/ColorPalette.spec.js
Labels: BREAKING_CHANGE

#3387 refactor(ui5-timeline-item): rename API
  packages/fiori/src/TimelineItem.hbs
  packages/fiori/src/TimelineItem.js
  packages/fiori/test/pages/Timeline.html
  packages/fiori/test/samples/Timeline.sample.html
  packages/fiori/test/specs/Timeline.spec.js
  packages/main/test/samples/Card.sample.html
  packages/main/test/samples/Carousel.sample.html
Labels: BREAKING_CHANGE

#3258 feat(ui5-segmented-button-item): introduce new component to serve as child of SegmentedButton
  docs/Public Module Imports.md
  packages/main/bundle.common.js
  packages/main/src/SegmentedButton.hbs
  packages/main/src/SegmentedButton.js
  packages/main/src/SegmentedButtonItem.hbs
  packages/main/src/SegmentedButtonItem.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/SegmentedButton.css
  packages/main/test/pages/SegmentedButton.html
  packages/main/test/samples/SegmentedButton.sample.html
  packages/main/test/specs/SegmentedButton.spec.js
Labels: BREAKING_CHANGE

#3374 fix(ui5-link): event is now fired on space pressed
  packages/main/src/Link.js
Labels: SF

#3429 fix(ui5-color-palette): rename change event
  packages/main/src/ColorPalette.js
  packages/main/test/pages/ColorPalette.html
Labels: BREAKING_CHANGE

#3412 feat(ui5-page): implement responsive paddings
  packages/fiori/src/Bar.hbs
  packages/fiori/src/Bar.js
  packages/fiori/src/Page.js
  packages/fiori/src/themes/Page.css
  packages/fiori/test/pages/Page.html
  packages/fiori/test/samples/Page.sample.html
Labels: SF, for review

#3404 refactor(ui5-upload-collection): rename properties
  packages/fiori/src/UploadCollectionItem.js
  packages/fiori/test/pages/UploadCollection.html
  packages/fiori/test/specs/UploadCollection.spec.js
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.js
Labels: BREAKING_CHANGE

#3363 refactor(ui5-responsive-popover): API enhancements
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/Wizard.js
  packages/main/src/ComboBox.js
  packages/main/src/DatePicker.js
  packages/main/src/Input.js
  packages/main/src/MultiComboBox.js
  packages/main/src/ResponsivePopover.js
  packages/main/src/Select.js
  packages/main/src/TabContainer.js
  packages/main/src/TimePickerBase.js
  packages/main/src/Tokenizer.js
  packages/main/src/features/InputSuggestions.js
  packages/main/test/pages/ColorPalette.html
  packages/main/test/pages/ResponsivePopover.html
  packages/main/test/samples/ResponsivePopover.sample.html
Labels: BREAKING_CHANGE, for review

#3438 refactor(ui5-color-palette-item): remove `stableDomRef` as not needed
  packages/main/src/ColorPaletteItem.js
Labels: BREAKING_CHANGE

#3405 refactor(ui5-radio-button): change tag name
  README.md
  docs/Public Module Imports.md
  packages/fiori/src/NotificationListItem.js
  packages/main/README.md
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.js
  packages/main/src/RadioButton.js
  packages/main/src/themes/CustomListItem.css
  packages/main/src/themes/RadioButton.css
  packages/main/src/themes/base/RadioButton-parameters.css
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/src/themes/sap_belize_hcb/RadioButton-parameters.css
  packages/main/src/themes/sap_belize_hcw/RadioButton-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/RadioButton-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/RadioButton-parameters.css
  packages/main/test/pages/Components.html
  packages/main/test/pages/FormSupport.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/List.html
  packages/main/test/pages/List_keyboard_support.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/pages/RadioButton.html
  packages/main/test/pages/form.html
  packages/main/test/pages/kitchen-styles.css
  packages/main/test/samples/Label.sample.html
  packages/main/test/samples/RadioButton.sample.html
  packages/main/test/specs/DatePicker.spec.js
  packages/main/test/specs/List.spec.js
  packages/playground/lib/static-index.js
Labels: BREAKING_CHANGE

#3440 refactor(ui5-bar): rename middleContent slot
  packages/fiori/src/Bar.hbs
  packages/fiori/src/Bar.js
  packages/fiori/test/pages/Bar.html
  packages/fiori/test/pages/Page.html
  packages/fiori/test/samples/Bar.sample.html
  packages/fiori/test/samples/Page.sample.html
Labels: BREAKING_CHANGE

#3443 refactor(ui5-wizard): ARIA attributes enhanced
  packages/fiori/src/Wizard.hbs
  packages/fiori/src/Wizard.js
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/test/specs/Wizard.spec.js
Labels: ACC

#3108 chore: Upgrade to lit-html 2
  packages/base/hash.txt
  packages/base/package.json
  packages/base/src/renderer/LitRenderer.js
  packages/base/src/renderer/ifDefined.js
  packages/base/src/renderer/scopeHTML.js
  packages/base/src/updateShadowRoot.js
  packages/fiori/src/Page.js
  packages/fiori/src/ShellBar.js
  packages/fiori/test/pages/ProductSwitch.html
  packages/fiori/test/pages/ProductSwitchItem.html
  packages/ie11/hash.txt
  packages/ie11/package.json
  packages/ie11/src/features/IE11.js
  packages/ie11/src/features/IE11WithoutFetch.js
  packages/ie11/src/globalThis.js
  packages/main/src/MultiComboBox.js
  packages/main/src/RadioButton.js
  packages/main/src/StepInput.hbs
  packages/main/src/SuggestionListItem.js
  packages/main/src/themes/TableCell.css
  packages/main/src/themes/TableRow.css
  packages/main/test/pages/Components.html
  packages/main/test/pages/InputsAlignment.html
  packages/main/test/specs/TextArea.spec.js
  packages/tools/lib/hbs2lit/src/litVisitor2.js
  packages/tools/lib/hbs2ui5/RenderTemplates/LitRenderer.js
  yarn.lock
Labels: for review

#3464 fix(ui5-card): correct content html tag
  packages/main/src/Card.hbs
Labels: ACC

#3360 fix(ui5-carousel): enhance public api
  packages/main/src/Carousel.js
  packages/main/test/pages/Carousel.html
  packages/main/test/pages/CarouselLoadMore.html
  packages/main/test/samples/Carousel.sample.html
  packages/main/test/specs/Carousel.spec.js
Labels: BREAKING_CHANGE, for review

#3229 fix(ui5-avatar-group): deprecate avatarSize property
  packages/main/src/AvatarGroup.hbs
  packages/main/src/AvatarGroup.js
  packages/main/src/themes/AvatarGroup.css
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/samples/AvatarGroup.sample.html
  packages/main/test/specs/AvatarGroup.spec.js
  packages/theme-base/hash.txt
Labels: BREAKING_CHANGE

#3385 feat(ui5-li): title attribute handle
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.js
  packages/main/src/SuggestionListItem.js
  packages/main/src/Tree.hbs
  packages/main/src/TreeItem.js
Labels: SF
