Repository SAP/ui5-webcomponents, pull requests merged in 2021-12, with the labels that each got.

#4152 fix(ui5-textarea): Calc properly TextArea's size for showExceeds property
  packages/main/src/TextArea.js
  packages/main/test/pages/TextArea.html
Labels: SF

#4447 fix(ui5-input): fix event handling in firefox
  packages/main/src/Input.js
Labels: SF, for review

#4485 refactor: provide stable data attributes for static area items
  packages/base/hash.txt
  packages/base/src/StaticAreaItem.js
  packages/fiori/test/pages/ShellBar.html
Labels: SF

#4446 feat(ui5-flexible-column-layout): new property accessibilityRoles
  docs/2-advanced/07-accessibility.md
  packages/fiori/src/FlexibleColumnLayout.hbs
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/specs/FCL.spec.js
Labels: SF

#4536 fix(ui5-card-header): fix rtl support
  packages/main/src/CardHeader.hbs
  packages/main/src/themes/CardHeader.css
Labels: for review
