Repository SAP/ui5-webcomponents, pull requests merged in 2022-02, with the labels that each got.

#4676 chore(ui5-table): cleanup code
  packages/main/src/Table.js
  packages/main/src/TableColumn.js
Labels: for review

#4687 chore: update chromdriver
  packages/base/package.json
  packages/fiori/package.json
  packages/icons-business-suite/package.json
  packages/icons-tnt/package.json
  packages/icons/package.json
  packages/localization/package.json
  packages/main/package.json
  packages/theming/package.json
  yarn.lock
Labels: dependencies

#4655 feat(ui5-button): implement accessibilityAttributes property
  docs/2-advanced/07-accessibility.md
  packages/fiori/src/ShellBar.hbs
  packages/fiori/src/ShellBar.js
  packages/main/src/AvatarGroup.hbs
  packages/main/src/AvatarGroup.js
  packages/main/src/Button.hbs
  packages/main/src/Button.js
  packages/main/src/MessageStrip.hbs
  packages/main/src/MessageStrip.js
  packages/main/src/Panel.hbs
  packages/main/src/Panel.js
  packages/main/src/SegmentedButtonItem.hbs
  packages/main/test/pages/Button.html
  packages/main/test/pages/styles/Button.css
  packages/main/test/samples/Dialog.sample.html
  packages/main/test/specs/AvatarGroup.spec.js
  packages/main/test/specs/Button.spec.js
Labels: ACC, SF

#4706 fix(ui5-date-picker): remove combobox role
  packages/main/src/DatePicker.js
  packages/main/test/specs/DatePicker.spec.js
Labels: ACC

#4735 feat(ui5-switch): provide accessible-name attribute support
  packages/main/src/Switch.js
  packages/main/test/pages/Switch.html
  packages/main/test/specs/Switch.spec.js
Labels: ACC, SF

#4681 fix(templates): replace HTML comments with HBS ones
  packages/main/src/Calendar.hbs
  packages/main/src/DatePicker.hbs
  packages/main/src/List.hbs
  packages/main/src/Panel.hbs
  packages/main/src/StepInput.hbs
Labels: TOPIC Core

#4730 feat(ui5-tabcontainer, ui5-tab): implement sap_horizon_exp theme
  packages/base/package.json
  packages/fiori/package.json
  packages/icons-business-suite/package.json
  packages/icons-tnt/package.json
  packages/icons/package.json
  packages/localization/package.json
  packages/main/package.json
  packages/main/src/Tab.js
  packages/main/src/TabContainer.hbs
  packages/main/src/TabContainer.js
  packages/main/src/themes/TabContainer.css
  packages/main/src/themes/TabInStrip.css
  packages/main/src/themes/base/TabContainer-parameters.css
  packages/main/src/themes/sap_belize_hcb/TabContainer-parameters.css
  packages/main/src/themes/sap_belize_hcw/TabContainer-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/TabContainer-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/TabContainer-parameters.css
  packages/main/src/themes/sap_horizon/TabContainer-parameters.css
  packages/main/src/themes/sap_horizon_exp/TabContainer-parameters.css
  packages/main/test/pages/TabContainer.html
  packages/theming/package.json
  yarn.lock
Labels: for review

#4767 fix(ui5-textarea): enhance aria-invalid attribute handling
  packages/main/src/TextArea.hbs
  packages/main/test/specs/Input.spec.js
  packages/main/test/specs/TextArea.spec.js
Labels: ACC

#4737 feat(ui5-button): add new tooltip property
  packages/fiori/src/FlexibleColumnLayout.hbs
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/ShellBar.hbs
  packages/fiori/src/UploadCollectionItem.hbs
  packages/fiori/test/pages/Bar.html
  packages/fiori/test/pages/BarcodeScannerDialog.html
  packages/fiori/test/pages/Page.html
  packages/fiori/test/samples/Bar.sample.html
  packages/fiori/test/samples/Bar2.sample.html
  packages/fiori/test/samples/BarcodeScannerDialog.sample.html
  packages/fiori/test/samples/Page.sample.html
  packages/fiori/test/specs/FCL.spec.js
  packages/main/src/Button.hbs
  packages/main/src/Button.js
  packages/main/src/Carousel.hbs
  packages/main/src/Link.js
  packages/main/src/ListItem.hbs
  packages/main/src/MessageStrip.hbs
  packages/main/src/Panel.hbs
  packages/main/src/TabContainer.hbs
  packages/main/test/pages/Button.html
  packages/main/test/specs/Button.spec.js
Labels: SF

#4790 feat: add and update icons from 4.13 and 5.01 icon fonts
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  packages/base/hash.txt
  packages/icons/hash.txt
  packages/icons/src/v4/SAP-icons.json
  packages/icons/src/v5/SAP-icons.json
  packages/main/test/pages/Icon.html
  packages/main/test/specs/Icon.spec.js
Labels: SF

#4799 feat(ui5-radio-button): implement sap_horizon_exp theme
  packages/main/src/RadioButton.hbs
  packages/main/src/themes/RadioButton.css
  packages/main/src/themes/base/RadioButton-parameters.css
  packages/main/src/themes/sap_horizon_exp/RadioButton-parameters.css
Labels: for review

#4805 fix(ui5-list): fix separators in SAP Horizon
  packages/main/src/themes/ListItemBase.css
  packages/main/src/themes/base/ListItemBase-parameters.css
  packages/main/src/themes/sap_horizon/ListItemBase-parameters.css
Labels: SF

#4809 fix(ui5-list): initial focus target
  packages/base/hash.txt
  packages/main/src/List.js
  packages/main/test/pages/List_test_page.html
  packages/main/test/specs/List.spec.js
Labels: SF

#4811 fix(ui5-flexible-column-layout): improve accessibility
  packages/fiori/src/FlexibleColumnLayout.hbs
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/specs/FCL.spec.js
Labels: SF

#4763 fix(ui5-input): improve lazy loading behaviour
  packages/base/hash.txt
  packages/main/src/Input.js
  packages/main/test/pages/InputsLazyLoading.html
  packages/main/test/specs/Input.spec.js
Labels: SF

#4813 fix(ui5-popup): body styles are no longer modified
  packages/main/src/Popup.js
  packages/main/src/themes/PopupGlobal.css
  packages/main/test/pages/Dialog.html
  packages/main/test/pages/styles/Dialog.css
  packages/main/test/specs/Dialog.spec.js
Labels: SF
