Repository SAP/ui5-webcomponents, pull requests merged in 2022-01, with the labels that each got.

#4490 feat: implement F6 Navigation Helper
  .travis.yml
  packages/base/hash.txt
  packages/base/src/Boot.js
  packages/base/src/FeaturesRegistry.js
  packages/base/src/Keys.js
  packages/base/src/UI5Element.js
  packages/base/src/UI5ElementMetadata.js
  packages/base/src/util/FocusableElements.js
  packages/base/src/util/isNodeHidden.js
  packages/fiori/src/Bar.js
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/Wizard.js
  packages/fiori/test/pages/F6TestPage.html
  packages/fiori/test/specs/F6Handling.spec.js
  packages/main/bundle.common.js
  packages/main/src/Calendar.js
  packages/main/src/Carousel.js
  packages/main/src/List.js
  packages/main/src/MessageStrip.js
  packages/main/src/Panel.hbs
  packages/main/src/Panel.js
  packages/main/src/TabContainer.js
  packages/main/src/Table.js
  packages/main/src/features/F6NavigationHelper.js
  packages/tools/components-package/wdio.js
  packages/tools/components-package/wdio.sync.js
Labels: SF, for review

#4558 docs(f6 navigation): add documentation
  docs/1-getting-started/06-using-features.md
  packages/base/hash.txt
  packages/base/src/features/F6Navigation.js
  packages/fiori/src/Bar.js
  packages/fiori/src/FlexibleColumnLayout.js
  packages/fiori/src/ShellBar.js
  packages/fiori/src/SideNavigation.js
  packages/fiori/src/Wizard.js
  packages/main/bundle.common.js
  packages/main/bundle.es5.js
  packages/main/bundle.esm.js
  packages/main/src/Calendar.js
  packages/main/src/Carousel.js
  packages/main/src/List.js
  packages/main/src/MessageStrip.js
  packages/main/src/Panel.js
  packages/main/src/TabContainer.js
  packages/main/src/Table.js
Labels: for review

#4548 feat(ui5-icon): accessibleRole property implemented
  docs/2-advanced/07-accessibility.md
  packages/main/src/Icon.js
  packages/main/test/pages/Icon.html
  packages/main/test/specs/Icon.spec.js
Labels: SF

#4577 fix(ui5-shellbar): allow selection with Enter key in overflow menu
  packages/base/hash.txt
  packages/fiori/src/ShellBar.js
  packages/fiori/src/ShellBarPopover.hbs
Labels: SF

#4564 feat(ui5-button)!: implement sap_horizon_exp theme
  packages/main/src/themes/Button.css
  packages/main/src/themes/ToggleButton.css
  packages/main/src/themes/base/Button-parameters.css
  packages/main/src/themes/sap_horizon/Button-parameters.css
  packages/main/src/themes/sap_horizon_exp/Button-parameters.css
Labels: for review

#4555 feat(ui5-input, ui5-select, ui5-datepicker, ui5-badge): implement sap…
  packages/main/src/Input.js
  packages/main/src/themes/DatePicker.css
  packages/main/src/themes/Input.css
  packages/main/src/themes/ListItem.css
  packages/main/src/themes/ListItemBase.css
  packages/main/src/themes/PopupsCommon.css
  packages/main/src/themes/ResponsivePopover.css
  packages/main/src/themes/Select.css
  packages/main/src/themes/SelectPopover.css
  packages/main/src/themes/base/DatePicker-parameters.css
  packages/main/src/themes/base/Input-parameters.css
  packages/main/src/themes/base/ListItemBase-parameters.css
  packages/main/src/themes/base/PopupsCommon-parameters.css
  packages/main/src/themes/base/Select-parameters.css
  packages/main/src/themes/sap_horizon/Input-parameters.css
  packages/main/src/themes/sap_horizon_exp/Badge-parameters.css
  packages/main/src/themes/sap_horizon_exp/DatePicker-parameters.css
  packages/main/src/themes/sap_horizon_exp/Input-parameters.css
  packages/main/src/themes/sap_horizon_exp/InputIcon-parameters.css
  packages/main/src/themes/sap_horizon_exp/ListItemBase-parameters.css
  packages/main/src/themes/sap_horizon_exp/PopupsCommon-parameters.css
  packages/main/src/themes/sap_horizon_exp/Select-parameters.css
  packages/main/src/themes/sap_horizon_exp/SelectPopover-parameters.css
  packages/main/src/themes/sap_horizon_exp/parameters-bundle.css
Labels: for review

#4591 feat(ui5-link): accessibilityAttributes property implemented
  packages/main/src/Link.hbs
  packages/main/src/Link.js
  packages/main/src/types/HasPopup.js
  packages/main/test/pages/Link.html
  packages/main/test/pages/styles/Link.css
  packages/main/test/specs/Link.spec.js
Labels: SF

#4604 feat: stable-dom-ref supported for abstract items
  packages/base/hash.txt
  packages/fiori/src/ShellBarItem.js
  packages/fiori/test/pages/ShellBar.html
  packages/fiori/test/specs/ShellBar.spec.js
  packages/main/src/BreadcrumbsItem.js
  packages/main/src/MultiComboBoxItem.js
  packages/main/src/Option.js
  packages/main/src/Tab.js
  packages/main/src/TabSeparator.js
  packages/theming/hash.txt
Labels: for review

#4599 fix(ui5-popover): restrict arrow going out of bounds
  packages/main/src/Popover.js
  packages/main/test/pages/PopoverArrowBounds.html
  packages/main/test/pages/styles/PopoverArrowBounds.css
Labels: SF

#4632 fix: fix ipad recognition
  packages/base/hash.txt
  packages/base/src/Device.js
Labels: for review

#4658 fix(ui5-switch): change switch role to role checkbox
  packages/main/src/Switch.hbs
  packages/main/test/specs/Switch.spec.js
Labels: ACC
