Repository SAP/ui5-webcomponents, pull requests merged in 2022-04, with the labels that each got.

#4993 build: add husky to lint code & cmt msg
  .husky/pre-push
  commitlint.config.js
  package.json
  packages/main/test/specs/Select.spec.js
  yarn.lock
Labels: TOPIC Core

#4980 refactor: optimize lit-html usage for the non-scoping scenario
  packages/base/hash.txt
  packages/base/src/CustomElementsScope.js
  packages/base/src/CustomElementsScopeUtils.js
  packages/base/src/StaticAreaItem.js
  packages/base/src/UI5ElementMetadata.js
  packages/base/src/renderer/LitRenderer.js
  packages/base/src/renderer/executeTemplate.js
  packages/theming/css-vars-usage.json
  packages/theming/hash.txt
  packages/tools/lib/hbs2lit/src/compiler.js
Labels: for review

#4942 fix(form support): fix submit event handling
  packages/base/hash.txt
  packages/main/README.md
  packages/main/src/Button.js
  packages/main/src/ComboBox.js
  packages/main/src/DatePicker.js
  packages/main/src/Input.js
  packages/main/src/MultiComboBox.js
  packages/main/src/features/InputElementsFormSupport.js
Labels: for review, TOPIC Core

#5031 feat(framework): configure default icon collection per theme
  packages/base/hash.txt
  packages/base/src/asset-registries/Icons.js
  packages/base/src/config/Icons.js
  packages/main/bundle.common.js
Labels: TOPIC Core

#5075 chore(deps): bump theming-base-content from 11.1.37 to 11.38
  packages/theming/css-vars-usage.json
  packages/theming/hash.txt
  packages/theming/package.json
  yarn.lock
Labels: dependencies

#5085 refactor: optimize postcss task
  .reuse/dep5
  packages/base/hash.txt
  packages/theming/config/postcss.themes/postcss.config.js
  packages/theming/package.json
  packages/tools/components-package/postcss.themes.js
  packages/tools/lib/copy-and-watch/index.js
  packages/tools/lib/postcss-combine-duplicated-selectors/index.js
  packages/tools/package.json
  yarn.lock
Labels: for review

#5123 chore: upgrade lit-html to 2.2.2
  packages/base/package.json
  yarn.lock
Labels: for review

#5146 chore: parallelize build tasks
  package.json
  packages/base/hash.txt
  packages/theming/hash.txt
  packages/tools/components-package/nps.js
Labels: for review

#5152 refactor: parallelize main/fiori build
  package.json
Labels: for review
