Repository SAP/ui5-webcomponents, pull requests merged in 2022-05, with the labels that each got.

#5160 chore: update OpenUI5 version to 1.101
  packages/base/package.json
  packages/localization/package.json
  packages/localization/src/dates/CalendarDate.js
  packages/localization/src/sap/ui/core/Core.js
  packages/localization/used-modules.txt
  packages/theming/css-vars-usage.json
  packages/tools/package.json
  yarn.lock
Labels: for review

#5170 fix(ui5-color-palette): align buttons to spec
  packages/main/src/ColorPaletteDialog.hbs
  packages/main/src/themes/ColorPalette.css
Labels: SF

#5153 fix: fix passive listeners for mobile
  packages/main/src/Button.js
  packages/main/src/ListItem.js
  packages/main/src/SliderBase.js
  packages/main/src/SplitButton.js
  packages/main/src/TableRow.js
Labels: for review, TOPIC Core

#5188 fix(f6navigation): fix keydown events for all inputs
  packages/base/src/features/F6Navigation.js
Labels: for review, TOPIC Core

#5232 chore: remove the colors require from tools
  packages/tools/lib/copy-and-watch/index.js
Labels: for review

#5246 fix(ui5-calendar): correct header month button text localization
  packages/main/src/Calendar.js
Labels: SF
