Repository SAP/ui5-webcomponents, pull requests merged in 2022-12, with the labels that each got.

#6130 chore: add explicit return type to key related functions
  packages/base/src/Keys.ts
Labels: TOPIC Core

#6115 chore: remove generics for ScrollEnablement
  packages/base/src/delegate/ScrollEnablement.ts
Labels: TOPIC Core

#6072 feat: support decorators for custom elements metadata
  .gitignore
  packages/base/src/UI5Element.ts
  packages/base/src/UI5ElementMetadata.ts
  packages/base/src/decorators/customElement.ts
  packages/base/src/decorators/defaultSlot.ts
  packages/base/src/decorators/event.ts
  packages/base/src/decorators/fastNavigation.ts
  packages/base/src/decorators/languageAware.ts
  packages/base/src/decorators/property.ts
  packages/base/src/decorators/slot.ts
  packages/base/src/decorators/themeAware.ts
  packages/base/src/types.ts
  packages/base/test/assets/Themes.js
  packages/fiori/src/ProductSwitch.ts
  packages/fiori/src/ProductSwitchItem.js
  packages/fiori/src/ProductSwitchItem.ts
  packages/fiori/tsconfig.json
  packages/main/src/Icon.js
  packages/main/src/Icon.ts
  packages/main/src/Label.js
  packages/main/src/Label.ts
  packages/main/src/Label2.ts
  packages/main/src/TableColumn.js
  packages/main/src/TableColumn.ts
  packages/main/src/Title.js
  packages/main/src/Title.ts
  packages/main/tsconfig.json
  packages/tools/components-package/nps.js
  packages/tools/lib/generate-custom-elements-manifest/index.js
  packages/tools/lib/jsdoc/preprocess.js
Labels: TOPIC Core

#6141 chore: use a better regex for types parsing
  packages/fiori/src/types/BarDesign.ts
  packages/main/src/types/BreadcrumbsSeparatorStyle.ts
  packages/main/src/types/TableGrowingMode.ts
  packages/main/src/types/TitleLevel.ts
  packages/main/src/types/ToastPlacement.ts
  packages/tools/lib/jsdoc/preprocess.js
Labels: for review

#6147 feat: add TS types for localization packages
  packages/base/src/UI5Element.ts
  packages/base/src/decorators/customElement.ts
  packages/base/src/decorators/event.ts
  packages/base/src/decorators/fastNavigation.ts
  packages/base/src/decorators/languageAware.ts
  packages/base/src/decorators/property.ts
  packages/base/src/decorators/slot.ts
  packages/base/src/decorators/themeAware.ts
  packages/localization/package.json
  packages/localization/src/DateFormat.js
  packages/localization/src/DateFormat.ts
  packages/localization/src/LocaleData.js
  packages/localization/src/LocaleData.ts
  packages/localization/src/dates/CalendarDate.ts
  packages/localization/src/dates/ExtremeDates.ts
  packages/localization/src/dates/UniversalDate.ts
  packages/localization/src/dates/calculateWeekNumber.ts
  packages/localization/src/dates/convertMonthNumbersToMonthNames.ts
  packages/localization/src/dates/getDaysInMonth.ts
  packages/localization/src/dates/getRoundedTimestamp.ts
  packages/localization/src/dates/getTodayUTCTimestamp.js
  packages/localization/src/dates/getTodayUTCTimestamp.ts
  packages/localization/src/dates/modifyDateBy.ts
  packages/localization/src/dates/transformDateToSecondaryType.ts
  packages/localization/src/features/calendar/Buddhist.ts
  packages/localization/src/features/calendar/Gregorian.ts
  packages/localization/src/features/calendar/Islamic.ts
  packages/localization/src/features/calendar/Japanese.ts
  packages/localization/src/features/calendar/Persian.ts
  packages/localization/src/getCachedLocaleDataInstance.js
  packages/localization/src/getCachedLocaleDataInstance.ts
  packages/localization/src/locale/getLocaleData.ts
  packages/localization/src/sap/base/util/LoaderExtensions.ts
  packages/localization/src/sap/ui/core/Core.ts
  packages/main/src/DateComponentBase.ts
  yarn.lock
Labels: TOPIC Core

#6156 refactor: migrate "theming" to TS
  packages/theming/package-scripts.js
  packages/theming/package.json
  packages/theming/src/Assets-static.ts
  packages/theming/src/Assets.ts
  packages/theming/tsconfig.json
Labels: TOPIC Core

#6163 chore: make TS dev dependency
  package.json
  packages/base/package.json
  packages/fiori/package.json
  packages/icons-business-suite/package.json
  packages/icons-tnt/package.json
  packages/icons/package.json
  packages/localization/package.json
  packages/main/package.json
  packages/theming/package.json
  yarn.lock
Labels: TOPIC Core

#6160 chore: correct openui5 imports after upgrade to 1.109
  packages/base/package.json
  packages/localization/src/sap/ui/core/Configuration.ts
  packages/localization/src/sap/ui/core/Core.ts
  packages/localization/src/sap/ui/core/FormatSettings.ts
  packages/localization/used-modules.txt
  packages/main/src/TimeSelection.js
  packages/tools/lib/copy-list/index.js
  yarn.lock
Labels: TOPIC Core

#6172 chore(deps): update playground dependencies list
  packages/playground/Gemfile.lock
Labels: dependencies, TOPIC Core, ruby

#6180 chore(deps): update playground dependencies
  packages/playground/Gemfile.lock
  packages/playground/just-the-docs.gemspec
  packages/playground/package.json
Labels: dependencies, TOPIC Core

#6188 chore: bump theming-base-content to v11.1.48
  packages/theming/package.json
  yarn.lock
Labels: dependencies

#6195 feat: migrate illustrated-message component to TS, small refactor
  packages/base/src/asset-registries/Illustrations.ts
  packages/fiori/src/IllustratedMessage.js
  packages/fiori/src/IllustratedMessage.ts
  packages/fiori/src/themes/IllustratedMessage.css
  packages/fiori/test/specs/IllustratedMessage.spec.js
  packages/tools/components-package/wdio.js
Labels: TOPIC Core

#6194 refactor(ui5-bar, ui5-upload-collection): migrate to TS
  packages/fiori/src/Assets-static.ts
  packages/fiori/src/Assets.ts
  packages/fiori/src/Bar.ts
  packages/fiori/src/UploadCollection.js
  packages/fiori/src/UploadCollection.ts
  packages/fiori/src/features/CoPilotAnimation.ts
  packages/fiori/src/illustrations/AllIllustrations.ts
  packages/fiori/src/upload-utils/UploadCollectionBodyDnD.ts
Labels: TOPIC Core

#6173 feat(ui5-button, ui5-date-picker, ui5-calendar): migrate to TS
  packages/base/src/UI5ElementMetadata.ts
  packages/base/src/util/isDefaultSlotProvided.ts
  packages/base/src/util/willShowContent.ts
  packages/fiori/src/ProductSwitch.ts
  packages/fiori/src/ProductSwitchItem.ts
  packages/localization/src/dates/CalendarDate.ts
  packages/localization/src/dates/UniversalDate.ts
  packages/localization/src/dates/calculateWeekNumber.ts
  packages/localization/src/dates/convertMonthNumbersToMonthNames.ts
  packages/localization/src/dates/transformDateToSecondaryType.ts
  packages/main/src/Badge.js
  packages/main/src/Button.js
  packages/main/src/Button.ts
  packages/main/src/Calendar.ts
  packages/main/src/CalendarDate.ts
  packages/main/src/CalendarHeader.js
  packages/main/src/CalendarHeader.ts
  packages/main/src/CalendarPart.ts
  packages/main/src/DateComponentBase.ts
  packages/main/src/DatePicker.ts
  packages/main/src/DayPicker.ts
  packages/main/src/FileUploader.js
  packages/main/src/MonthPicker.ts
  packages/main/src/YearPicker.ts
  packages/main/src/features/InputElementsFormSupport.ts
  packages/tools/lib/jsdoc/preprocess.js
Labels: TOPIC B, TOPIC Core

#6201 refactor(ui5-progress-indicator): migrate to TS
  packages/main/src/ProgressIndicator.ts
Labels: TOPIC P, TOPIC Core

#6202 refactor(ui5-panel): migrate to TS
  packages/main/src/Panel.ts
Labels: TOPIC RL, TOPIC Core

#6205 refactor(ui5-page): migrate to TS
  packages/fiori/src/Page.ts
Labels: TOPIC RL, TOPIC Core

#6204 refactor(ui5-link): migrate to TS
  packages/main/src/Link.hbs
  packages/main/src/Link.js
  packages/main/src/Link.ts
Labels: TOPIC B, TOPIC Core

#6206 refactor(ui5-timeline-*): migrate to TS
  packages/fiori/src/Timeline.ts
  packages/fiori/src/TimelineItem.js
  packages/fiori/src/TimelineItem.ts
Labels: TOPIC B, TOPIC Core

#6209 refactor(ui5-dynamic-side-content): migrate to TS
  packages/fiori/src/DynamicSideContent.ts
Labels: TOPIC B, TOPIC Core

#6211 refactor(ui5-file-uploader): migrate to TS
  packages/main/src/FileUploader.js
  packages/main/src/FileUploader.ts
  packages/main/src/features/InputElementsFormSupport.ts
Labels: TOPIC B, TOPIC Core

#6210 refactor(ui5-switch): migrate to TS
  packages/main/src/Switch.hbs
  packages/main/src/Switch.js
  packages/main/src/Switch.ts
Labels: TOPIC B, TOPIC Core
