Repository SAP/ui5-webcomponents, pull requests merged in 2022-03, with the labels that each got.

#4866 fix(ui5-date-picker): remove aria-expanded attribute
  packages/main/src/DatePicker.js
  packages/main/src/TimePicker.js
  packages/main/test/specs/DatePicker.spec.js
Labels: ACC

#4905 fix(localization): fix JS error upon "sh" locale set
  packages/base/hash.txt
  packages/base/src/asset-registries/LocaleData.js
  packages/localization/hash.txt
  packages/tools/assets-meta.js
Labels: SF

#4921 feat(ui5-select): add aria-roledescription attribute
  packages/main/src/Select.hbs
  packages/main/src/Select.js
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/specs/Select.spec.js
Labels: SF

#4919 fix(ui5-flexible-column-layout): correct column border styles for RTL
  packages/fiori/src/FlexibleColumnLayout.hbs
  packages/fiori/src/themes/FlexibleColumnLayout.css
Labels: SF

#4934 fix(framework): add more 72-* fonts as system styles
  packages/base/hash.txt
  packages/base/src/css/FontFace.css
Labels: SF

#4948 fix(playground): fix search results
  packages/playground/_sass/layout.scss
  packages/playground/_sass/search.scss
  packages/playground/assets/js/playground.js
  packages/theming/hash.txt
Labels: for review

#4952 fix(framework): fix scoping of self tag
  packages/base/src/renderer/executeTemplate.js
Labels: SF, TOPIC Core
