Repository SAP/ui5-webcomponents, pull requests merged in 2022-08, with the labels that each got.

#5609 feat(ui5-popover): new type DOMReference for opener
  packages/base/src/UI5Element.js
  packages/base/src/types/DOMReference.js
  packages/main/src/Popover.js
Labels: for review

#5705 refactor(ui5-card-header): add new CSS Shadow part
  packages/main/src/CardHeader.hbs
  packages/main/src/CardHeader.js
Labels: TOPIC RD, MDK

#5706 fix(ui5-li-notification): align actions' texts to the left
  packages/fiori/src/NotificationOverflowActionsPopover.hbs
  packages/fiori/src/themes/NotificationOverflowActionsPopover.css
  packages/fiori/test/pages/NotificationListItem.html
Labels: TOPIC RD, MDK

#5726 fix(ui5-list): unexpected spaces between group items
  packages/main/src/themes/GroupHeaderListItem.css
Labels: TOPIC P

#5750 fix(ui5-button): correct text shadow in contrast themes
  packages/main/src/themes/sap_belize_hcb/Button-parameters.css
  packages/main/src/themes/sap_belize_hcw/Button-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/Button-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/Button-parameters.css
Labels: SF
