Repository SAP/ui5-webcomponents, pull requests merged in 2022-06, with the labels that each got.

#5133 fix(formEnablement): enable required attribute
  packages/main/src/features/InputElementsFormSupport.js
  packages/main/test/pages/form.html
Labels: for review, TOPIC Core

#5298 chore: fix import of theming assets in codesandbox
  packages/tools/lib/generate-json-imports/themes.js
Labels: TOPIC Core

#5424 fix(f6navigation): prevent default behavior on windows OS
  packages/base/src/features/F6Navigation.js
  packages/fiori/test/pages/F6TestPage.html
Labels: SF
