Repository SAP/ui5-webcomponents, pull requests merged in 2023-03, with the labels that each got.

#6615 refactor: deprecate decoratorMetadata in favor of metadata
  packages/base/src/UI5Element.ts
  packages/base/src/decorators/customElement.ts
  packages/base/src/decorators/event.ts
  packages/base/src/decorators/fastNavigation.ts
  packages/base/src/decorators/languageAware.ts
  packages/base/src/decorators/property.ts
  packages/base/src/decorators/slot.ts
  packages/base/src/decorators/themeAware.ts
Labels: for review

#6616 fix(framework): fix boot, interfering theme load
  packages/base/src/Boot.ts
  packages/base/test/assets/bundle.light.js
  packages/base/test/assets/styles/Boot.css
  packages/base/test/pages/Boot.html
  packages/base/test/specs/Boot.spec.js
Labels: TOPIC Core

#6609 feat: enhance create-ui5-element command to create component in TS
  packages/tools/lib/create-new-component/index.js
  packages/tools/lib/create-new-component/jsFileContentTemplate.js
  packages/tools/lib/create-new-component/tsFileContentTemplate.js
Labels: TOPIC Core

#6654 refactor: use new `customElement` notation in `fiori` components
  docs/5-development/07-ts.md
  packages/base/src/decorators/fastNavigation.ts
  packages/base/src/decorators/languageAware.ts
  packages/base/src/decorators/themeAware.ts
  packages/create-package/template/src/MyFirstComponent.ts
  packages/fiori/src/Bar.ts
  packages/fiori/src/BarcodeScannerDialog.ts
  packages/fiori/src/DynamicSideContent.ts
  packages/fiori/src/FlexibleColumnLayout.ts
  packages/fiori/src/IllustratedMessage.ts
  packages/fiori/src/MediaGallery.ts
  packages/fiori/src/MediaGalleryItem.ts
  packages/fiori/src/NotificationListGroupItem.ts
  packages/fiori/src/NotificationListItem.ts
  packages/fiori/src/NotificationListItemBase.ts
  packages/fiori/src/Page.ts
  packages/fiori/src/ProductSwitch.ts
  packages/fiori/src/ProductSwitchItem.ts
  packages/fiori/src/SideNavigation.ts
  packages/fiori/src/Timeline.ts
  packages/fiori/src/TimelineItem.ts
  packages/fiori/src/UploadCollection.ts
  packages/fiori/src/UploadCollectionItem.ts
  packages/fiori/src/ViewSettingsDialog.ts
  packages/fiori/src/Wizard.ts
  packages/fiori/src/WizardTab.ts
Labels: TOPIC Core

#6584 fix(ui5-icon): aria-label change
  packages/main/src/Icon.ts
  packages/main/test/pages/Icon.html
  packages/main/test/specs/Icon.spec.js
Labels: TOPIC P

#6725 fix: fix eslint for JS 3rd party projects
  packages/base/package-scripts.js
  packages/localization/package-scripts.js
  packages/tools/components-package/eslint.js
  packages/tools/components-package/nps.js
Labels: TOPIC Core

#6718 fix(framework): apply theme after every theme props registration
  packages/base/src/Boot.ts
  packages/base/src/asset-registries/Themes.ts
  packages/base/src/theming/ThemeRegistered.ts
  packages/base/test/assets/bundle.light.js
  packages/base/test/assets/styles/Boot.css
  packages/base/test/pages/Boot.html
  packages/base/test/specs/Boot.spec.js
Labels: TOPIC Core

#6727 chore: improve icon types
  packages/base/src/asset-registries/Icons.ts
  packages/main/bundle.common.js
  packages/main/src/Icon.ts
Labels: for review

#6732 fix: inline sources in the .map file so the src folder is not mandatory
  packages/base/.npmignore
  packages/base/tsconfig.json
  packages/create-package/template/tsconfig.json
  packages/fiori/.npmignore
  packages/fiori/tsconfig.json
  packages/icons-business-suite/tsconfig.json
  packages/icons-tnt/tsconfig.json
  packages/icons/tsconfig.json
  packages/localization/.npmignore
  packages/localization/tsconfig.json
  packages/main/.npmignore
  packages/main/tsconfig.json
  packages/playground/tsconfig.json
  packages/theming/tsconfig.json
Labels: TOPIC Core

#6754 feat(icons): add/update icons
  packages/icons/src/v4/SAP-icons.json
  packages/icons/src/v5/SAP-icons.json
Labels: TOPIC Core

#6682 docs: add Typescript support information
  README.md
  docs/1-getting-started/06-using-features.md
  docs/1-getting-started/07-typescript-support.md
  docs/1-getting-started/08-wrapping-up.md
  docs/5-development/06-deep-dive-and-best-practices.md
  docs/5-development/07-typescript-in-UI5-Web-Components.md
Labels: documentation, TOPIC Core

#6755 feat(icons-business-suite): update icons
  packages/icons-business-suite/src/v1/SAP-icons-business-suite.json
  packages/icons-business-suite/src/v2/SAP-icons-business-suite.json
Labels: TOPIC Core

#6815 fix(theming): fix icons version detection for custom theme (built via the ThemeDesigner)
  packages/base/lib/generate-asset-parameters/index.js
  packages/base/src/config/Icons.ts
  packages/base/src/config/Theme.ts
  packages/base/src/global.d.ts
  packages/main/bundle.common.js
  packages/main/test/pages/base/IconCollection.html
  packages/main/test/pages/base/IconCollectionInCustomTheme.html
  packages/main/test/pages/css/css_variables.horizon.css
  packages/main/test/specs/base/IconCollection.spec.js
  packages/tools/lib/create-icons/index.js
Labels: TOPIC Core
