Repository SAP/ui5-webcomponents, pull requests merged in 2024-12, with the labels that each got.

#10255 fix(ui5-dialog): width on mobile is not bigger than the phone width
  packages/main/src/Dialog.ts
  packages/main/src/themes/Dialog.css
Labels: 1.24, downport

#10305 chore(ui5-color-picker): rename displayMode to simplified
  packages/main/cypress/specs/ColorPicker.cy.ts
  packages/main/src/ColorPicker.ts
  packages/main/src/types/ColorPickerDisplayMode.ts
  packages/main/test/pages/ColorPicker.html
  packages/website/docs/_samples/main/ColorPicker/Simplified/sample.html
Labels: for review

#10316 fix(ui5-popover): fix arrow position in RTL direction
  packages/main/src/Popover.ts
  packages/main/src/themes/base/rtl-parameters.css
  packages/main/test/pages/Popover.html
  packages/main/test/pages/PopoverRTL.html
  packages/main/test/pages/styles/Popover.css
Labels: 1.24, downport

#10368 chore: remove StyleDataCSP and change StyleData / ThemeData to string
  packages/base/cypress/specs/Boot.cy.ts
  packages/base/lib/generate-styles/index.js
  packages/base/src/ManagedStyles.ts
  packages/base/src/asset-registries/Themes.ts
  packages/base/src/theming/getStylesString.ts
  packages/base/src/types.ts
  packages/base/test/assets/Themes.ts
  packages/main/src/TabContainer.ts
  packages/tools/lib/css-processors/css-processor-components.mjs
  packages/tools/lib/css-processors/css-processor-themes.mjs
  packages/tools/lib/css-processors/shared.mjs
Labels: for review

#10428 fix(ui5-popover): revert rtl correction fix
  packages/main/src/Popover.ts
Labels: 1.24
