Repository SAP/ui5-webcomponents, pull requests merged in 2024-08, with the labels that each got.

#9609 fix(ui5-date-picker): adjust timestamp
  packages/main/src/DatePicker.ts
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/DateTimePickerPopover.hbs
  packages/main/test/specs/DatePicker.spec.js
Labels: 1.24, downport

#9407 feat(ui5-timeline-group-item): introduce new component
  packages/fiori/src/Timeline.ts
  packages/fiori/src/TimelineGroupItem.hbs
  packages/fiori/src/TimelineGroupItem.ts
  packages/fiori/src/TimelineItem.hbs
  packages/fiori/src/TimelineItem.ts
  packages/fiori/src/themes/Timeline.css
  packages/fiori/src/themes/TimelineGroupItem.css
  packages/fiori/src/themes/TimelineItem.css
  packages/fiori/src/themes/base/TimelineGroupItem-parameters.css
  packages/fiori/src/themes/sap_fiori_3/TimelineGroupItem-parameters.css
  packages/fiori/src/themes/sap_fiori_3/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/fiori/src/themes/sap_fiori_3_hcw/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon_dark/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon_dark_exp/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon_exp/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon_hcb/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon_hcb_exp/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon_hcw/parameters-bundle.css
  packages/fiori/src/themes/sap_horizon_hcw_exp/parameters-bundle.css
  packages/fiori/test/pages/Timeline.html
  packages/fiori/test/specs/Timeline.spec.js
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3_dark/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/sizes-parameters.css
  packages/website/docs/_components_pages/fiori/Timeline/Timeline.mdx
  packages/website/docs/_components_pages/fiori/Timeline/TimelineGroupItem.mdx
  packages/website/docs/_samples/fiori/Timeline/WithGroups/WithGroups.md
  packages/website/docs/_samples/fiori/Timeline/WithGroups/main.js
  packages/website/docs/_samples/fiori/Timeline/WithGroups/sample.html
Labels: New Component, for review

#9629 fix(ui5-shellbar): remove aria attribute from search button
  packages/fiori/src/ShellBar.ts
Labels: 1.24, downport

#9574 fix(ui5-menu): provide accessible name to the popover
  packages/main/src/Menu.hbs
  packages/main/src/Menu.ts
  packages/main/src/MenuItem.hbs
  packages/main/src/MenuItem.ts
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/specs/Menu.cy.js
Labels: SF_ACC

#9628 feat(ui5-dialog): increase resize handle size
  packages/main/src/Dialog.hbs
  packages/main/src/themes/Dialog.css
  packages/main/src/themes/base/Dialog-parameters.css
  packages/main/src/themes/sap_horizon/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_dark/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_dark_exp/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_exp/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_hcb/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_hcb_exp/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_hcb_exp/parameters-bundle.css
  packages/main/src/themes/sap_horizon_hcw/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_hcw_exp/Dialog-parameters.css
  packages/main/src/themes/sap_horizon_hcw_exp/parameters-bundle.css
Labels: ACC WCAG 2.2

#9644 fix(ui5-split-button): provide aria attributes for the arrow button (…
  packages/main/src/SplitButton.hbs
  packages/main/src/SplitButton.ts
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/pages/SplitButton.html
  packages/main/test/specs/SplitButton.spec.js
Labels: 1.24, downport

#9582 chore: add quick prompt pattern sample for `<ui5-ai-button>`
  packages/ai/src/Button.hbs
  packages/ai/test/pages/Button.html
  packages/ai/test/pages/js/Button.js
  packages/ai/test/pages/styles/Button.css
  packages/website/docs/components/patterns/AI QuickPrompt.mdx
  packages/website/docs/components/patterns/AI QuickPrompt/AI QuickPrompt.md
  packages/website/docs/components/patterns/AI QuickPrompt/main.css
  packages/website/docs/components/patterns/AI QuickPrompt/main.js
  packages/website/docs/components/patterns/AI QuickPrompt/sample.html
  packages/website/static/data/predefinedTexts.json
Labels: for review

#9524 fix(ui5-special-date): add visual representation for Working/NonWorking types
  packages/main/src/Calendar.ts
  packages/main/src/DayPicker.ts
  packages/main/src/themes/DayPicker.css
  packages/main/test/pages/CalendarLegend.html
  packages/main/test/specs/CalendarLegend.spec.js
  packages/website/docs/_samples/main/Calendar/CalendarWithLegend/main.js
  packages/website/docs/_samples/main/Calendar/CalendarWithLegend/sample.html
  packages/website/docs/_samples/main/CalendarLegend/Basic/main.js
  packages/website/docs/_samples/main/CalendarLegend/Basic/sample.html
Labels: for review

#9676 fix(ui5-special-date): add visual representation for Working/NonWorking types
  packages/main/src/Calendar.ts
  packages/main/src/DayPicker.ts
  packages/main/src/themes/DayPicker.css
  packages/main/test/pages/Calendar.html
  packages/main/test/pages/CalendarLegend.html
  packages/main/test/specs/Calendar.spec.js
  packages/main/test/specs/CalendarLegend.spec.js
  packages/website/docs/_samples/main/Calendar/CalendarWithLegend/main.js
  packages/website/docs/_samples/main/Calendar/CalendarWithLegend/sample.html
  packages/website/docs/_samples/main/CalendarLegend/Basic/main.js
  packages/website/docs/_samples/main/CalendarLegend/Basic/sample.html
Labels: 1.24, downport

#9661 fix(ui5-split-button): adjust arrow part width
  packages/main/src/themes/SplitButton.css
Labels: 1.24, downport

#9734 fix(ui5-calendar): adjust aria-disabled attribute (#9732)
  packages/main/src/DayPicker.ts
  packages/main/src/MonthPicker.hbs
  packages/main/src/MonthPicker.ts
  packages/main/src/YearPicker.hbs
  packages/main/src/YearPicker.ts
Labels: 1.24, downport
