Repository SAP/ui5-webcomponents, pull requests merged in 2024-04, with the labels that each got.

#8596 refactor(ui5-popover): rename property placementType to placement
  packages/fiori/src/NotificationOverflowActionsPopover.hbs
  packages/fiori/src/ShellBarPopover.hbs
  packages/fiori/src/WizardPopover.hbs
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/pages/ShellBar.html
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
  packages/fiori/test/samples/ProductSwitch.sample.html
  packages/fiori/test/samples/ShellBar.sample.html
  packages/main/src/BreadcrumbsPopover.hbs
  packages/main/src/ColorPalettePopover.hbs
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/FileUploaderPopover.hbs
  packages/main/src/InputPopover.hbs
  packages/main/src/Menu.hbs
  packages/main/src/Menu.ts
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/Popover.ts
  packages/main/src/SelectMenu.hbs
  packages/main/src/SelectPopover.hbs
  packages/main/src/TabContainerPopover.hbs
  packages/main/src/TextAreaPopover.hbs
  packages/main/src/TimePickerPopover.hbs
  packages/main/src/TokenizerPopover.hbs
  packages/main/src/Toolbar.ts
  packages/main/src/ToolbarPopover.hbs
  packages/main/src/themes/Menu.css
  packages/main/src/themes/Popover.css
  packages/main/src/types/PopoverPlacement.ts
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/pages/Dialog.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/pages/Popover.html
  packages/main/test/pages/PopoverArrowBounds.html
  packages/main/test/pages/Popups.html
  packages/main/test/pages/ResponsivePopover.html
  packages/main/test/samples/AvatarGroup.sample.html
  packages/playground/_stories/fiori/NotificationListGroupItem/NotificationListGroupItem.stories.ts
  packages/playground/_stories/fiori/NotificationListItem/NotificationListItem.stories.ts
  packages/playground/_stories/fiori/ProductSwitch/ProductSwitch.stories.ts
  packages/playground/_stories/fiori/ShellBar/ShellBar.stories.ts
  packages/playground/_stories/main/AvatarGroup/TemplateGroupWithPopover.ts
  packages/playground/_stories/main/AvatarGroup/TemplateIndividualWithPopover.ts
  packages/playground/_stories/main/Popover/Popover.stories.ts
  packages/playground/_stories/main/ResponsivePopover/ResponsivePopover.stories.ts
  packages/website/docs/_samples/fiori/NotificationListGroupItem/InShellBar/sample.html
  packages/website/docs/_samples/fiori/NotificationListItem/InShellBar/sample.html
  packages/website/docs/_samples/fiori/ProductSwitch/WithShellBar/sample.html
  packages/website/docs/_samples/fiori/ShellBar/Advanced/sample.html
  packages/website/docs/_samples/main/AvatarGroup/GroupWithPopover/sample.html
  packages/website/docs/_samples/main/AvatarGroup/IndividualWithPopover/sample.html
  packages/website/docs/_samples/main/Popover/Placement/sample.html
  packages/website/docs/_samples/main/ResponsivePopover/Placement/sample.html
Labels: BREAKING CHANGE, 2.0

#8605 refactor(ui5-illustrated-message): rename `size` property to `design`
  packages/fiori/src/IllustratedMessage.ts
  packages/fiori/test/pages/IllustratedMessage.html
  packages/fiori/test/specs/IllustratedMessage.spec.js
  packages/playground/_stories/fiori/IllustratedMessage/IllustratedMessage.stories.ts
Labels: BREAKING CHANGE, 2.0

#8600 refactor(ui5-breadcrumbs): rename property separator-style to separators
  packages/main/src/Breadcrumbs.ts
  packages/main/src/themes/Breadcrumbs.css
  packages/main/src/types/BreadcrumbsSeparator.ts
  packages/main/test/pages/Breadcrumbs.html
  packages/main/test/samples/Breadcrumbs.sample.html
  packages/playground/_stories/main/Breadcrumbs/Breadcrumbs.stories.ts
  packages/website/docs/_samples/main/Breadcrumbs/BreadcrumbsStyles/sample.html
Labels: BREAKING CHANGE, 2.0

#8593 refactor(ui5-tabcontainer): delete ITab interface
  packages/main/src/Tab.ts
  packages/main/src/TabContainer.ts
  packages/main/src/TabInOverflow.hbs
  packages/main/src/TabInStrip.hbs
  packages/main/src/TabSeparator.ts
  packages/main/src/TabSeparatorInOverflow.hbs
Labels: BREAKING CHANGE, 2.0

#8647 fix(ui5-popup): handle multiple _open calls
  packages/main/src/Popup.ts
  packages/main/test/specs/Popover.spec.js
Labels: 2.0

#8653 refactor(ui5-tab, ui5-tab-separator): rename getTabInStripDomRef to getDomRefInStrip
  packages/main/src/Tab.ts
  packages/main/src/TabContainer.ts
  packages/main/src/TabSeparator.ts
  packages/main/test/specs/TabContainer.spec.js
Labels: BREAKING CHANGE, 2.0

#8657 refactor(ui5-list, ui5-tree, ui5-upload-collection): rename mode to selectionMode
  packages/fiori/src/ShellBarPopover.hbs
  packages/fiori/src/UploadCollection.hbs
  packages/fiori/src/UploadCollection.ts
  packages/fiori/src/ViewSettingsDialog.hbs
  packages/fiori/test/pages/F6TestPage.html
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/UploadCollection.html
  packages/fiori/test/pages/uploadCollectionScript.js
  packages/fiori/test/specs/UploadCollection.spec.js
  packages/main/src/BreadcrumbsPopover.hbs
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/InputPopover.hbs
  packages/main/src/List.ts
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.ts
  packages/main/src/Menu.hbs
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/NavigationMenu.hbs
  packages/main/src/SelectMenu.hbs
  packages/main/src/SelectPopover.hbs
  packages/main/src/TabContainerPopover.hbs
  packages/main/src/TokenizerPopover.hbs
  packages/main/src/Tree.hbs
  packages/main/src/Tree.ts
  packages/main/src/TreeItemBase.ts
  packages/main/src/themes/ListItem.css
  packages/main/src/themes/TreeItem.css
  packages/main/src/types/ListSelectionMode.ts
  packages/main/test/pages/Carousel.html
  packages/main/test/pages/Dialog.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/List.html
  packages/main/test/pages/List_keyboard_support.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/pages/Popups.html
  packages/main/test/pages/Tree.html
  packages/main/test/pages/TreeDynamic.html
  packages/main/test/specs/List.spec.js
  packages/main/test/specs/Tree.spec.js
  packages/playground/_stories/fiori/FlexibleColumnLayout/FlexibleColumnLayout.stories.ts
  packages/playground/_stories/fiori/UploadCollection/UploadCollection.stories.ts
  packages/playground/_stories/main/List/List.stories.ts
  packages/playground/_stories/main/Panel/Panel.stories.ts
  packages/playground/_stories/main/Tree/Tree.stories.ts
  packages/website/docs/_components_pages/main/List/List.mdx
  packages/website/docs/_samples/fiori/FlexibleColumnLayout/Basic/sample.html
  packages/website/docs/_samples/fiori/UploadCollection/Basic/sample.html
  packages/website/docs/_samples/main/List/GroupHeaders/sample.html
  packages/website/docs/_samples/main/List/Modes/sample.html
  packages/website/docs/_samples/main/List/NoData/sample.html
Labels: BREAKING CHANGE, 2.0

#8679 chore(tools): Re-enable the JS build as "legacy"
  packages/base/package-scripts.cjs
  packages/icons-tnt/package-scripts.cjs
  packages/icons/package-scripts.cjs
  packages/theming/package-scripts.cjs
  packages/tools/components-package/nps.js
  packages/tools/icons-collection/nps.js
  packages/tools/lib/css-processors/css-processor-components.mjs
  packages/tools/lib/css-processors/css-processor-themes.mjs
  packages/tools/lib/css-processors/shared.mjs
  packages/tools/lib/generate-json-imports/i18n.js
  packages/tools/lib/generate-json-imports/themes.js
  packages/tools/lib/hbs2lit/src/compiler.js
  packages/tools/lib/hbs2lit/src/litVisitor2.js
  packages/tools/lib/hbs2lit/src/svgProcessor.js
  packages/tools/lib/hbs2ui5/RenderTemplates/LitRenderer.js
  packages/tools/lib/hbs2ui5/index.js
  packages/tools/lib/i18n/defaults.js
Labels: 2.0

#8607 refactor(ui5-upload-collection): remove Delete selection mode
  packages/fiori/src/UploadCollection.ts
  packages/fiori/src/UploadCollectionItem.hbs
  packages/fiori/src/UploadCollectionItem.ts
  packages/fiori/src/themes/UploadCollectionItem.css
  packages/fiori/src/types/UploadCollectionSelectionMode.ts
  packages/fiori/test/pages/UploadCollection.html
  packages/fiori/test/specs/UploadCollection.spec.js
  packages/playground/_stories/fiori/UploadCollection/UploadCollection.stories.ts
  packages/website/docs/_samples/fiori/UploadCollection/Basic/sample.html
Labels: BREAKING CHANGE, 2.0

#8676 refactor(ui5-tabcontainer): remove fixed property
  packages/fiori/test/pages/F6TestPage.html
  packages/fiori/test/pages/FCL.html
  packages/main/src/TabContainer.ts
  packages/main/test/pages/TabContainer.html
  packages/main/test/pages/TabContainerDragAndDrop.html
  packages/playground/_stories/main/TabContainer/TabContainer.stories.ts
  packages/website/docs/_samples/fiori/FlexibleColumnLayout/Basic/sample.html
  packages/website/docs/_samples/main/TabContainer/OverflowMode/sample.html
  packages/website/docs/_samples/main/TabContainer/TabLayout/sample.html
Labels: BREAKING CHANGE, 2.0

#8683 refactor(ui5-progress-indicator): remove disabled property
  packages/main/src/ProgressIndicator.hbs
  packages/main/src/ProgressIndicator.ts
  packages/main/src/themes/ProgressIndicator.css
  packages/main/test/pages/ProgressIndicator.html
  packages/playground/_stories/main/ProgressIndicator/ProgressIndicator.stories.ts
  packages/website/docs/_components_pages/main/ProgressIndicator.mdx
  packages/website/docs/_samples/main/ProgressIndicator/States/sample.html
Labels: BREAKING CHANGE, 2.0

#8686 refactor(ui5-list): renamed busy, busyDelay to loading, loadingDelay
  packages/main/src/List.hbs
  packages/main/src/List.ts
  packages/main/src/themes/List.css
  packages/main/test/pages/List.html
  packages/main/test/specs/List.spec.js
  packages/playground/_stories/main/List/List.stories.ts
  packages/website/docs/_samples/main/List/Growing/main.js
  packages/website/docs/_samples/main/List/Growing/sample.html
  packages/website/docs/_samples/main/List/GrowingOnButtonPress/main.js
  packages/website/docs/_samples/main/List/GrowingOnButtonPress/sample.html
Labels: BREAKING CHANGE, 2.0

#8684 refactor(ui5-side-navigation): renamed title property
  packages/fiori/src/SideNavigationItemBase.ts
  packages/fiori/src/SideNavigationPopover.hbs
  packages/fiori/test/pages/SideNavigation.html
  packages/fiori/test/specs/SideNavigation.spec.js
Labels: enhancement, 2.0

#8299 feat: introduce Text web component
  packages/main/src/Text.ts
  packages/main/src/bundle.esm.ts
  packages/main/src/themes/Text.css
  packages/main/src/themes/base/Text-parameters.css
  packages/main/src/themes/sap_belize/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
  packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
  packages/main/src/themes/sap_horizon/parameters-bundle.css
  packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
  packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css
  packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
  packages/main/test/pages/Text.html
  packages/website/docs/_components_pages/main/Text.mdx
  packages/website/docs/_samples/main/Text/Basic/Basic.md
  packages/website/docs/_samples/main/Text/Basic/main.js
  packages/website/docs/_samples/main/Text/Basic/sample.html
  packages/website/docs/_samples/main/Text/CustomStyling/CustomStyling.md
  packages/website/docs/_samples/main/Text/CustomStyling/main.js
  packages/website/docs/_samples/main/Text/CustomStyling/sample.html
  packages/website/docs/_samples/main/Text/MaxLines/MaxLines.md
  packages/website/docs/_samples/main/Text/MaxLines/main.js
  packages/website/docs/_samples/main/Text/MaxLines/sample.html
  packages/website/src/css/custom.css
Labels: New Component, 2.0

#8704 refactor(ui5-menu): rename open and close events
  packages/main/src/Menu.ts
  packages/main/test/pages/Menu.html
  packages/main/test/specs/Menu.spec.js
Labels: BREAKING CHANGE, 2.0

#8610 feat(ui5-date-*): adapt date and time controls to timezone feature
  docs/2-advanced/01-configuration.md
  packages/main/src/Calendar.ts
  packages/main/src/CalendarPart.ts
  packages/main/src/DateComponentBase.ts
  packages/main/src/DateTimePicker.ts
  packages/main/src/DayPicker.ts
  packages/main/src/TimePickerBase.ts
  packages/main/src/TimePickerInternals.ts
  packages/main/src/TimeSelection.ts
  packages/main/test/pages/DateControlsWithTimezone.html
  packages/main/test/specs/DateControlsWithTimezone.spec.js
  packages/website/docs/_components_pages/main/Calendar/Calendar.mdx
  packages/website/docs/_components_pages/main/DatePicker.mdx
  packages/website/docs/_components_pages/main/DateTimePicker.mdx
  packages/website/docs/_components_pages/main/TimePicker.mdx
  packages/website/docs/_samples/main/Calendar/CalendarInDifferentTimezone/CalendarInDifferentTimezone.md
  packages/website/docs/_samples/main/Calendar/CalendarInDifferentTimezone/main.js
  packages/website/docs/_samples/main/Calendar/CalendarInDifferentTimezone/sample.html
  packages/website/docs/_samples/main/DatePicker/DatePickerInDifferentTimezone/DatePickerInDifferentTimezone.md
  packages/website/docs/_samples/main/DatePicker/DatePickerInDifferentTimezone/main.js
  packages/website/docs/_samples/main/DatePicker/DatePickerInDifferentTimezone/sample.html
  packages/website/docs/_samples/main/DateTimePicker/DateTimePickerInDifferentTimezone/DateTimePickerInDifferentTimezone.md
  packages/website/docs/_samples/main/DateTimePicker/DateTimePickerInDifferentTimezone/main.js
  packages/website/docs/_samples/main/DateTimePicker/DateTimePickerInDifferentTimezone/sample.html
  packages/website/docs/_samples/main/TimePicker/TimePickerInDifferentTimezone/TimePickerInDifferentTimezone.md
  packages/website/docs/_samples/main/TimePicker/TimePickerInDifferentTimezone/main.js
  packages/website/docs/_samples/main/TimePicker/TimePickerInDifferentTimezone/sample.html
Labels: enhancement, 2.0

#8711 refactor(ui5-combobox): remove firing of change event on navigation
  packages/main/src/ComboBox.ts
  packages/main/test/specs/ComboBox.spec.js
Labels: BREAKING CHANGE, 2.0

#8756 refactor(ui5-textarea): rename property growingMaxLines to growingMaxRows
  packages/main/src/TextArea.ts
  packages/main/src/themes/TextArea.css
  packages/main/test/pages/TextArea.html
  packages/main/test/specs/TextArea.spec.js
  packages/playground/_stories/main/TextArea/TextArea.stories.ts
  packages/website/docs/_samples/main/TextArea/Growing/sample.html
Labels: BREAKING CHANGE, 2.0

#8670 feat(ui5-link): introduce `tooltip` property
  docs/2-advanced/07-accessibility.md
  packages/main/src/Link.hbs
  packages/main/src/Link.ts
  packages/main/test/pages/Link.html
  packages/main/test/specs/Link.spec.js
Labels: enhancement, ACC, 2.0

#8765 refactor(ui5-multi-combobox): rename property allowCustomValues to noValidation
  packages/main/src/MultiComboBox.ts
  packages/main/test/pages/MultiComboBox.html
  packages/playground/_stories/main/MultiComboBox/MultiComboBox.stories.ts
  packages/website/docs/_components_pages/main/MultiComboBox/MultiComboBox.mdx
  packages/website/docs/_samples/main/MultiComboBox/ClearIcon/sample.html
  packages/website/docs/_samples/main/MultiComboBox/MultiComboBoxCustomValue/sample.html
Labels: BREAKING CHANGE, 2.0

#8601 refactor(ui5-badge): change default values of properties
  docs/5-development/05-testing-UI5-Web-Components.md
  packages/main/src/Badge.ts
  packages/main/src/themes/Badge.css
  packages/main/test/pages/Badge.html
  packages/main/test/pages/Badge.js
  packages/website/docs/_samples/main/Badge/Basic/sample.html
Labels: BREAKING CHANGE, 2.0

#8635 refactor(ui5-carousel): replace items-per-page-s, items-per-page-m, items-per-page-l properties
  packages/main/src/Carousel.ts
  packages/main/test/pages/Carousel.html
  packages/main/test/specs/Carousel.spec.js
  packages/playground/_stories/main/Carousel/Carousel.stories.ts
  packages/website/docs/_components_pages/main/Carousel.mdx
  packages/website/docs/_samples/main/Carousel/MultipleItemsPerPage/sample.html
Labels: BREAKING CHANGE, 2.0

#8778 refactor(ui5-menu): rename the busy and busy delay properties
  packages/main/src/Menu.hbs
  packages/main/src/Menu.ts
  packages/main/src/MenuItem.ts
  packages/main/src/MenuListItem.ts
  packages/main/src/NavigationMenu.hbs
  packages/main/test/pages/Menu.html
  packages/main/test/specs/Menu.spec.js
  packages/playground/_stories/main/Menu/MenuItem/MenuItem.stories.ts
Labels: BREAKING CHANGE, 2.0

#8814 refactor(ui5-li): removes role property
  packages/main/src/ListItem.ts
Labels: 2.0

#8816 refactor(ui5-page): rename disableScrolling and floatingFooter properties
  packages/fiori/src/Page.ts
  packages/fiori/src/themes/Page.css
  packages/fiori/test/pages/DynamicSideContent.html
  packages/fiori/test/pages/Page.html
  packages/main/src/themes/PopupsCommon.css
  packages/playground/_stories/fiori/Page/Page.stories.ts
  packages/website/docs/_components_pages/fiori/Page.mdx
  packages/website/docs/_samples/fiori/Page/Basic/sample.html
  packages/website/docs/_samples/fiori/Page/FixedFooter/FixedFooter.md
  packages/website/docs/_samples/fiori/Page/FixedFooter/main.js
  packages/website/docs/_samples/fiori/Page/FixedFooter/sample.html
Labels: BREAKING CHANGE, 2.0

#8815 refactor(ui5-tree, ui5-list, ui5-li): removes accessibleRoleDescripti…
  packages/main/src/List.hbs
  packages/main/src/List.ts
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.ts
  packages/main/src/Tree.hbs
  packages/main/src/Tree.ts
  packages/main/src/TreeItemBase.ts
Labels: 2.0

#8761 refactor(ui5-segmented-button): rename `mode` to `selectionMode`
  packages/fiori/src/ViewSettingsDialog.ts
  packages/main/src/SegmentedButton.ts
  packages/main/src/types/SegmentedButtonSelectionMode.ts
  packages/main/test/pages/RTL.html
  packages/main/test/pages/SegmentedButton.html
  packages/main/test/pages/Tokenizer.html
  packages/playground/_stories/main/SegmentedButton/SegmentedButton.stories.ts
Labels: BREAKING CHANGE, 2.0

#8845 refactor(ui5-wizard): rename event parameter
  packages/fiori/src/Wizard.ts
  packages/fiori/test/pages/Wizard_test.html
Labels: BREAKING CHANGE, 2.0

#8669 refactor(ui5-segmented-button-item): implement segmented button item independently from button
  packages/fiori/src/ViewSettingsDialog.hbs
  packages/main/src/SegmentedButton.ts
  packages/main/src/SegmentedButtonItem.hbs
  packages/main/src/SegmentedButtonItem.ts
  packages/main/src/TimePickerInternals.ts
  packages/main/src/TimeSelectionClocks.hbs
  packages/main/src/TimeSelectionClocks.ts
  packages/main/src/TimeSelectionInputs.hbs
  packages/main/src/themes/SegmentedButton.css
  packages/main/src/themes/SegmentedButtonItem.css
  packages/main/src/themes/base/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_fiori_3/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcb/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcw/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
  packages/main/src/themes/sap_horizon/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_horizon/parameters-bundle.css
  packages/main/src/themes/sap_horizon_dark/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
  packages/main/src/themes/sap_horizon_hcb/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css
  packages/main/src/themes/sap_horizon_hcw/SegmentedButtonItem-parameters.css
  packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
  packages/main/test/pages/FormComponents.html
  packages/main/test/pages/RTL.html
  packages/main/test/pages/SegmentedButton.html
  packages/main/test/specs/SegmentedButton.spec.js
  packages/main/test/specs/TimeSelectionClocks.spec.js
  packages/playground/_stories/main/SegmentedButton/SegmentedButton.stories.ts
  packages/playground/_stories/main/SegmentedButton/SegmentedButtonItem/SegmentedButtonItem.stories.ts
  packages/website/docs/_samples/main/SegmentedButton/Basic/sample.html
  packages/website/docs/_samples/main/SegmentedButton/SelectionModes/sample.html
Labels: BREAKING CHANGE, 2.0

#8855 refactor(ui5-toast): replace `show` method with `open` property
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/pages/ShellBar.html
  packages/main/src/Toast.ts
  packages/main/test/pages/Popover.html
  packages/main/test/pages/Toast.html
  packages/website/docs/_samples/main/Toast/Basic/main.js
  packages/website/docs/_samples/main/Toast/Duration/main.js
  packages/website/docs/_samples/main/Toast/Placement/main.js
Labels: BREAKING CHANGE, 2.0

#8825 refactor(ui5-li, ui5-list): changes accessibleRole type
  packages/main/src/List.hbs
  packages/main/src/List.ts
  packages/main/src/ListItem.ts
  packages/main/src/Menu.hbs
  packages/main/src/NavigationMenu.hbs
  packages/main/src/Tree.ts
  packages/main/src/types/ListAccessibleRole.ts
  packages/main/src/types/ListItemAccessibleRole.ts
  packages/main/test/specs/Menu.spec.js
Labels: BREAKING CHANGE, 2.0

#8827 feature(ui5-option): tooltip property added
  packages/main/src/Option.ts
  packages/main/src/Select.ts
  packages/main/src/SelectPopover.hbs
  packages/main/test/pages/Select.html
  packages/main/test/specs/Select.spec.js
  packages/playground/_stories/main/Select/Option/Option.stories.ts
Labels: 2.0

#8848 fix(ui5-time-picker): fix buttons announcements in value help dialog
  packages/main/src/ToggleSpinButton.hbs
  packages/main/src/ToggleSpinButton.ts
Labels: ACC

#8834 refactor(ui5-icon): add mode property
  packages/main/src/Button.hbs
  packages/main/src/Button.ts
  packages/main/src/DatePicker.ts
  packages/main/src/DatePickerInput.hbs
  packages/main/src/Icon.ts
  packages/main/src/Select.hbs
  packages/main/src/StandardListItem.hbs
  packages/main/src/themes/Icon.css
  packages/main/src/types/IconMode.ts
  packages/main/test/pages/Icon.html
  packages/main/test/specs/Icon.spec.js
  packages/playground/_stories/main/Icon/Icon.stories.ts
  packages/playground/docs/landing-page.html
  packages/website/docs/_samples/main/Icon/Interactive/sample.html
Labels: BREAKING CHANGE, 2.0
