Repository SAP/ui5-webcomponents, pull requests merged in 2024-07, with the labels that each got.

#9346 WIP: create announcing-v2.mdx
  packages/website/blog/releases/announcing-v2.mdx
Labels: 2.0

#9222 fix(ui5-rating-indicator): make rating indicator ACC WCAG 2.2 compliant
  packages/main/src/themes/sap_horizon/RatingIndicator-parameters.css
  packages/main/src/themes/sap_horizon_dark/RatingIndicator-parameters.css
  packages/main/src/themes/sap_horizon_hcb/RatingIndicator-parameters.css
  packages/main/src/themes/sap_horizon_hcw/RatingIndicator-parameters.css
  packages/main/test/pages/RatingIndicator.html
Labels: ACC WCAG 2.2

#9323 docs: enhance custom development section
  README.md
  docs/09-FAQ.md
  docs/2-advanced/06-using-i18n-for-apps.md
  docs/5-development/01-library.md
  docs/5-development/02-component.md
  docs/5-development/02-custom-UI5-Web-Components.md
  docs/5-development/03-properties.md
  docs/5-development/03-understanding-components-metadata.md
  docs/5-development/04-slots.md
  docs/5-development/04-understanding-hbs-templates.md
  docs/5-development/05-events.md
  docs/5-development/05-testing-UI5-Web-Components.md
  docs/5-development/06-deep-dive-and-best-practices.md
  docs/5-development/06-lifecycle-hooks.md
  docs/5-development/07-styling.md
  docs/5-development/07-typescript-in-UI5-Web-Components.md
  docs/5-development/08-templates.md
  docs/5-development/09-internationalization.md
  docs/5-development/10-testing.md
  docs/5-development/11-rendering-engine.md
  docs/5-development/12-deep-dive-and-best-practices.md
  docs/5-development/README.md
  docs/6-contributing/01-development-workflow.md
  docs/6-contributing/02-conventions-and-guidelines.md
Labels: documentation, 2.0

#9089 refactor(ui5-li): replace the usage of image property with image slot
  packages/main/src/ListItemStandard.hbs
  packages/main/src/ListItemStandard.ts
  packages/main/src/themes/ListItem.css
  packages/main/test/pages/Carousel.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/List.html
  packages/main/test/pages/ListGrowing_Button.html
  packages/main/test/pages/ListGrowing_Scroll.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/pages/Popover.html
  packages/main/test/samples/List.sample.html
  packages/main/test/specs/List.spec.js
  packages/website/docs/_samples/main/Card/Basic/sample.html
  packages/website/docs/_samples/main/Card/WithList/sample.html
  packages/website/docs/_samples/main/Carousel/MultipleItemsPerPage/sample.html
  packages/website/docs/_samples/main/List/GroupHeaders/sample.html
Labels: BREAKING CHANGE, 2.0

#9341 fix(dynamic-page): some remarks fixed
  packages/fiori/src/themes/DynamicPage.css
  packages/fiori/src/themes/DynamicPageHeaderActions.css
Labels: 2.0 Release Testing

#9325 fix(ui5-link): remove the space between `end-icon` and text in long links
  packages/main/src/themes/Link.css
  packages/main/test/pages/Link.html
Labels: 2.0 Release Testing

#9335 fix(ui5-checkbox): adjust focus outline in wrapped mode
  packages/main/src/themes/CheckBox.css
  packages/main/src/themes/base/CheckBox-parameters.css
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3/CheckBox-parameters.css
  packages/main/src/themes/sap_fiori_3_dark/CheckBox-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/CheckBox-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcb/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/CheckBox-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_hcw/sizes-parameters.css
  packages/main/src/themes/sap_horizon/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon/sizes-parameters.css
  packages/main/src/themes/sap_horizon_dark/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon_dark/sizes-parameters.css
  packages/main/src/themes/sap_horizon_exp/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon_hcb/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon_hcb/sizes-parameters.css
  packages/main/src/themes/sap_horizon_hcw/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon_hcw/sizes-parameters.css
Labels: 2.0 Release Testing

#9375 chore: update create-webc-package template
  packages/create-package/template/src/MyFirstComponent.ts
Labels: 2.0

#9373 docs: write Styles article
  docs/5-development/01-package.md
  docs/5-development/07-styling.md
  docs/5-development/08-templates.md
  docs/7-migration-guides/01-to-version-2.md
Labels: documentation, 2.0

#9377 docs: new internationalization
  docs/5-development/09-internationalization.md
Labels: documentation, 2.0

#9388 chore: fix console errors and typos
  packages/main/src/MessageStrip.ts
  packages/main/src/TextArea.ts
  packages/main/src/themes/Input.css
  packages/main/test/pages/Input.html
  packages/website/docs/_components_pages/main/Input/Input.mdx
Labels: 2.0 Release Testing

#9333 feat(ui5-menu-item): add accessibility attributes
  packages/base/src/types.ts
  packages/main/src/ListItem.hbs
  packages/main/src/ListItem.ts
  packages/main/src/MenuItem.hbs
  packages/main/src/MenuItem.ts
  packages/main/test/pages/Menu.html
  packages/main/test/specs/Menu.cy.js
Labels: enhancement, ACC, 2.0

#9412 fix(ui5-shellbar): add tooltip for shellbar items
  packages/fiori/src/ShellBarPopover.hbs
Labels: 1.24, downport

#9443 fix(ui5-table): correct announced row count
  packages/main/src/Table.hbs
Labels: 1.24, downport

#9330 fix(ui5-checkbox): adjust focus outline in wrapped mode
  packages/main/src/themes/CheckBox.css
  packages/main/src/themes/base/CheckBox-parameters.css
  packages/main/src/themes/base/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3/CheckBox-parameters.css
  packages/main/src/themes/sap_fiori_3/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3/sizes-parameters.css
  packages/main/src/themes/sap_fiori_3_dark/CheckBox-parameters.css
  packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
  packages/main/src/themes/sap_fiori_3_dark/sizes-parameters.css
  packages/main/src/themes/sap_horizon/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon/sizes-parameters.css
  packages/main/src/themes/sap_horizon_dark/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon_dark/sizes-parameters.css
  packages/main/src/themes/sap_horizon_hcb/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon_hcb/sizes-parameters.css
  packages/main/src/themes/sap_horizon_hcw/CheckBox-parameters.css
  packages/main/src/themes/sap_horizon_hcw/sizes-parameters.css
Labels: 1.24, downport

#9469 fix(ui5-segmented-button): prevent focus for disabled items
  packages/main/src/Button.ts
  packages/main/src/SegmentedButton.ts
  packages/main/src/ToggleButton.ts
  packages/main/src/themes/SegmentedButton.css
  packages/main/test/pages/SegmentedButton.html
  packages/main/test/specs/Button.spec.js
  packages/main/test/specs/SegmentedButton.spec.js
Labels: 1.24, downport

#9514 fix(ui5-multi-combobox, ui5-combobox, ui5-input): improve popup announcement
  packages/main/src/ComboBox.ts
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/Input.ts
  packages/main/src/InputPopover.hbs
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/i18n/messagebundle.properties
Labels: 1.24, downport

#9540 chore: display tag / since information in playground
  packages/website/build-scripts/api-reference-generation/component-file.mjs
  packages/website/src/css/custom.css
Labels: for review

#9528 fix(ui5-shellbar): improved readability
  packages/fiori/src/themes/ShellBar.css
Labels: 1.24, downport

#9479 feat: enhance feature initialization
  packages/base/src/FeaturesRegistry.ts
  packages/base/src/UI5Element.ts
  packages/base/src/UI5ElementMetadata.ts
  packages/base/src/decorators/customElement.ts
  packages/main/src/ColorPalette.ts
  packages/main/src/ColorPaletteDialog.hbs
  packages/main/src/Input.hbs
  packages/main/src/Input.ts
  packages/main/src/InputPopover.hbs
  packages/main/src/features/ColorPaletteMoreColors.ts
  packages/main/src/features/InputSuggestions.ts
Labels: for review

#9423 fix(ui5-menu): adjust loading sub-menu
  packages/main/src/Menu.hbs
  packages/main/src/Menu.ts
Labels: bug, 1.24

#9583 chore: fix styles
  packages/website/src/css/custom.css
Labels: for review

#9563 feat: update @ui5/webcomponents-icons to 5.9 & 4.21
  packages/icons/src/v4/SAP-icons.json
  packages/icons/src/v5/SAP-icons.json
  packages/main/test/specs/Icon.spec.js
Labels: for review

#9541 fix(ui5-timepicker): fix error thrown upon selection from the clock
  packages/main/src/TimePickerClock.ts
Labels: for review

#9603 feat(theming): update theming-base-content to 11.17.1
  packages/theming/package.json
  yarn.lock
Labels: dependencies
