Repository SAP/ui5-webcomponents, pull requests merged in 2024-06, with the labels that each got.

#9006 refactor(ui5-link): wrap text by default
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/TimelineItem.hbs
  packages/fiori/src/UploadCollectionItem.hbs
  packages/main/src/Breadcrumbs.hbs
  packages/main/src/Link.ts
  packages/main/src/themes/Link.css
  packages/main/test/pages/Link.html
  packages/website/docs/_components_pages/main/Link.mdx
  packages/website/docs/_samples/main/Link/TextWrapping/sample.html
Labels: BREAKING CHANGE, 2.0

#9077 feat(ui5-menu-item): add endContent slot
  packages/main/src/Button.ts
  packages/main/src/ListItemBase.ts
  packages/main/src/Menu.ts
  packages/main/src/MenuItem.hbs
  packages/main/src/MenuItem.ts
  packages/main/src/themes/MenuItem.css
  packages/main/test/pages/Menu.html
  packages/main/test/specs/Menu.spec.js
  packages/website/docs/_components_pages/main/Menu/Menu.mdx
  packages/website/docs/_samples/main/Menu/MenuEndContent/MenuEndContent.md
  packages/website/docs/_samples/main/Menu/MenuEndContent/main.js
  packages/website/docs/_samples/main/Menu/MenuEndContent/sample.html
Labels: 2.0

#8998 fix(ui5-time-picker): remove box shadow
  packages/main/src/themes/TimePicker.css
Labels: 1.24, downport

#9125 fix(ui5-calendar): adjust accessibility semantics
  packages/main/src/MonthPicker.hbs
  packages/main/src/YearPicker.hbs
Labels: 1.24, downport

#8956 fix(ui5-popup): initialFocus won't work if 'autofocus' is set
  packages/main/src/Popup.ts
  packages/main/test/pages/Dialog.html
  packages/main/test/specs/Dialog.spec.js
Labels: Stale

#9150 fix(framework): set dataTransfer.effectAllowed only for UI5 elements
  packages/base/src/util/dragAndDrop/DragRegistry.ts
  packages/main/src/ListItem.ts
  packages/main/src/TabContainer.ts
  packages/main/test/pages/DragAndDropGeneric.html
  packages/main/test/pages/styles/DragAndDropGeneric.css
Labels: 1.24, downport

#9112 refactor(ui5-multi-combobox): replace open-change event with open and close events
  packages/main/src/MultiComboBox.ts
  packages/main/test/pages/MultiComboBox.html
  packages/main/test/specs/MultiComboBox.spec.js
Labels: BREAKING CHANGE, 2.0

#9036 feat(ui5-link): introduce `icon` and `endIcon` properties
  packages/main/src/Link.hbs
  packages/main/src/Link.ts
  packages/main/src/themes/Link.css
  packages/main/test/pages/Link.html
  packages/main/test/specs/Link.spec.js
  packages/website/docs/_components_pages/main/Link.mdx
  packages/website/docs/_samples/main/Link/WithIcons/WithIcons.md
  packages/website/docs/_samples/main/Link/WithIcons/main.js
  packages/website/docs/_samples/main/Link/WithIcons/sample.html
Labels: 2.0

#9115 refactor(ui5-tag): remove design Color Set 3
  packages/main/src/Tag.ts
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/Avatar.css
  packages/main/src/themes/Tag.css
  packages/main/src/themes/base/Tag-parameters.css
  packages/main/src/themes/sap_fiori_3_hcb/Tag-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/Tag-parameters.css
  packages/main/src/themes/sap_horizon/Tag-parameters.css
  packages/main/src/themes/sap_horizon_dark/Tag-parameters.css
  packages/main/src/themes/sap_horizon_dark_exp/Tag-parameters.css
  packages/main/src/themes/sap_horizon_exp/Tag-parameters.css
  packages/main/src/themes/sap_horizon_hcb/Tag-parameters.css
  packages/main/src/themes/sap_horizon_hcb_exp/Tag-parameters.css
  packages/main/src/themes/sap_horizon_hcw/Tag-parameters.css
  packages/main/src/themes/sap_horizon_hcw_exp/Tag-parameters.css
  packages/main/src/types/TagDesign.ts
  packages/main/test/pages/Tag.html
  packages/main/test/pages/Tag.js
  packages/main/test/specs/Tag.spec.js
  packages/website/docs/_components_pages/main/Tag.mdx
  packages/website/docs/_samples/main/Tag/Basic/sample.html
  packages/website/docs/_samples/main/Tag/Designs/sample.html
  packages/website/docs/_samples/main/Tag/Set3/Set3.md
  packages/website/docs/_samples/main/Tag/Set3/main.js
  packages/website/docs/_samples/main/Tag/Set3/sample.html
Labels: BREAKING CHANGE, 2.0

#9018 fix(ui5-button): add keyboard shortcut to cancel the button's action
  packages/main/src/Button.ts
  packages/main/test/specs/Button.spec.js
Labels: 1.24, downport

#9126 refactor(ui5-tag): wrap text by default
  packages/fiori/src/NotificationListItem.hbs
  packages/main/src/Tag.ts
  packages/main/src/themes/Tag.css
  packages/main/test/pages/Tag.html
  packages/main/test/pages/Tag.js
  packages/main/test/specs/Tag.spec.js
  packages/website/docs/_samples/fiori/DynamicPage/Basic/sample.html
  packages/website/docs/_samples/main/Avatar/WithBadge/sample.html
  packages/website/docs/_samples/main/Tag/Designs/sample.html
  packages/website/docs/_samples/main/Tag/Interactive/sample.html
  packages/website/docs/_samples/main/Tag/Size/sample.html
  packages/website/docs/_samples/main/Tag/WrappingTypes/sample.html
Labels: BREAKING CHANGE, 2.0

#9078 feat(ui5-ai-prompt-input): initial (experimental) implementation
  packages/ai/src/PromptInput.hbs
  packages/ai/src/PromptInput.ts
  packages/ai/src/i18n/messagebundle.properties
  packages/ai/src/themes/PromptInput.css
  packages/ai/test/pages/PromptInput.html
  packages/website/docs/_components_pages/ai/PromptInput.mdx
  packages/website/docs/_samples/ai/PromptInput/Basic/main.js
  packages/website/docs/_samples/ai/PromptInput/Basic/sample.html
  packages/website/src/components/Editor/index.js
Labels: New Component

#9164 refactor(ui5-side-navigation-item): remove wholeItemToggleable property
  packages/fiori/src/SideNavigationItem.ts
  packages/fiori/test/pages/SideNavigation.html
  packages/fiori/test/pages/SideNavigationOnly.html
  packages/fiori/test/pages/SideNavigationWithGroups.html
  packages/fiori/test/specs/SideNavigation.spec.js
Labels: BREAKING CHANGE, 2.0

#8842 refactor(ui5-combobox): integrate properly popover api
  packages/main/src/ComboBox.ts
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/Input.ts
  packages/main/test/specs/ComboBox.spec.js
Labels: 2.0

#9165 refactor(ui5-checkbox): wrap text by default
  packages/main/src/CheckBox.ts
  packages/main/src/themes/CheckBox.css
  packages/main/test/pages/CheckBox.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/website/docs/_components_pages/main/CheckBox.mdx
  packages/website/docs/_samples/main/CheckBox/TextWrapping/sample.html
Labels: BREAKING CHANGE, 2.0

#9221 fix(ui5-date-picker): provide accessible name to the popover (#8693)
  packages/main/src/DatePicker.ts
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/DateRangePicker.ts
  packages/main/src/DateTimePicker.ts
  packages/main/src/TimePicker.ts
  packages/main/src/TimePickerPopover.hbs
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/specs/DatePicker.spec.js
  packages/main/test/specs/DateRangePicker.spec.js
  packages/main/test/specs/DateTimePicker.spec.js
  packages/main/test/specs/TimePicker.spec.js
Labels: 1.24, downport

#9127 fix(ui5-button): adjust screen reader announcement order (#8997)
  packages/main/src/Button.hbs
  packages/main/src/Button.ts
  packages/main/test/specs/Button.spec.js
Labels: 1.24, downport

#9220 fix(ui5-step-input): check input before accessing value
  packages/main/src/StepInput.ts
Labels: 1.24, downport

#9245 chore: adapt OpenUI5 version check
  packages/base/src/features/OpenUI5Support.ts
Labels: for review

#9204 fix(ui5-dialog): fix focusing when dialog is open from OpenUI5 dialog
  packages/base/src/features/OpenUI5Support.ts
  packages/base/src/features/patchPopup.ts
  packages/main/test/pages/DialogAndOpenUI5Dialog.html
Labels: 1.24, downport

#9274 fix(ui5-tab-container): change display
  packages/main/src/themes/TabContainer.css
Labels: BREAKING CHANGE, 2.0

#8871 feat(ui5-menu-separator): add new component
  packages/main/src/Menu.ts
  packages/main/src/MenuItem.ts
  packages/main/src/MenuSeparator.hbs
  packages/main/src/MenuSeparator.ts
  packages/main/src/bundle.esm.ts
  packages/main/src/themes/MenuItem.css
  packages/main/src/themes/MenuSeparator.css
  packages/main/test/pages/Menu.html
  packages/main/test/specs/Menu.spec.js
  packages/website/docs/_components_pages/main/Menu/MenuSeparator.mdx
  packages/website/docs/_samples/main/Menu/Basic/main.js
  packages/website/docs/_samples/main/Menu/Basic/sample.html
Labels: BREAKING CHANGE, 2.0

#9249 refactor(ui5-view-settings-dialog): change opening api to open property
  packages/fiori/src/ViewSettingsDialog.hbs
  packages/fiori/src/ViewSettingsDialog.ts
  packages/fiori/test/pages/ViewSettingsDialog.html
  packages/website/docs/_samples/fiori/ViewSettingsDialog/Basic/main.js
Labels: BREAKING CHANGE, 2.0

#9246 refactor(ui5-li): selected property changed to private
  packages/main/src/ListItem.ts
  packages/main/src/ListItemBase.ts
  packages/main/src/MenuSeparator.ts
  packages/main/src/Option.ts
  packages/main/src/OptionCustom.ts
Labels: 2.0

#9308 refactor: rename `ListSeparators` enum to `ListSeparator`
  docs/Migrating to version 2.0 guide.md
  packages/main/src/List.ts
  packages/main/src/types/ListSeparator.ts
Labels: BREAKING CHANGE, 2.0

#9299 fix(ui5-daterange-picker): selected announcement
  packages/main/src/DayPicker.ts
  packages/main/test/specs/DateRangePicker.spec.js
Labels: 1.24, downport

#9307 refactor(ui5-combobox, ui5-multi-combobox): prepare for physical list items
  packages/main/src/ComboBox.ts
  packages/main/src/ComboBoxItemGroup.ts
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiComboBoxItemGroup.ts
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/test/pages/ComboBox.html
  packages/main/test/pages/MultiComboBox.html
  packages/main/test/specs/MultiComboBox.spec.js
  packages/website/docs/_samples/main/ComboBox/Grouping/sample.html
  packages/website/docs/_samples/main/MultiComboBox/MultiComboBoxGrouping/sample.html
Labels: BREAKING CHANGE, 2.0

#9328 fix(ui5-calendar): adjust year button visibility
  packages/main/src/Calendar.hbs
  packages/main/src/Calendar.ts
  packages/main/test/specs/Calendar.spec.js
Labels: 1.24, downport
