Repository SAP/ui5-webcomponents, pull requests merged in 2024-05, with the labels that each got.

#8861 fix(ui5-side-navigation): import overflow icon
  packages/fiori/src/SideNavigation.ts
Labels: 1.24

#8810 refactor(ui5-*): use unified API to define a11y attributes via `accessibilityAttributes`
  docs/2-advanced/07-accessibility.md
  docs/Migrating to version 2.0 guide.md
  packages/base/src/types.ts
  packages/base/src/types/AriaHasPopup.ts
  packages/base/src/types/AriaLandmarkRole.ts
  packages/base/src/types/AriaRole.ts
  packages/fiori/src/FlexibleColumnLayout.ts
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/ShellBar.ts
  packages/fiori/src/SideNavigationItemBase.ts
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/ShellBar.html
  packages/fiori/test/specs/FCL.spec.js
  packages/fiori/test/specs/NotificationList.spec.js
  packages/fiori/test/specs/ShellBar.spec.js
  packages/main/src/Avatar.ts
  packages/main/src/AvatarGroup.hbs
  packages/main/src/AvatarGroup.ts
  packages/main/src/Breadcrumbs.hbs
  packages/main/src/Breadcrumbs.ts
  packages/main/src/Button.ts
  packages/main/src/DatePicker.ts
  packages/main/src/Link.ts
  packages/main/src/ListItem.ts
  packages/main/src/Menu.hbs
  packages/main/src/MenuListItem.ts
  packages/main/src/MessageStrip.ts
  packages/main/src/NavigationMenu.hbs
  packages/main/src/ResponsivePopover.hbs
  packages/main/src/SelectMenuOption.ts
  packages/main/src/SplitButton.hbs
  packages/main/src/SplitButton.ts
  packages/main/src/Tab.ts
  packages/main/src/TabContainer.hbs
  packages/main/src/TabContainer.ts
  packages/main/src/TabInStrip.hbs
  packages/main/src/Text.ts
  packages/main/src/Title.ts
  packages/main/src/Toolbar.ts
  packages/main/src/ToolbarButton.ts
  packages/main/src/TreeItemBase.ts
  packages/main/test/pages/Avatar.html
  packages/main/test/pages/AvatarGroup.html
  packages/main/test/pages/Link.html
  packages/main/test/pages/Menu.html
  packages/playground/_stories/fiori/FlexibleColumnLayout/FlexibleColumnLayout.stories.ts
  packages/playground/_stories/fiori/ShellBar/ShellBar.stories.ts
  packages/playground/_stories/main/Avatar/Avatar.stories.ts
  packages/playground/_stories/main/AvatarGroup/AvatarGroup.stories.ts
Labels: BREAKING CHANGE, 2.0

#8851 fix(ui5-dialog): state icon no longer shrinks when title is too long
  packages/main/src/themes/Dialog.css
Labels: 1.24, downport

#8862 fix(ui5-side-navigation): replace items and fixedItems union type with SideNavigationItemBase
  packages/fiori/src/SideNavigation.ts
Labels: 1.24, downport

#8749 feat(ui5-date-picker): Replace `openPicker` method with `open` property
  packages/main/src/DatePicker.ts
  packages/main/src/DatePickerInput.hbs
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/DateRangePicker.ts
  packages/main/src/DateTimePicker.ts
  packages/main/test/pageobjects/DatePickerTestPage.js
  packages/main/test/specs/DatePicker.spec.js
  packages/main/test/specs/DateTimePicker.spec.js
Labels: BREAKING CHANGE, 2.0

#8769 refactor(ui5-input): events changes
  packages/fiori/src/themes/ShellBar.css
  packages/fiori/test/pages/ShellBar.html
  packages/main/src/Input.ts
  packages/main/src/MultiInput.ts
  packages/main/src/features/InputSuggestions.ts
  packages/main/test/pages/Input.html
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/MultiInput.html
  packages/main/test/pages/MultiInput_Suggestions.html
  packages/main/test/specs/Input.mobile.spec.js
  packages/main/test/specs/Input.spec.js
  packages/main/test/specs/MultiInput.spec.js
Labels: BREAKING CHANGE, 2.0

#8484 feat(ui5-tokenizer): introduce new component
  packages/main/src/MultiComboBox.hbs
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiInput.hbs
  packages/main/src/MultiInput.ts
  packages/main/src/Token.hbs
  packages/main/src/Token.ts
  packages/main/src/Tokenizer.hbs
  packages/main/src/Tokenizer.ts
  packages/main/src/TokenizerPopover.hbs
  packages/main/src/i18n/messagebundle.properties
  packages/main/src/themes/MultiComboBox.css
  packages/main/src/themes/Token.css
  packages/main/src/themes/Tokenizer.css
  packages/main/src/themes/TokenizerPopover.css
  packages/main/test/pages/Tokenizer.html
  packages/main/test/pages/styles/Tokenizer.css
  packages/main/test/specs/MultiComboBox.mobile.spec.js
  packages/main/test/specs/MultiComboBox.spec.js
  packages/main/test/specs/MultiInput.mobile.spec.js
  packages/main/test/specs/MultiInput.spec.js
  packages/main/test/specs/Tokenizer.mobile.spec.js
  packages/main/test/specs/Tokenizer.spec.js
  packages/website/docs/_components_pages/main/Token.mdx
  packages/website/docs/_components_pages/main/Tokenizer.mdx
  packages/website/docs/_samples/main/Tokenizer/Basic/Basic.md
  packages/website/docs/_samples/main/Tokenizer/Basic/main.js
  packages/website/docs/_samples/main/Tokenizer/Basic/sample.html
Labels: New Component, BREAKING CHANGE, 2.0

#8916 refactor(ui5-title): wrap text by default
  packages/fiori/src/IllustratedMessage.hbs
  packages/fiori/src/UploadCollection.hbs
  packages/fiori/src/ViewSettingsDialog.hbs
  packages/fiori/test/pages/F6TestPage.html
  packages/fiori/test/pages/FCL.html
  packages/main/src/ColorPalettePopover.hbs
  packages/main/src/ResponsivePopover.hbs
  packages/main/src/Title.ts
  packages/main/src/TokenizerPopover.hbs
  packages/main/src/themes/Dialog.css
  packages/main/src/themes/Title.css
  packages/main/test/pages/DateTimePicker.html
  packages/main/test/pages/Title.html
  packages/playground/_stories/fiori/FlexibleColumnLayout/FlexibleColumnLayout.stories.ts
  packages/website/docs/_samples/fiori/FlexibleColumnLayout/Basic/sample.html
Labels: BREAKING CHANGE, 2.0

#8935 refactor(ui5-label): wrap text by default
  packages/fiori/src/UploadCollectionItem.hbs
  packages/fiori/test/pages/F6TestPage.html
  packages/fiori/test/pages/FCL.html
  packages/fiori/test/pages/Wizard.html
  packages/fiori/test/pages/WizardPageMode_test.html
  packages/fiori/test/pages/Wizard_test.html
  packages/fiori/test/pages/Wizard_test_mobile.html
  packages/main/src/BusyIndicator.hbs
  packages/main/src/Label.ts
  packages/main/src/themes/Label.css
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/Label.html
  packages/main/test/specs/Label.spec.js
  packages/playground/_stories/fiori/Wizard/Wizard.stories.ts
  packages/playground/_stories/fiori/Wizard/WizardStep/WizardStep.stories.ts
  packages/playground/_stories/main/Panel/Panel.stories.ts
  packages/website/docs/_components_pages/main/Label.mdx
  packages/website/docs/_samples/fiori/Wizard/Basic/sample.html
  packages/website/docs/_samples/fiori/Wizard/PageMode/sample.html
  packages/website/docs/_samples/main/Label/TextWrapping/sample.html
  packages/website/docs/_samples/main/Panel/Basic/sample.html
  packages/website/docs/_samples/main/Panel/CustomHeader/sample.html
  packages/website/docs/_samples/main/Panel/Fixed/sample.html
  packages/website/docs/_samples/main/Panel/StickyHeader/sample.html
Labels: BREAKING CHANGE, 2.0

#8947 refactor(ui5-popover): remove hideBackdrop property
  packages/main/src/Dialog.ts
  packages/main/src/Popover.ts
  packages/main/src/Popup.ts
  packages/main/src/themes/Popover.css
  packages/main/test/pages/Popover.html
  packages/main/test/pages/styles/Popover.css
  packages/playground/_stories/main/Popover/Popover.stories.ts
  packages/playground/_stories/main/ResponsivePopover/ResponsivePopover.stories.ts
Labels: BREAKING CHANGE, 2.0

#8946 refactor(ui5-popup): rename after-open and after-close events to 'open' and 'close'
  packages/fiori/src/BarcodeScannerDialog.hbs
  packages/fiori/src/ShellBarPopover.hbs
  packages/fiori/src/SideNavigationPopover.hbs
  packages/fiori/src/ViewSettingsDialog.hbs
  packages/main/src/ColorPalettePopover.hbs
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/InputPopover.hbs
  packages/main/src/Menu.hbs
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/NavigationMenu.hbs
  packages/main/src/Popover.ts
  packages/main/src/Popup.ts
  packages/main/src/ResponsivePopover.hbs
  packages/main/src/SelectMenu.hbs
  packages/main/src/SelectPopover.hbs
  packages/main/src/TimePickerPopover.hbs
  packages/main/src/Tokenizer.ts
  packages/main/src/TokenizerPopover.hbs
  packages/main/src/ToolbarPopover.hbs
  packages/main/test/pages/DialogLifecycle.html
  packages/main/test/pages/OpenUI5.html
  packages/main/test/pages/Popover.html
Labels: BREAKING CHANGE, 2.0

#8807 refactor(ui5-link): change the accessibleRole property type
  packages/main/src/Button.hbs
  packages/main/src/Button.ts
  packages/main/src/Link.ts
  packages/main/src/ToggleSpinButton.ts
  packages/main/src/types/LinkAccessibleRole.ts
Labels: 2.0

#8804 feat(ui5-date-range): introduce new calendar date type
  packages/main/src/Calendar.ts
  packages/main/src/CalendarDate.ts
  packages/main/src/CalendarDateRange.ts
  packages/main/src/DateRangePicker.hbs
  packages/main/src/DateRangePicker.ts
  packages/main/src/DayPicker.ts
  packages/main/test/pages/Calendar.html
  packages/main/test/specs/Calendar.spec.js
Labels: BREAKING CHANGE, 2.0

#8685 feat(ui5-*): integrate element internals in input components
  docs/1-getting-started/06-using-features.md
  packages/base/src/UI5Element.ts
  packages/base/src/UI5ElementMetadata.ts
  packages/base/src/decorators/customElement.ts
  packages/base/src/features/InputElementsFormSupport.ts
  packages/main/README.md
  packages/main/src/Button.ts
  packages/main/src/CheckBox.hbs
  packages/main/src/CheckBox.ts
  packages/main/src/ColorPicker.ts
  packages/main/src/ComboBox.ts
  packages/main/src/DatePicker.ts
  packages/main/src/DatePickerInput.hbs
  packages/main/src/DateRangePicker.ts
  packages/main/src/DateTimePicker.ts
  packages/main/src/FileUploader.hbs
  packages/main/src/FileUploader.ts
  packages/main/src/Input.hbs
  packages/main/src/Input.ts
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiInput.ts
  packages/main/src/RadioButton.hbs
  packages/main/src/RadioButton.ts
  packages/main/src/RadioButtonGroup.ts
  packages/main/src/RangeSlider.ts
  packages/main/src/Select.hbs
  packages/main/src/Select.ts
  packages/main/src/Slider.ts
  packages/main/src/SliderBase.ts
  packages/main/src/StepInput.hbs
  packages/main/src/StepInput.ts
  packages/main/src/Switch.hbs
  packages/main/src/Switch.ts
  packages/main/src/TextArea.hbs
  packages/main/src/TextArea.ts
  packages/main/src/TimePicker.ts
  packages/main/src/bundle.esm.ts
  packages/main/src/features/InputElementsFormSupport.ts
  packages/main/src/i18n/messagebundle.properties
  packages/main/test/pageobjects/ListTestPage.js
  packages/main/test/pages/FormSupport.html
  packages/main/test/pages/List_test_page.html
  packages/main/test/pages/form_support_test.html
  packages/main/test/pages/form_support_test2.html
  packages/main/test/pages/form_support_test3.html
  packages/main/test/specs/FormSupport.spec.js
  packages/main/test/ssr/component-imports.js
Labels: BREAKING CHANGE, 2.0

#8954 fix(ui5-side-navigation): overflow menu items are now displayed (#8948)
  packages/main/src/NavigationMenu.ts
Labels: 1.24, downport

#8881 feat(ui5-input): allow custom icon styling
  packages/main/src/ComboBox.hbs
  packages/main/src/DatePickerInput.hbs
  packages/main/src/Input.hbs
  packages/main/src/MultiComboBox.hbs
  packages/main/src/MultiInput.hbs
  packages/main/src/Select.hbs
  packages/main/src/StepInput.hbs
  packages/main/src/TimePicker.hbs
  packages/main/src/styles/Icon.module.css
  packages/main/src/styles/Input.module.css
  packages/main/src/themes/Input.css
  packages/main/src/themes/InputIcon.css
  packages/main/src/themes/InputSharedStyles.css
  packages/main/src/themes/ResponsivePopoverCommon.css
  packages/main/test/pages/ComponentStyles.html
  packages/main/test/specs/ComboBox.spec.js
  packages/main/test/specs/LitKeyFunction.spec.js
  packages/main/test/specs/MultiComboBox.spec.js
  packages/tools/lib/css-processors/css-processor-component-styles.mjs
  packages/website/docs/_components_pages/main/Input/Input.mdx
  packages/website/docs/_samples/main/Input/CustomIcon/CustomIcon.md
Labels: 2.0

#8958 fix(ui5-side-navigation-item): click event is no longer fired twice
  packages/fiori/src/SideNavigationSelectableItemBase.ts
  packages/fiori/test/pages/SideNavigation.html
  packages/fiori/test/specs/SideNavigation.spec.js
Labels: 1.24, downport

#8967 refactor(ui5-toast): rename event `after-close` to `close`
  docs/Migrating to version 2.0 guide.md
  packages/main/src/Select.ts
  packages/main/src/SelectMenu.ts
  packages/main/src/Toast.ts
  packages/playground/_stories/main/SplitButton/SplitButton.stories.ts
Labels: BREAKING CHANGE, 2.0

#8904 feat(ui5-list,ui5-tree): make drag&drop feature public
  packages/main/src/CustomListItem.ts
  packages/main/src/List.ts
  packages/main/src/ListItemBase.ts
  packages/main/src/StandardListItem.ts
  packages/main/src/TreeItemBase.ts
  packages/website/docs/_components_pages/main/List/List.mdx
  packages/website/docs/_components_pages/main/Tree/Tree.mdx
  packages/website/docs/_samples/main/List/DragAndDrop/DragAndDrop.md
  packages/website/docs/_samples/main/List/DragAndDrop/main.js
  packages/website/docs/_samples/main/List/DragAndDrop/sample.html
  packages/website/docs/_samples/main/Tree/DragAndDrop/DragAndDrop.md
  packages/website/docs/_samples/main/Tree/DragAndDrop/main.js
  packages/website/docs/_samples/main/Tree/DragAndDrop/sample.html
Labels: 2.0

#8938 docs: update accessibility documentation
  docs/2-advanced/07-accessibility.md
Labels: ACC, 2.0

#8925 feat(ui5-button): add second (end) icon
  packages/main/src/Button.hbs
  packages/main/src/Button.ts
  packages/main/src/TabContainer.hbs
  packages/main/src/themes/Button.css
  packages/main/src/themes/SegmentedButtonItem.css
  packages/main/test/pages/Button.html
  packages/main/test/pages/FileUploader.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/specs/Button.spec.js
  packages/playground/_stories/main/Button/Button.stories.ts
  packages/playground/_stories/main/Menu/Menu.stories.ts
  packages/playground/_stories/main/Menu/MenuItem/MenuItem.stories.ts
  packages/website/docs/_components_pages/main/Button.mdx
  packages/website/docs/_samples/main/Button/EndIcon/EndIcon.md
  packages/website/docs/_samples/main/Button/EndIcon/main.js
  packages/website/docs/_samples/main/Button/EndIcon/sample.html
  packages/website/docs/_samples/main/Button/MenuButton/MenuButton.md
  packages/website/docs/_samples/main/Button/MenuButton/main.js
  packages/website/docs/_samples/main/Button/MenuButton/sample.html
  packages/website/docs/_samples/main/Menu/AditionalText/sample.html
  packages/website/docs/_samples/main/Menu/Basic/sample.html
  packages/website/docs/_samples/main/Menu/SubMenu/sample.html
Labels: BREAKING CHANGE, 2.0

#8980 feat(ui5-input): add input type search
  packages/main/src/types/InputType.ts
  packages/main/test/pages/Input.html
Labels: 2.0

#8968 fix(ui5-popover): fix auto close when click on iframe inside a shadow root
  packages/main/src/popup-utils/PopoverRegistry.ts
  packages/main/test/pages/Popover.html
  packages/main/test/specs/Popover.spec.js
Labels: downport

#8975 fix(ui5-notification): implement keyboard navigation spec
  packages/fiori/README.md
  packages/fiori/src/NotificationList.ts
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListGroupItem.ts
  packages/fiori/src/NotificationListGroupList.ts
  packages/fiori/src/NotificationListItem.hbs
  packages/fiori/src/NotificationListItem.ts
  packages/fiori/src/NotificationListItemBase.ts
  packages/fiori/src/bundle.esm.ts
  packages/fiori/src/i18n/messagebundle.properties
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/pages/NotificationList_test_page.html
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
  packages/fiori/test/specs/NotificationList.spec.js
  packages/website/docs/_samples/fiori/NotificationListGroupItem/Basic/main.js
  packages/website/docs/_samples/fiori/NotificationListGroupItem/Basic/sample.html
  packages/website/docs/_samples/fiori/NotificationListGroupItem/InShellBar/main.js
  packages/website/docs/_samples/fiori/NotificationListGroupItem/InShellBar/sample.html
  packages/website/docs/_samples/fiori/NotificationListItem/Basic/main.js
  packages/website/docs/_samples/fiori/NotificationListItem/Basic/sample.html
Labels: BREAKING CHANGE, 2.0

#8722 refactor(ui5-menu): make menu items physical
  packages/fiori/src/NotificationListItem.ts
  packages/fiori/src/SideNavigation.ts
  packages/main/src/Menu.hbs
  packages/main/src/Menu.ts
  packages/main/src/MenuItem.hbs
  packages/main/src/MenuItem.ts
  packages/main/src/MenuListItem.hbs
  packages/main/src/MenuListItem.ts
  packages/main/src/NavigationMenu.hbs
  packages/main/src/NavigationMenu.ts
  packages/main/src/NavigationMenuItem.hbs
  packages/main/src/NavigationMenuItem.ts
  packages/main/src/themes/Menu.css
  packages/main/src/themes/MenuItem.css
  packages/main/src/themes/NavigationMenu.css
  packages/main/src/themes/NavigationMenuItem.css
  packages/main/test/pages/Menu.html
  packages/main/test/pages/SplitButton.html
  packages/main/test/specs/Menu.spec.js
  packages/website/docs/_samples/main/Menu/AditionalText/main.js
  packages/website/docs/_samples/main/Menu/AditionalText/sample.html
  packages/website/docs/_samples/main/Menu/Basic/main.js
  packages/website/docs/_samples/main/Menu/Basic/sample.html
  packages/website/docs/_samples/main/Menu/SubMenu/main.js
  packages/website/docs/_samples/main/Menu/SubMenu/sample.html
Labels: BREAKING CHANGE, 2.0

#9014 fix: register runtime in SSR usage (#9013)
  packages/base/package.json
  packages/base/src/Boot.ts
  packages/fiori/package.json
  packages/localization/package.json
  packages/main/package.json
Labels: 1.24

#9037 fix(ui5-side-navigation-item): "selected" is no longer announced on every focused item
  packages/fiori/src/SideNavigationItem.hbs
  packages/fiori/src/SideNavigationSubItem.hbs
  packages/fiori/test/specs/SideNavigation.spec.js
Labels: 1.24, downport

#9048 feat(ui5-toolbar-button): add second (end) icon
  packages/main/src/ToolbarButton.hbs
  packages/main/src/ToolbarButton.ts
  packages/main/src/ToolbarPopoverButton.hbs
  packages/main/test/pages/ToolbarButton.html
  packages/main/test/specs/ToolbarButton.spec.js
Labels: BREAKING CHANGE, 2.0

#9043 fix(ui5-calendar): respect component level calendarType in week calculation
  packages/localization/src/dates/calculateWeekNumber.ts
  packages/main/src/DayPicker.ts
Labels: 1.24, downport

#9051 fix(ui5-multi-input): delete selected value on BACKSPACE
  packages/main/src/MultiInput.ts
  packages/main/test/specs/MultiInput.spec.js
Labels: 1.24, downport

#9066 fix(ui5-*): describe missing dependencies
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiInput.ts
  packages/main/src/TabContainer.ts
  packages/main/src/TimeSelectionClocks.ts
  packages/main/src/TimeSelectionInputs.ts
  packages/main/src/Tokenizer.ts
Labels: 1.24, downport

#9001 feat(ui5-time-picker): introduce `open` property
  packages/main/src/TimePicker.hbs
  packages/main/src/TimePicker.ts
  packages/main/src/TimePickerPopover.hbs
  packages/main/test/specs/TimePicker.spec.js
Labels: BREAKING CHANGE, 2.0

#8926 feat(ui5-combobox): introduce nested grouping of items
  packages/main/src/ComboBox.ts
  packages/main/src/ComboBoxItem.ts
  packages/main/src/ComboBoxItemGroup.ts
  packages/main/src/ComboBoxPopover.hbs
  packages/main/test/pages/ComboBox.html
  packages/main/test/specs/ComboBox.mobile.spec.js
  packages/main/test/specs/ComboBox.spec.js
Labels: 2.0

#8950 refactor(ui5-input): replace openPicker method with public property open
  packages/main/src/Input.ts
  packages/main/src/ResponsivePopover.hbs
  packages/main/src/ResponsivePopover.ts
  packages/main/test/pages/Input.html
  packages/main/test/pages/MultiInput.html
  packages/main/test/specs/Input.mobile.spec.js
  packages/main/test/specs/Input.spec.js
Labels: BREAKING CHANGE, 2.0
