Repository SAP/ui5-webcomponents, pull requests merged in 2024-03, with the labels that each got.

#8158 fix(ui5-side-navigation): fix private types
  packages/fiori/src/SideNavigation.ts
  packages/main/src/NavigationMenu.ts
Labels: Stale

#8182 chore: prepare setup for reusable styles
  packages/fiori/src/styles/ToolLayout.module.css
  packages/fiori/test/pages/ComponentStyles.html
  packages/main/src/styles/Input.module.css
  packages/main/test/pages/ComponentStyles.html
  packages/tools/components-package/nps.js
  packages/tools/lib/css-processors/css-processor-component-styles.mjs
Labels: for review, for discussion

#8494 refactor(framework): remove internet explorer related checks
  packages/base/index.js
  packages/base/src/Device.ts
  packages/base/test/ssr/Device.js
Labels: BREAKING CHANGE, 2.0

#8496 refactor(framework): remove CSP related functionality
  docs/2-advanced/08-CSP.md
  docs/2-advanced/08-scrollbars-customization.md
  docs/2-advanced/09-ignore-custom-elements.md
  packages/base/README.md
  packages/base/index.js
  packages/base/src/CSP.ts
  packages/base/src/ManagedStyles.ts
  packages/base/src/UI5Element.ts
  packages/base/src/renderer/LitRenderer.ts
  packages/base/src/theming/getEffectiveLinksHrefs.ts
  packages/base/src/theming/preloadLinks.ts
  packages/base/src/updateShadowRoot.ts
  packages/base/src/util/createStyleInHead.ts
  packages/base/test/assets/bundle.light.js
  packages/base/test/pages/Boot.html
  packages/base/test/specs/Boot.spec.js
  packages/fiori/test/pages/DynamicSideContent.html
  packages/main/src/bundle.common.bootstrap.ts
  packages/main/src/bundle.esm.ts
  packages/main/test/pages/InputFieldMinWidth.html
Labels: BREAKING CHANGE, 2.0

#8497 refactor(ui5-card): remove ICardHeader interface
  packages/main/src/Card.ts
  packages/main/src/CardHeader.ts
Labels: BREAKING CHANGE, 2.0

#8504 refactor(ui5-upload-collection): remove IUploadCollectionItem interface
  packages/fiori/src/UploadCollection.ts
  packages/fiori/src/UploadCollectionItem.ts
Labels: BREAKING CHANGE, 2.0

#8509 refactor(ui5-busy-indicator): rename BusyIndicatorSize values to S, M and L
  packages/fiori/src/BarcodeScannerDialog.hbs
  packages/fiori/src/NotificationListGroupItem.hbs
  packages/fiori/src/NotificationListItem.hbs
  packages/main/src/BusyIndicator.ts
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/List.hbs
  packages/main/src/Table.hbs
  packages/main/src/themes/BusyIndicator.css
  packages/main/src/types/BusyIndicatorSize.ts
  packages/main/test/pages/BusyIndicator.html
  packages/main/test/samples/BusyIndicator.sample.html
  packages/playground/_stories/main/BusyIndicator/BusyIndicator.stories.ts
  packages/website/docs/_components_pages/main/BusyIndicator.mdx
  packages/website/docs/_samples/main/BusyIndicator/Basic/sample.html
  packages/website/docs/_samples/main/BusyIndicator/Sizes/sample.html
  packages/website/docs/_samples/main/BusyIndicator/WithComponent/sample.html
Labels: BREAKING CHANGE, 2.0

#8507 refactor(ui5-card-header): rename status to additionalText
  packages/main/src/CardHeader.hbs
  packages/main/src/CardHeader.ts
  packages/main/src/themes/CardHeader.css
  packages/main/test/pages/Card.html
  packages/main/test/specs/Card.spec.js
  packages/playground/_stories/main/Card/Card.stories.ts
  packages/playground/_stories/main/Card/CardHeader/CardHeader.stories.ts
  packages/website/docs/_samples/main/Card/Basic/sample.html
  packages/website/docs/_samples/main/Card/WithList/sample.html
  packages/website/docs/_samples/main/Card/WithTable/sample.html
Labels: BREAKING CHANGE, 2.0

#8511 refactor(ui5-carousel): rename pageIndicatorStyle to pageIndicatorType
  packages/main/src/Carousel.ts
  packages/main/src/types/CarouselPageIndicatorType.ts
  packages/main/test/pages/Carousel.html
  packages/main/test/specs/Carousel.spec.js
  packages/playground/_stories/main/Carousel/Carousel.stories.ts
  packages/website/docs/_components_pages/main/Carousel.mdx
  packages/website/docs/_samples/main/Carousel/PageIndicatorType/sample.html
Labels: BREAKING CHANGE, 2.0

#8501 refactor(framework): remove render method
  docs/5-development/02-custom-UI5-Web-Components.md
  docs/5-development/07-typescript-in-UI5-Web-Components.md
  packages/base/src/UI5Element.ts
  packages/base/src/decorators/customElement.ts
  packages/base/src/updateShadowRoot.ts
  packages/base/test/elements/Child.js
  packages/base/test/elements/Generic.js
  packages/base/test/elements/Parent.js
  packages/base/test/elements/WithComplexTemplate.js
  packages/base/test/elements/WithStaticArea.js
  packages/main/src/SliderBase.ts
Labels: BREAKING CHANGE, 2.0

#8503 refactor(tools): remove js option from generation templates
  packages/create-package/README.md
  packages/create-package/create-package.js
  packages/create-package/template/package-scripts.js
  packages/create-package/template/src/Assets.js
  packages/create-package/template/src/MyFirstComponent.js
  packages/tools/lib/create-new-component/index.js
  packages/tools/lib/create-new-component/jsFileContentTemplate.js
Labels: BREAKING CHANGE, 2.0

#8506 chore: remove unused command
  package.json
Labels: 2.0

#8502 refactor(ui5-popover): rename enum values
  packages/fiori/src/NotificationOverflowActionsPopover.hbs
  packages/fiori/src/ShellBar.ts
  packages/fiori/test/pages/NotificationListGroupItem.html
  packages/fiori/test/pages/NotificationListItem.html
  packages/fiori/test/samples/NotificationListGroupItem.sample.html
  packages/fiori/test/samples/NotificationListItem.sample.html
  packages/main/src/BreadcrumbsPopover.hbs
  packages/main/src/ComboBox.ts
  packages/main/src/ComboBoxPopover.hbs
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/FileUploaderPopover.hbs
  packages/main/src/Input.ts
  packages/main/src/InputPopover.hbs
  packages/main/src/Menu.hbs
  packages/main/src/Menu.ts
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/Popover.ts
  packages/main/src/SelectMenu.hbs
  packages/main/src/SelectPopover.hbs
  packages/main/src/TabContainerPopover.hbs
  packages/main/src/TextArea.ts
  packages/main/src/TimePickerPopover.hbs
  packages/main/src/TokenizerPopover.hbs
  packages/main/src/ToolbarPopover.hbs
  packages/main/src/themes/Menu.css
  packages/main/src/themes/Popover.css
  packages/main/src/types/PopoverHorizontalAlign.ts
  packages/main/src/types/PopoverPlacementType.ts
  packages/main/test/pages/Input_quickview.html
  packages/main/test/pages/Kitchen.html
  packages/main/test/pages/Kitchen.openui5.html
  packages/main/test/pages/Popover.html
  packages/main/test/pages/PopoverArrowBounds.html
  packages/main/test/pages/Popups.html
  packages/main/test/specs/Popover.spec.js
  packages/playground/_stories/fiori/NotificationListGroupItem/NotificationListGroupItem.stories.ts
  packages/playground/_stories/fiori/NotificationListItem/NotificationListItem.stories.ts
  packages/website/docs/_samples/fiori/NotificationListGroupItem/InShellBar/sample.html
  packages/website/docs/_samples/fiori/NotificationListItem/InShellBar/sample.html
  packages/website/docs/_samples/main/Popover/Placement/sample.html
  packages/website/docs/_samples/main/ResponsivePopover/Placement/sample.html
Labels: BREAKING CHANGE, 2.0

#8524 refactor(icons): remove soccor icon
  packages/icons/src/v4/SAP-icons.json
  packages/icons/src/v5/SAP-icons.json
Labels: BREAKING CHANGE, 2.0

#8525 refactor(icons-business-suite): remove add-polygone icon
  packages/icons-business-suite/src/v1/SAP-icons-business-suite.json
  packages/icons-business-suite/src/v2/SAP-icons-business-suite.json
Labels: BREAKING CHANGE, 2.0

#8526 refactor: remove all Assets-static.js modules
  packages/fiori/src/Assets-static.ts
  packages/icons-business-suite/src/Assets-static.ts
  packages/icons-business-suite/src/json-imports/Icons.ts
  packages/icons-tnt/src/Assets-static.ts
  packages/icons-tnt/src/json-imports/Icons.ts
  packages/icons/src/Assets-static.ts
  packages/icons/src/json-imports/Icons.ts
  packages/localization/lib/generate-json-imports/cldr.js
  packages/localization/src/Assets-static.ts
  packages/main/src/Assets-static.ts
  packages/theming/src/Assets-static.ts
  packages/tools/lib/generate-json-imports/i18n.js
  packages/tools/lib/generate-json-imports/themes.js
Labels: BREAKING CHANGE, 2.0

#8529 refactor(ui5-calendar): rename `selected-dates-change` to `selection-change` and rename few event details
  packages/main/src/Calendar.ts
  packages/main/src/DatePicker.ts
  packages/main/src/DatePickerPopover.hbs
  packages/main/src/DateRangePicker.ts
  packages/main/src/DateTimePicker.ts
  packages/main/src/DateTimePickerPopover.hbs
  packages/main/test/pages/Calendar.html
Labels: BREAKING CHANGE, 2.0

#8538 refactor(ui5-color-picker): rename `color` to `value`
  packages/main/src/ColorPalette.ts
  packages/main/src/ColorPicker.hbs
  packages/main/src/ColorPicker.ts
  packages/main/test/pages/ColorPicker.html
  packages/main/test/specs/ColorPalette.spec.js
  packages/main/test/specs/ColorPicker.spec.js
  packages/playground/_stories/main/ColorPicker/ColorPicker.stories.ts
  packages/website/docs/_samples/main/ColorPicker/Basic/sample.html
Labels: BREAKING CHANGE, 2.0

#8521 refactor(tools): enable TypeScript as default
  packages/base/package-scripts.cjs
  packages/create-package/template/package-scripts.js
  packages/fiori/package-scripts.cjs
  packages/icons-business-suite/package-scripts.cjs
  packages/main/package-scripts.cjs
  packages/theming/package-scripts.cjs
  packages/tools/components-package/nps.js
  packages/tools/icons-collection/nps.js
  packages/tools/lib/css-processors/css-processor-components.mjs
  packages/tools/lib/css-processors/css-processor-themes.mjs
  packages/tools/lib/css-processors/shared.mjs
  packages/tools/lib/generate-json-imports/i18n.js
  packages/tools/lib/generate-json-imports/themes.js
  packages/tools/lib/hbs2lit/src/compiler.js
  packages/tools/lib/hbs2lit/src/litVisitor2.js
  packages/tools/lib/hbs2lit/src/svgProcessor.js
  packages/tools/lib/hbs2ui5/RenderTemplates/LitRenderer.js
  packages/tools/lib/hbs2ui5/index.js
  packages/tools/lib/i18n/defaults.js
Labels: BREAKING CHANGE, 2.0

#8542 refactor(ui5-color-palette): remove deprecated APIs
  packages/main/src/ColorPalettePopover.ts
  packages/main/test/pages/ColorPalettePopover.html
  packages/main/test/samples/ColorPalettePopover.sample.html
  packages/playground/_stories/main/ColorPalettePopover/ColorPalettePopover.stories.ts
  packages/website/docs/_samples/main/ColorPalettePopover/Basic/main.js
  packages/website/docs/_samples/main/ColorPalettePopover/Basic/sample.html
  packages/website/docs/_samples/main/ColorPalettePopover/DefaultColor/main.js
  packages/website/docs/_samples/main/ColorPalettePopover/DefaultColor/sample.html
  packages/website/docs/_samples/main/ColorPalettePopover/MoreColors/main.js
  packages/website/docs/_samples/main/ColorPalettePopover/MoreColors/sample.html
Labels: BREAKING CHANGE, 2.0

#8559 Rename subTabs slot
  packages/main/src/Tab.ts
  packages/main/src/TabContainer.hbs
  packages/main/src/TabContainer.ts
  packages/main/src/TabSeparator.ts
  packages/main/test/pages/TabContainer.html
  packages/main/test/pages/TabContainerDragAndDrop.html
  packages/main/test/samples/TabContainer.sample.html
  packages/playground/_stories/main/TabContainer/Tab/Tab.stories.ts
  packages/playground/_stories/main/TabContainer/TabContainer.stories.ts
  packages/website/docs/_samples/main/TabContainer/NestedTabs/sample.html
Labels: BREAKING CHANGE, 2.0

#8565 refactor(ui5-tabcontainer): rename tabs-overflow-mode
  packages/main/src/TabContainer.ts
  packages/main/src/types/OverflowMode.ts
  packages/main/test/pages/TabContainer.html
  packages/main/test/pages/TabContainerDragAndDrop.html
  packages/main/test/samples/TabContainer.sample.html
  packages/main/test/specs/TabContainer.spec.js
  packages/playground/_stories/main/TabContainer/TabContainer.stories.ts
  packages/website/docs/_components_pages/main/TabContainer/TabContainer.mdx
  packages/website/docs/_samples/main/TabContainer/OverflowMode/OverflowMode.md
  packages/website/docs/_samples/main/TabContainer/OverflowMode/main.js
  packages/website/docs/_samples/main/TabContainer/OverflowMode/sample.html
Labels: BREAKING CHANGE, 2.0

#8570 refactor(ui5-tabcontainer): remove TabContainerBackgroundDesign enume…
  packages/main/src/TabContainer.ts
  packages/main/src/types/TabContainerBackgroundDesign.ts
Labels: 2.0

#8568 refactor(ui5-tabcontainer): remove deprecated showOverflow property
  packages/main/src/TabContainer.ts
Labels: BREAKING CHANGE, 2.0
