Repository SAP/ui5-webcomponents, pull requests merged in 2024-10, with the labels that each got.

#9969 chore: do not strip CLDR assets
  packages/localization/lib/copy-and-strip-cldr/index.js
  packages/localization/package-scripts.cjs
Labels: SAP MDK

#10044 fix(ui5-popup): add role attribute to focus helper element
  packages/main/src/Popup.hbs
Labels: 1.24, downport

#9991 fix(ui5-menu-li): add font-size to the menu item text
  packages/main/src/themes/MenuListItem.css
Labels: 1.24

#10094 fix(ui5-badge): correct parameters for Color Set 2 in high contrast themes
  packages/main/src/themes/sap_fiori_3_hcb/Badge-parameters.css
  packages/main/src/themes/sap_fiori_3_hcw/Badge-parameters.css
Labels: 1.24
