Repository SAP/ui5-webcomponents, pull requests merged in 2025-01, with the labels that each got.

#10456 fix(framework): getComponentFeature can return undefined
  packages/base/src/FeaturesRegistry.ts
  packages/main/src/ColorPalette.ts
  packages/main/src/Input.ts
Labels: bug, TOPIC Core

#10325 fix(f6navigation): skip hidden elements
  packages/base/src/util/FocusableElements.ts
  packages/main/cypress/specs/F6.cy.ts
Labels: Stale

#10344 chore(ui5-table): migrate Table.ts wdio tests to cypress
  packages/main/cypress/specs/Table.cy.ts
  packages/main/test/specs/Table.spec.js
Labels: Stale

#10517 fix: ai button and color palette bring their own items
  packages/ai/README.md
  packages/ai/src/Button.ts
  packages/main/README.md
  packages/main/src/ColorPalette.ts
Labels: bug

#10575 chore(ui5-popover): remove an unnecessary selector
  packages/main/src/Input.ts
  packages/main/src/themes/base/rtl-parameters.css
Labels: 1.24

#10510 refactor: make InputSuggestions a normal dynamic import
  packages/main/src/Input.ts
  packages/main/src/bundle.esm.ts
  packages/main/src/features/InputSuggestions.ts
Labels: TOPIC RL, for review, TOPIC Core

#10608 chore: make color palette more colors declarative
  packages/main/cypress/support/commands/ColorPalette.commands.ts
  packages/main/src/ColorPalette.ts
  packages/main/src/features/ColorPaletteMoreColorsTemplate.tsx
  packages/main/test/specs/ColorPalette.spec.js
Labels: TOPIC B, for review

#10505 refactor: rework the ColorPaletteMoreColors feature
  packages/main/src/ColorPalette.ts
  packages/main/src/ColorPaletteTemplate.tsx
  packages/main/src/Input.ts
  packages/main/src/bundle.esm.ts
  packages/main/src/features/ColorPaletteMoreColors.ts
Labels: for review, TOPIC Core

#10437 fix(ui5-card): fix accessibiity role position
  packages/main/cypress/specs/Card.cy.ts
  packages/main/src/CardHeader.ts
  packages/main/src/CardHeaderTemplate.tsx
Labels: Stale

#10624 chore(framework): remove component features
  docs/2-advanced/05-using-features.md
  packages/ai/src/PromptInput.ts
  packages/base/src/FeaturesRegistry.ts
  packages/base/src/UI5Element.ts
  packages/base/src/UI5ElementMetadata.ts
  packages/base/src/decorators/customElement.ts
  packages/fiori/cypress/specs/ShellBar.cy.ts
  packages/main/README.md
  packages/main/cypress/specs/ColorPalette.cy.ts
  packages/main/cypress/specs/Input.cy.ts
  packages/main/cypress/specs/MultiInput.cy.ts
  packages/main/cypress/specs/base/Events.cy.ts
  packages/main/cypress/support/commands/ColorPalette.commands.ts
  packages/main/src/ColorPalettePopover.ts
  packages/main/src/Input.ts
Labels: for review

#10700 fix(ui5-file-uploder): match focus correctly with screen readers
  packages/main/src/FileUploader.ts
Labels: High Prio, SF_ACC
