Repository SAP/ui5-webcomponents, pull requests merged in 2025-04, with the labels that each got.

#11195 chore: enhance cypress test configuration with conditional execution of tools
  packages/ai/package-scripts.cjs
  packages/cypress-internal/src/commands.ts
  packages/fiori/package-scripts.cjs
  packages/main/package-scripts.cjs
  packages/tools/components-package/nps.js
Labels: for review

#11263 docs(website): playground height
  packages/website/src/components/Editor/index.js
Labels: for review

#11200 chore: create acc report folder
  packages/cypress-internal/src/acc_report/index
  packages/cypress-internal/src/acc_report/task.ts
Labels: for review

#11247 chore: use correct jsx in cypress mount function
  package.json
  packages/ai/cypress/support/component.ts
  packages/ai/cypress/tsconfig.json
  packages/base/cypress/support/component.ts
  packages/cypress-ct-ui5-webc/package.json
  packages/cypress-ct-ui5-webc/src/index.ts
  packages/cypress-internal/package.json
  packages/cypress-internal/src/commands.ts
  packages/cypress-internal/src/copy.js
  packages/cypress-internal/tsconfig.json
  packages/fiori/cypress/support/component.ts
  packages/fiori/cypress/tsconfig.json
  packages/main/cypress/specs/DateTimePicker.cy.tsx
  packages/main/cypress/specs/base/Events.cy.tsx
  packages/main/cypress/support/commands.ts
  packages/main/cypress/support/commands/Dialog.commands.ts
  packages/main/cypress/support/commands/Popover.commands.ts
  packages/main/cypress/support/commands/ResponsivePopover.commands.ts
  packages/main/cypress/support/commands/utils/popup-open.ts
  packages/main/cypress/support/component.ts
  packages/main/cypress/tsconfig.json
Labels: for review

#11363 fix(ui5-popover): fix arrow positioning
  packages/base/package.json
  packages/fiori/package.json
  packages/localization/package.json
  packages/main/package.json
  packages/main/src/Popover.ts
  packages/main/test/pages/Popover.html
  yarn.lock
Labels: 1.24, downport

#11389 fix(DragRegistry - TypeScript): correct import
  packages/base/src/util/dragAndDrop/DragRegistry.ts
Labels: for review, 1.24

#11318 feat(ui5-button): make click button preventable
  packages/fiori/src/ShellBar.ts
  packages/fiori/src/ShellBarItem.ts
  packages/fiori/src/UploadCollectionItem.ts
  packages/fiori/src/Wizard.ts
  packages/main/cypress/specs/Card.cy.tsx
  packages/main/cypress/specs/FormSupport.cy.tsx
  packages/main/src/AvatarGroup.ts
  packages/main/src/AvatarGroupTemplate.tsx
  packages/main/src/Button.ts
  packages/main/src/Carousel.ts
  packages/main/src/ExpandableText.ts
  packages/main/src/MultiComboBox.ts
  packages/main/src/Panel.ts
  packages/main/src/SplitButton.ts
  packages/main/src/TableHeaderCellActionBase.ts
  packages/main/src/TableRow.ts
  packages/main/src/TableRowActionBase.ts
  packages/main/src/Tokenizer.ts
  packages/tools/lib/cem/custom-elements-manifest.config.mjs
Labels: for review
