Repository SAP/ui5-webcomponents, pull requests merged in 2025-03, with the labels that each got.

#10936 chore: add tests for i18n
  packages/base/cypress/specs/i18n_texts.cy.tsx
  packages/base/test/test-elements/I18nChild.tsx
  packages/base/test/test-elements/I18nChild2.tsx
  packages/base/test/test-elements/I18nParent.tsx
Labels: for review

#10591 chore: remove cem dev context
  packages/tools/components-package/nps.js
  packages/tools/lib/cem/custom-elements-manifest.config.mjs
  packages/tools/lib/cem/validate.js
  patches/@custom-elements-manifest+analyzer+0.8.4.patch
Labels: for review

#11074 fix(ui5-carousel): update roles to match ACC specification
  packages/main/src/Carousel.hbs
  packages/main/src/Carousel.ts
  packages/main/src/i18n/messagebundle.properties
Labels: 1.24, downport

#11122 fix(ui5-menu): handle uncaught error on mouseout
  packages/main/src/Menu.ts
Labels: 1.24

#10887 chore(ui5-tabcontainer): remove unused classes getter
  packages/main/src/TabContainer.ts
Labels: Stale

#11093 chore: usage of build scripts
  packages/base/package-scripts.cjs
  packages/theming/css-vars-usage.json
  packages/theming/package-scripts.cjs
  packages/theming/package.json
Labels: for review

#11128 chore: integrate `cypress-axe` for accessibility testing
  .gitignore
  packages/cypress-internal/package.json
  packages/cypress-internal/src/acc_report/index
  packages/cypress-internal/src/acc_report/support.ts
  packages/cypress-internal/src/acc_report/task.ts
  packages/cypress-internal/src/commands.ts
  packages/cypress-internal/src/copy.js
  packages/cypress-internal/src/cypress.config.ts
  packages/cypress-internal/src/helpers.ts
  packages/cypress-internal/tsconfig.json
  packages/main/cypress/specs/Button.cy.tsx
  yarn.lock
Labels: for review
