Repository SAP/ui5-webcomponents, pull requests merged in 2025-02, with the labels that each got.

#10745 fix(framework): improve check for native popovers
  packages/base/src/features/patchPopup.ts
Labels: SAP SF, for review

#10657 fix(ui5-popover): popover arrow is aligned to the middle of the opener
  packages/fiori/test/specs/ShellBar.spec.js
  packages/main/src/Popover.ts
  packages/main/test/specs/MultiInput.spec.js
Labels: 1.24

#10807 refactor(ui5-multi-combobox): switch to .tsx
  packages/main/src/ComboBox.ts
  packages/main/src/MultiComboBox.hbs
  packages/main/src/MultiComboBox.ts
  packages/main/src/MultiComboBoxPopover.hbs
  packages/main/src/MultiComboBoxPopoverTemplate.tsx
  packages/main/src/MultiComboBoxTemplate.tsx
Labels: TOPIC RL, for review

#10827 chore: correct generation of events in cem
  packages/tools/lib/cem/custom-elements-manifest.config.mjs
  packages/tools/lib/cem/utils.mjs
Labels: for review

#10818 refactor: vite.config.js for enhanced flexibility and tool compatibility
  packages/create-package/template/vite.config.js
  packages/tools/components-package/vite.config.js
  packages/tools/lib/dev-server/virtual-index-html-plugin.js
Labels: for review
